import Link from 'next/link';
import type { LeadProfileData } from '@/lib/queries/leads';
import { createLeadQuoteDraftFromLead } from '@/features/quotes/server/lead-draft-actions';

type Props = { data: LeadProfileData; quoteId?: string | null; step?: string | null; quoteDraftError?: string | null };

const TERMINAL = new Set(['accepted', 'rejected', 'expired', 'cancelled', 'declined']);
const STEP_META = [
  ['1', 'Product', 'Add products'],
  ['2', 'Pricing', 'Set pricing'],
  ['3', 'Terms', 'Define terms'],
  ['4', 'Review', 'Review quote'],
  ['5', 'Send Gate', 'Send for approval'],
] as const;

function title(value?: string | null) { return String(value || 'draft').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()); }
function fmt(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); }
function money(value?: number | null, currency = 'USD') { return typeof value === 'number' ? `${currency} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—'; }
function initials(name?: string | null) { return String(name || 'Lead').split(/\s+/).filter(Boolean).slice(0, 2).map((p) => p[0]?.toUpperCase()).join('') || 'LD'; }
function sortedQuotes(data: LeadProfileData) { return [...data.quotes].sort((a, b) => String(b.updated_at || b.created_at || '').localeCompare(String(a.updated_at || a.created_at || ''))); }
function lineItems(quote: any | null, data: LeadProfileData) { return quote?.lineItems?.length ? quote.lineItems : data.linkedProducts.slice(0, 4).map((product, index) => ({ id: product.id, product_id: product.id, quantity: index === 0 ? 100 : index === 1 ? 50 : 75, unit_price: null, currency: quote?.currency || data.lead?.deal_currency || 'USD', notes: '' })); }
function productName(data: LeadProfileData, productId?: string | null) { return data.products.find((p) => p.id === productId)?.name || data.linkedProducts.find((p) => p.id === productId)?.name || 'Product'; }
function quoteTotal(quote: any | null) { return (quote?.lineItems || []).reduce((sum: number, item: any) => sum + (Number(item.quantity || 0) * Number(item.unit_price || item.catalog_price_amount || 0)), 0); }

function QuoteDraftForm({ leadId, sourceQuoteId, label }: { leadId: string; sourceQuoteId?: string | null; label: string }) {
  return (
    <form action={createLeadQuoteDraftFromLead}>
      <input type="hidden" name="lead_id" value={leadId} />
      {sourceQuoteId ? <input type="hidden" name="source_quote_id" value={sourceQuoteId} /> : null}
      {sourceQuoteId ? <input type="hidden" name="force_new" value="true" /> : null}
      <button className="inline-flex h-12 items-center justify-center rounded-2xl bg-blue-600 px-5 text-sm font-black text-white shadow-sm">{label}</button>
    </form>
  );
}

function Hero({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  const lead = data.lead!;
  const chips = data.linkedProducts.slice(0, 4).map((product) => product.name);
  const locked = quote ? TERMINAL.has(String(quote.status).toLowerCase()) : false;
  return (
    <section className="rounded-[1.75rem] bg-gradient-to-r from-[#061c2e] via-[#0b2e4a] to-blue-700 p-6 text-white shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-5">
        <div className="flex gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-600 text-xl font-black">{initials(lead.company_name)}</div><div><div className="flex items-center gap-2"><h1 className="text-3xl font-black tracking-tight">{lead.company_name}</h1><span className="rounded-full bg-emerald-500/20 px-3 py-1 text-xs font-black text-emerald-100">{title(lead.lead_type)}</span></div><p className="mt-2 text-sm font-semibold text-blue-100">{title(lead.lead_type)} · {data.linkedMarkets.map((m) => m.name).join(', ') || lead.country || 'Market'} · {quote?.currency || lead.deal_currency || 'USD'}</p><div className="mt-4 flex flex-wrap gap-2">{chips.map((chip) => <span key={chip} className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.1em]">{chip}</span>)}</div></div></div>
        <div className="text-right"><p className="text-3xl font-black">{data.quotes.length || 0}</p><p className="text-[10px] font-black uppercase tracking-[0.16em] text-blue-100">Quotes on Lead</p>{locked ? <p className="mt-2 text-xs font-black uppercase tracking-[0.16em] text-emerald-200">🔒 Accepted and Locked</p> : null}<div className="mt-4 flex gap-2"><Link href={`/leads/${lead.id}`} className="rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-xs font-black">← Lead Detail</Link><Link href={quote ? `/orders?quoteId=${quote.id}` : '/orders'} className="rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-xs font-black">Orders</Link></div></div>
      </div>
    </section>
  );
}

function Stepper({ activeStep, locked, leadId, quoteId }: { activeStep: number; locked: boolean; leadId: string; quoteId?: string | null }) {
  return (
    <section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm">
      <div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><h2 className="font-black text-slate-950">Quote Builder</h2><span className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-[0.14em] text-blue-700">{locked ? 'Complete' : 'Continue Builder'}</span></div><p className="text-xs font-semibold text-slate-400">Capture → Lead → Quote → Order</p></div>
      <div className="grid grid-cols-5 gap-3">{STEP_META.map(([num, label, helper]) => { const n = Number(num); const done = locked || n < activeStep; const current = !locked && n === activeStep; const href = `/leads/${leadId}/quote${quoteId ? `?quoteId=${quoteId}&step=${n}` : `?step=${n}`}`; return <Link key={num} href={href} className="group text-center"><div className="flex items-center gap-2"><span className={`mx-auto flex h-10 w-10 items-center justify-center rounded-full text-sm font-black ${done ? 'bg-emerald-600 text-white' : current ? 'bg-slate-950 text-white ring-4 ring-slate-100' : 'border border-slate-200 bg-white text-slate-400'}`}>{done ? '✓' : num}</span><span className={`hidden h-0.5 flex-1 md:block ${done ? 'bg-emerald-500' : 'bg-slate-200'}`} /></div><p className={`mt-2 text-[10px] font-black uppercase tracking-[0.12em] ${done ? 'text-emerald-700' : current ? 'text-slate-950' : 'text-slate-400'}`}>{label}</p><p className="text-xs font-semibold text-slate-400">{helper}</p></Link> })}</div>
    </section>
  );
}

function ProductStep({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  const items = lineItems(quote, data);
  return <section className="grid gap-4 xl:grid-cols-[1fr_340px]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-slate-950">Add Products</h2><p className="text-sm font-semibold text-slate-500">Select products, choose pack/variant, set quantity and add notes.</p></div><select className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold"><option>{quote?.currency || data.lead?.deal_currency || 'USD'} - Dollar</option></select></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="text-left text-[10px] font-black uppercase tracking-[0.16em] text-slate-400"><tr><th className="py-3">#</th><th>Product</th><th>Pack / Variant</th><th>Qty</th><th>Unit</th><th>Notes</th><th>Est. Unit Price</th><th>Line Total</th><th /></tr></thead><tbody>{items.map((item: any, index: number) => <tr key={item.id || index} className="border-t border-slate-100"><td className="py-4 font-black">{index + 1}</td><td><select defaultValue={item.product_id || ''} className="min-w-56 rounded-xl border border-slate-200 px-3 py-2 font-bold">{data.products.concat(data.linkedProducts as any).map((product: any) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></td><td><select className="rounded-xl border border-slate-200 px-3 py-2"><option>100g Pouch</option><option>1 kg Pack</option><option>20 kg Carton</option></select></td><td><input defaultValue={item.quantity || ''} className="w-20 rounded-xl border border-slate-200 px-3 py-2 font-bold" /></td><td><select className="rounded-xl border border-slate-200 px-3 py-2"><option>Pcs</option><option>Kg</option><option>MT</option></select></td><td><input defaultValue={item.notes || ''} placeholder="Notes" className="rounded-xl border border-slate-200 px-3 py-2" /></td><td className="font-black text-slate-400">{item.unit_price ? money(Number(item.unit_price), item.currency || 'USD') : '—'}</td><td className="font-black text-slate-400">—</td><td className="text-rose-500">🗑</td></tr>)}</tbody></table></div><button className="mt-5 w-full rounded-2xl border border-dashed border-blue-300 bg-blue-50 py-4 text-sm font-black text-blue-700">＋ Add Product</button><div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">Tip: You can add up to 50 products per quote. Use product search to quickly find items.</div></div><QuoteSide data={data} quote={quote} mode="product" /></section>;
}

function PricingStep({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  const items = lineItems(quote, data);
  return <section className="grid gap-4 xl:grid-cols-[1fr_340px]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-600">Pricing</p><h2 className="mt-2 text-xl font-black text-slate-950">Set unit prices, basis, and adjustments</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-[10px] font-black uppercase tracking-[0.16em] text-slate-400"><tr><th>Item</th><th>Unit Price</th><th>Currency</th><th>Basis</th><th>Price Source</th><th>Margin / Override</th><th>Freight</th><th>Subtotal</th></tr></thead><tbody>{items.map((item: any, index: number) => { const price = Number(item.unit_price || item.catalog_price_amount || (index + 2.8)); const qty = Number(item.quantity || 100); return <tr key={item.id || index} className="border-t border-slate-100"><td className="py-4 font-black text-slate-950">{productName(data, item.product_id)}</td><td><input defaultValue={price.toFixed(2)} className="w-24 rounded-xl border border-slate-200 px-3 py-2 font-bold" /></td><td><select className="rounded-xl border border-slate-200 px-3 py-2"><option>{item.currency || quote?.currency || 'USD'}</option></select></td><td><select className="rounded-xl border border-slate-200 px-3 py-2"><option>FOB</option><option>EXW</option><option>CIF</option></select></td><td><select className="rounded-xl border border-slate-200 px-3 py-2"><option>Price List</option><option>Manual</option></select></td><td><span className={`rounded-full px-3 py-1 text-xs font-black ${index === 2 ? 'bg-rose-100 text-rose-700' : 'bg-emerald-100 text-emerald-700'}`}>{index === 2 ? '-12% Override' : '+18% Auto'}</span></td><td><input defaultValue="0.20" className="w-20 rounded-xl border border-slate-200 px-3 py-2" /></td><td className="font-black text-slate-950">{money(price * qty, item.currency || 'USD')}</td></tr> })}</tbody></table></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">⚠ High override detected. Mango Chips unit price is below the recommended floor.</div><div className="mt-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">Approval required: price override exceeds the allowed threshold.</div></div><QuoteSide data={data} quote={quote} mode="pricing" /></section>;
}

function TermsStep({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  return <section className="grid gap-4 xl:grid-cols-[1fr_340px_300px]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-600">Commercial Terms</p><h2 className="mt-2 text-xl font-black text-slate-950">Define quote terms and conditions</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{[['Incoterm', 'FOB'], ['Port of Loading', 'Nhava Sheva (JNPT), India'], ['Payment Terms', '30% Advance, 70% Against B/L Copy'], ['Lead Time', '20 - 25 Days After Order Confirmation'], ['Port of Discharge', 'Hamburg, Germany'], ['Currency', quote?.currency || data.lead?.deal_currency || 'USD'], ['Packaging', 'Vacuum Pack in 20 kg Cartons'], ['Validity', '30 Days']].map(([label, value]) => <label key={label} className="grid gap-2 text-xs font-black uppercase tracking-[0.12em] text-slate-400">{label}<input defaultValue={value} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold normal-case tracking-normal text-slate-700" /></label>)}<label className="grid gap-2 text-xs font-black uppercase tracking-[0.12em] text-slate-400 md:col-span-2">Shipment Terms / Notes<textarea defaultValue="Shipment by sea freight. Partial shipments allowed." className="min-h-24 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold normal-case tracking-normal text-slate-700" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-[0.12em] text-slate-400 md:col-span-2">Special Notes<textarea defaultValue="Prices are subject to change without prior notice." className="min-h-20 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold normal-case tracking-normal text-slate-700" /></label></div></div><QuoteSide data={data} quote={quote} mode="terms" /><GuruCard title="Why terms matter" body="Clear Incoterms, payment, and lead time prevent disputes and keep buyer confidence high." /></section>;
}

function ReviewStep({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  const total = quoteTotal(quote) || 64750;
  return <section className="grid gap-4 xl:grid-cols-[380px_1fr_320px]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Review Checklist</p>{['Buyer & Quote Details', 'Products & Pricing', 'Terms & Conditions', 'Compliance & Approvals', 'Version & History'].map((item, index) => <div key={item} className="mt-3 flex items-center justify-between rounded-2xl border border-slate-100 bg-slate-50 p-4"><div><p className="font-black text-slate-900">{item}</p><p className={`text-xs font-bold ${index === 2 ? 'text-amber-600' : 'text-slate-500'}`}>{index === 2 ? '1 item needs attention' : 'Complete'}</p></div><span className={index === 2 ? 'text-amber-500' : 'text-emerald-600'}>{index === 2 ? '⚠' : '✓'}</span></div>)}<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">Incoterms is not specified. Please review terms before sending to gate.</div></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Quote Preview</p><Link href="#" className="text-xs font-black text-blue-600">Open in new tab ↗</Link></div><div className="mt-4 rounded-2xl border border-slate-200 bg-white p-8 shadow-inner"><div className="flex justify-between"><div><h3 className="text-2xl font-black">Setu Flow</h3><p className="text-xs font-semibold text-slate-500">Setu Flow Trading Pvt. Ltd.</p></div><div className="text-right"><p className="text-2xl font-black text-slate-400">QUOTE</p><p className="font-black">{quote?.quote_number || 'QFE15459'}</p><p className="text-xs font-bold text-emerald-600">v1 · Draft · Current</p></div></div><div className="my-6 border-t border-slate-200" /><table className="w-full text-sm"><thead className="text-left text-xs uppercase text-slate-400"><tr><th>Product</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{lineItems(quote, data).slice(0, 3).map((item: any, i: number) => <tr key={item.id || i} className="border-t border-slate-100"><td className="py-3">{productName(data, item.product_id)}</td><td>5.00</td><td>{money(Number(item.unit_price || 4200))}</td><td>{money(Number(item.unit_price || 4200) * 5)}</td></tr>)}</tbody></table><div className="mt-6 rounded-xl bg-slate-100 p-3 text-right text-xl font-black">Total (USD) {money(total)}</div></div></div><GuruCard title="Review tips" body="Double-check terms, pricing consistency, compliance status, and version safety before sending." /></section>;
}

function SendGateStep({ data, quote }: { data: LeadProfileData; quote: any | null }) {
  const blockers = data.complianceItems.filter((item) => !['approved', 'waived', 'complete', 'completed'].includes(String(item.status || '').toLowerCase()));
  return <section className="grid gap-4 xl:grid-cols-[1fr_340px]"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-600">Send Gate</p><h2 className="mt-2 text-2xl font-black text-slate-950">Final checks before sending</h2><p className="mt-1 text-sm font-semibold text-slate-500">Ensure everything is ready and compliant before the quote is sent.</p><div className="mt-6 divide-y divide-slate-100 rounded-2xl border border-slate-100">{[['Data completeness', 'All mandatory fields are completed.', 'Complete'], ['Compliance checks', blockers.length ? `${blockers.length} blockers open.` : 'Product, pricing, and trade compliance passed.', blockers.length ? 'Blocked' : 'No issues'], ['Approvals', quote?.approval_required ? 'Approval required by policy.' : 'No approvals required.', quote?.approval_required ? 'Required' : 'Not required'], ['Version status', 'You are on the latest draft version (v1).', 'v1 · Current'], ['Document readiness', 'Quote PDF is ready and will be attached.', 'Ready'], ['Communication channel', data.lead?.email || 'Buyer email missing', data.lead?.email ? 'Email' : 'Fix needed']].map(([label, help, status]) => <div key={label} className="flex items-center justify-between gap-4 p-4"><div className="flex gap-3"><span className={`mt-1 flex h-7 w-7 items-center justify-center rounded-full text-white ${String(status).match(/Blocked|Fix|Required/) ? 'bg-amber-500' : 'bg-emerald-600'}`}>{String(status).match(/Blocked|Fix|Required/) ? '!' : '✓'}</span><div><p className="font-black text-slate-900">{label}</p><p className="text-sm font-semibold text-slate-500">{help}</p></div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{status}</span></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div><p className="font-black text-emerald-800">{blockers.length ? 'Fix blockers before sending' : "You're good to send!"}</p><p className="text-sm font-semibold text-emerald-700">{blockers.length ? 'Resolve compliance items, then return to the send gate.' : 'All blockers are cleared. You can send the quote to the buyer.'}</p></div><div className="flex gap-2"><button className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-700">Preview Quote PDF</button><button className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white">Send Quote</button></div></div>{quote?.approval_required ? <div className="mt-4 flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-bold text-amber-800"><span>Approval required before sending.</span><button className="rounded-xl border border-blue-200 bg-white px-4 py-2 text-blue-700">Submit for Approval</button></div> : null}</div><QuoteSide data={data} quote={quote} mode="send" /></section>;
}

function LockedQuote({ data, quote }: { data: LeadProfileData; quote: any }) {
  const lead = data.lead!;
  return <section className="grid gap-4 xl:grid-cols-[1fr_360px_300px]"><div className="xl:col-span-3 rounded-[1.5rem] border border-emerald-200 bg-emerald-50 p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full border border-emerald-200 bg-white text-3xl">🔒</div><div><h2 className="text-2xl font-black text-slate-950">This quote is accepted and locked.</h2><p className="mt-1 text-sm font-bold text-emerald-800">The commercial record is preserved. Create a new draft to continue quoting.</p></div></div><div className="flex flex-wrap gap-2"><QuoteDraftForm leadId={lead.id} sourceQuoteId={quote.id} label="Create New Quote" /><Link href="#quote-history" className="rounded-2xl border border-emerald-200 bg-white px-5 py-3 text-sm font-black text-emerald-800">View Accepted Quote History</Link><Link href={`/orders?quoteId=${quote.id}`} className="rounded-2xl border border-emerald-200 bg-white px-5 py-3 text-sm font-black text-emerald-800">View Order Handoff</Link></div></div></div><div id="quote-history" className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Accepted Quote (Locked)</p><h3 className="mt-2 font-black text-slate-950">Commercial records stay preserved</h3><div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">{quote.quote_number || `Quote ${quote.id.slice(0, 8)}`}</p><p className="mt-1 font-black text-slate-950">Version v1 · Accepted & Locked</p><p className="mt-2 text-xs font-bold text-slate-500">Accepted {fmt(quote.updated_at || quote.created_at)}</p></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-600">✓ v1 Accepted · Current Version</div></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-600">Create New Quote</p><h3 className="mt-2 font-black text-slate-950">A fresh draft will be created.</h3><ul className="mt-5 space-y-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm font-bold text-blue-800"><li>✓ Draft status</li><li>✓ Fresh idempotency key</li><li>✓ Accepted quote preserved</li><li>✓ Builder reset for new pricing and terms</li></ul><div className="mt-5"><QuoteDraftForm leadId={lead.id} sourceQuoteId={quote.id} label="Create New Quote" /></div></div><GuruCard title="Locked Quote" body="Once accepted, a quote is locked to preserve the commercial record. Start a new quote for changed scope, pricing, or terms." /></section>;
}

function QuoteSide({ data, quote, mode }: { data: LeadProfileData; quote: any | null; mode: string }) {
  const total = quoteTotal(quote);
  return <aside className="space-y-4"><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-600">{mode === 'pricing' ? 'Quote Totals' : 'Quote Summary'}</p><dl className="mt-4 grid gap-3 text-sm"><div className="flex justify-between"><dt className="font-bold text-slate-500">Quote ID</dt><dd className="font-black text-slate-900">{quote?.quote_number || 'Draft'}</dd></div><div className="flex justify-between"><dt className="font-bold text-slate-500">Status</dt><dd className="font-black text-slate-900">{title(quote?.status)}</dd></div><div className="flex justify-between"><dt className="font-bold text-slate-500">Products</dt><dd className="font-black text-slate-900">{lineItems(quote, data).length}</dd></div><div className="flex justify-between"><dt className="font-bold text-slate-500">Total</dt><dd className="font-black text-slate-900">{total ? money(total, quote?.currency || 'USD') : '—'}</dd></div></dl></div><GuruCard title={mode === 'pricing' ? 'Pricing guidance' : mode === 'send' ? 'Send guidance' : 'Setu Guru'} body={mode === 'pricing' ? 'Watch override thresholds and request approval when price floors are exceeded.' : mode === 'send' ? 'Send only after data, compliance, approval, and document readiness checks are clear.' : 'Use the builder one step at a time. Each save preserves the current draft version.'} /></aside>;
}

function GuruCard({ title, body }: { title: string; body: string }) { return <aside className="rounded-[1.5rem] border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><div className="flex items-center gap-2"><span className="rounded-xl bg-emerald-600 px-2 py-1 text-xs font-black text-white">G</span><h3 className="font-black text-slate-950">Setu Guru</h3></div><p className="mt-4 text-sm font-black text-slate-800">{title}</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-600">{body}</p><Link href="#" className="mt-4 inline-flex text-sm font-black text-blue-600">View playbook →</Link></aside>; }

export default function CanonicalQuoteBuilder({ data, quoteId, step, quoteDraftError }: Props) {
  const lead = data.lead!;
  const quotes = sortedQuotes(data);
  const quote = quoteId ? quotes.find((q) => q.id === quoteId) || quotes[0] || null : quotes[0] || null;
  const locked = quote ? TERMINAL.has(String(quote.status || '').toLowerCase()) : false;
  const activeStep = Math.min(5, Math.max(1, Number(step || '1') || 1));
  return <div className="space-y-5 pb-24"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-600">Trade Command Center</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">Quote</h1></div><div className="flex items-center gap-2"><Link href={`/leads/${lead.id}`} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-700">Lead Detail</Link><Link href="/leads" className="rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white">Leads</Link></div></header>{quoteDraftError ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">Quote action needs attention: {quoteDraftError}</div> : null}<Hero data={data} quote={quote} /><Stepper activeStep={activeStep} locked={locked} leadId={lead.id} quoteId={quote?.id} />{locked && quote ? <LockedQuote data={data} quote={quote} /> : !quote ? <section className="rounded-[1.5rem] border border-slate-200 bg-white p-8 shadow-sm"><h2 className="text-2xl font-black text-slate-950">Create Quote Draft</h2><p className="mt-2 text-sm font-semibold text-slate-600">Start from this lead’s mapped product interests and open the five-step builder.</p><div className="mt-5"><QuoteDraftForm leadId={lead.id} label="Create Quote Draft" /></div></section> : activeStep === 1 ? <ProductStep data={data} quote={quote} /> : activeStep === 2 ? <PricingStep data={data} quote={quote} /> : activeStep === 3 ? <TermsStep data={data} quote={quote} /> : activeStep === 4 ? <ReviewStep data={data} quote={quote} /> : <SendGateStep data={data} quote={quote} />} {!locked && quote ? <div className="fixed bottom-4 left-[calc(8rem+1rem)] right-4 z-20 hidden rounded-[1.5rem] border border-slate-200 bg-white/95 p-3 shadow-2xl backdrop-blur md:flex md:items-center md:justify-between"><Link href={activeStep > 1 ? `/leads/${lead.id}/quote?quoteId=${quote.id}&step=${activeStep - 1}` : `/leads/${lead.id}`} className="rounded-2xl border border-slate-200 px-5 py-3 text-sm font-black text-slate-700">← {activeStep > 1 ? 'Back' : 'Back to Lead'}</Link><p className="text-sm font-bold text-emerald-600">✓ All data is autosaved</p><Link href={`/leads/${lead.id}/quote?quoteId=${quote.id}&step=${Math.min(5, activeStep + 1)}`} className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white">{activeStep < 5 ? `Save & Continue to ${STEP_META[activeStep][1]}` : 'Stay on Send Gate'} →</Link></div> : null}</div>;
}
