from pathlib import Path
p=Path('/mnt/data/v1762/src/features/leads/components/leads-workspace.tsx')
s=p.read_text()
# Type changes
s=s.replace("type QuoteLineItem = { id: string; quote_id: string | null; product_id: string | null; product_variant_id?: string | null; catalog_price_id?: string | null; catalog_price_amount?: number | null; catalog_price_currency?: string | null; quantity?: number | null; unit_price?: number | null; currency?: string | null; is_price_overridden?: boolean | null; override_reason?: string | null; overridden_by?: string | null; overridden_at?: string | null; notes?: string | null };",
"type QuoteLineItem = { id: string; quote_id: string | null; product_id: string | null; product_variant_id?: string | null; catalog_price_id?: string | null; catalog_price_amount?: number | null; catalog_price_currency?: string | null; quantity?: number | null; unit_price?: number | null; currency?: string | null; is_price_overridden?: boolean | null; override_reason?: string | null; overridden_by?: string | null; overridden_at?: string | null; notes?: string | null };")
s=s.replace("type Quote = { id: string; lead_id: string; rfq_id: string | null; status: string; currency: string | null; created_at: string; updated_at: string; notes?: string | null; quote_number?: string | null; current_version_id?: string | null; lineItems?: QuoteLineItem[] };",
"type Quote = { id: string; lead_id: string; rfq_id: string | null; status: string; currency: string | null; created_at: string; updated_at: string; notes?: string | null; notes_internal?: string | null; quote_number?: string | null; current_version_id?: string | null; approval_required?: boolean | null; approved_at?: string | null; approved_by?: string | null; lineItems?: QuoteLineItem[] };")
s=s.replace("type QuotePreviewSavePayload = { currency: string; lines: Array<{ id?: string; productId: string | null; productVariantId?: string | null; quantity: number; unitPrice: number | null; currency: string; catalogPriceAmount?: number | null; catalogPriceCurrency?: string | null; notes?: string | null; source?: string | null }> };",
"type QuotePreviewSavePayload = { currency: string; lines: Array<{ id?: string; productId: string | null; productVariantId?: string | null; quantity: number; unitPrice: number | null; currency: string; catalogPriceAmount?: number | null; catalogPriceCurrency?: string | null; notes?: string | null; source?: string | null; quoteAdjustmentType?: 'none' | 'discount_percent' | 'discount_amount' | 'markup_percent' | 'markup_amount'; quoteAdjustmentValue?: number | null; quoteAdjustmentReason?: string | null; approvalRequired?: boolean | null }> };")
# Add helper after countryCurrency
needle="function countryCurrency(country?: string | null) {\n  const key = String(country ?? '').toLowerCase().replace(/[^a-z]/g, '');\n  return COUNTRY_CURRENCY[key] ?? null;\n}\n"
insert=needle+"\nconst INCOTERM_HELP: Record<string, string> = {\n  EXW: 'EXW: buyer collects from factory; quote price is factory gate only.',\n  FOB: 'FOB/FCA: seller covers factory to port/carrier handoff; buyer handles main freight.',\n  CFR: 'CFR: seller covers freight to destination port; buyer handles insurance and import.',\n  CIF: 'CIF: seller covers freight and insurance to destination port.',\n  DDP: 'DDP: seller covers delivery, duty, taxes, and local handoff to buyer.'\n};\n\nconst QUOTE_ADJUSTMENT_OPTIONS = [\n  { value: 'none', label: 'No quote adjustment' },\n  { value: 'discount_percent', label: 'Discount %' },\n  { value: 'discount_amount', label: 'Discount amount' },\n  { value: 'markup_percent', label: 'Markup %' },\n  { value: 'markup_amount', label: 'Markup amount' },\n] as const;\n\nfunction getIncotermHelp(value: string) {\n  return INCOTERM_HELP[String(value || '').toUpperCase()] ?? 'Select the commercial handoff point before pricing the customer.';\n}\n\nfunction quoteAdjustmentDeltaPercent(base: number | null | undefined, adjusted: number | null | undefined) {\n  const baseline = Number(base ?? 0);\n  const next = Number(adjusted ?? 0);\n  if (!Number.isFinite(baseline) || baseline <= 0 || !Number.isFinite(next)) return 0;\n  return ((next - baseline) / baseline) * 100;\n}\n\nfunction applyQuoteAdjustment(base: number | null | undefined, type?: string | null, value?: number | null) {\n  const starting = Number(base ?? 0);\n  const amount = Number(value ?? 0);\n  if (!Number.isFinite(starting) || starting < 0) return 0;\n  if (!Number.isFinite(amount) || amount === 0 || !type || type === 'none') return starting;\n  if (type === 'discount_percent') return Math.max(0, starting * (1 - amount / 100));\n  if (type === 'markup_percent') return Math.max(0, starting * (1 + amount / 100));\n  if (type === 'discount_amount') return Math.max(0, starting - amount);\n  if (type === 'markup_amount') return Math.max(0, starting + amount);\n  return starting;\n}\n"
s=s.replace(needle,insert)
# DisplayLine fields
s=s.replace("    packSummary?: string | null;\n  };", "    packSummary?: string | null;\n    quoteAdjustmentType?: 'none' | 'discount_percent' | 'discount_amount' | 'markup_percent' | 'markup_amount';\n    quoteAdjustmentValue?: number | null;\n    quoteAdjustmentReason?: string | null;\n    approvalRequired?: boolean | null;\n    adjustmentDeltaPercent?: number | null;\n  };")
# add fields in sourceItems return objects (first occurrence has note)
s=s.replace("          note: item.notes ?? null,\n          pricingBasis:", "          note: item.notes ?? null,\n          quoteAdjustmentType: item.is_price_overridden ? 'discount_amount' : 'none',\n          quoteAdjustmentValue: item.is_price_overridden && item.catalog_price_amount != null && item.unit_price != null ? Math.abs(Number(item.catalog_price_amount) - Number(item.unit_price)) : null,\n          quoteAdjustmentReason: item.override_reason ?? null,\n          approvalRequired: item.is_price_overridden ? Math.abs(quoteAdjustmentDeltaPercent(item.catalog_price_amount, item.unit_price)) > 15 : false,\n          adjustmentDeltaPercent: quoteAdjustmentDeltaPercent(item.catalog_price_amount, item.unit_price),\n          pricingBasis:")
# add fields in coverage return
s=s.replace("        note: unitPrice == null ? `No catalog price found${marketLabel ? ` for ${marketLabel}` : ''}. Create/open draft preview creates the quote shell; fill price in saved quote workflow.` : `Catalog/reference price${marketLabel ? ` for ${marketLabel}` : ''}.`,\n        pricingBasis:", "        note: unitPrice == null ? `No catalog price found${marketLabel ? ` for ${marketLabel}` : ''}. Create/open draft preview creates the quote shell; fill price in saved quote workflow.` : `Catalog/reference price${marketLabel ? ` for ${marketLabel}` : ''}.`,\n        quoteAdjustmentType: 'none',\n        quoteAdjustmentValue: null,\n        quoteAdjustmentReason: null,\n        approvalRequired: false,\n        adjustmentDeltaPercent: 0,\n        pricingBasis:")
# updateEditableLine signature and body
old="""  const updateEditableLine = (lineId: string, field: 'quantity' | 'unitPrice', value: string) => {\n    const normalized = Number(value.replace(/,/g, ''));\n    setEditableLines((current) => current.map((line) => {\n      if (line.id !== lineId) return line;\n      const nextQuantity = field === 'quantity' ? (Number.isFinite(normalized) && normalized > 0 ? normalized : 0) : line.quantity;\n      const nextUnitPrice = field === 'unitPrice' ? (Number.isFinite(normalized) ? normalized : 0) : line.unitPrice;\n      return { ...line, quantity: nextQuantity, unitPrice: nextUnitPrice, total: nextQuantity * (nextUnitPrice ?? 0), priceStatus: nextUnitPrice && nextUnitPrice > 0 ? 'priced' : 'missing' };\n    }));\n  };\n"""
new="""  const updateEditableLine = (lineId: string, field: 'quantity' | 'unitPrice' | 'quoteAdjustmentType' | 'quoteAdjustmentValue' | 'quoteAdjustmentReason', value: string) => {\n    const normalized = field === 'quoteAdjustmentType' || field === 'quoteAdjustmentReason' ? NaN : Number(value.replace(/,/g, ''));\n    setEditableLines((current) => current.map((line) => {\n      if (line.id !== lineId) return line;\n      const nextQuantity = field === 'quantity' ? (Number.isFinite(normalized) && normalized > 0 ? normalized : 0) : line.quantity;\n      const manualPrice = field === 'unitPrice' ? (Number.isFinite(normalized) ? normalized : 0) : line.unitPrice;\n      const nextAdjustmentType = field === 'quoteAdjustmentType' ? value as DisplayLine['quoteAdjustmentType'] : (line.quoteAdjustmentType ?? 'none');\n      const nextAdjustmentValue = field === 'quoteAdjustmentValue' ? (Number.isFinite(normalized) ? normalized : 0) : (line.quoteAdjustmentValue ?? null);\n      const nextAdjustmentReason = field === 'quoteAdjustmentReason' ? value : (line.quoteAdjustmentReason ?? null);\n      const baseline = line.catalogPriceAmount ?? manualPrice ?? 0;\n      const nextUnitPrice = field === 'unitPrice' ? manualPrice : applyQuoteAdjustment(baseline, nextAdjustmentType, nextAdjustmentValue);\n      const deltaPercent = quoteAdjustmentDeltaPercent(baseline, nextUnitPrice);\n      const approvalRequired = Math.abs(deltaPercent) > 15;\n      return {\n        ...line,\n        quantity: nextQuantity,\n        unitPrice: nextUnitPrice,\n        quoteAdjustmentType: nextAdjustmentType,\n        quoteAdjustmentValue: nextAdjustmentValue,\n        quoteAdjustmentReason: nextAdjustmentReason,\n        adjustmentDeltaPercent: deltaPercent,\n        approvalRequired,\n        total: nextQuantity * (nextUnitPrice ?? 0),\n        priceStatus: nextUnitPrice && nextUnitPrice > 0 ? 'priced' : 'missing'\n      };\n    }));\n  };\n"""
s=s.replace(old,new)
# approval calculations after pricingReady
s=s.replace("  const hasQuoteDraft = Boolean(latestQuote);\n  const sendReady = blockerCount === 0 && pricingReady && hasQuoteDraft;\n  const approvalReady = hasQuoteDraft && displayLines.length > 0;", "  const hasQuoteDraft = Boolean(latestQuote);\n  const quoteAdjustmentApprovalRequired = displayLines.some((line) => Boolean(line.approvalRequired));\n  const latestQuoteApprovalRequired = Boolean(latestQuote?.approval_required) && !latestQuote?.approved_at;\n  const approvalPending = quoteAdjustmentApprovalRequired || latestQuoteApprovalRequired;\n  const sendReady = blockerCount === 0 && pricingReady && hasQuoteDraft && !approvalPending;\n  const approvalReady = hasQuoteDraft && displayLines.length > 0;")
# payload include fields
s=s.replace("      source: line.source,\n    })),", "      source: line.source,\n      quoteAdjustmentType: line.quoteAdjustmentType ?? 'none',\n      quoteAdjustmentValue: line.quoteAdjustmentValue ?? null,\n      quoteAdjustmentReason: line.quoteAdjustmentReason ?? null,\n      approvalRequired: Boolean(line.approvalRequired),\n    })),")
# validations require reason if approval
s=s.replace("      if (displayLines.some((line) => line.unitPrice == null || line.unitPrice <= 0)) return 'Every quote line needs a unit price above zero.';\n    }", "      if (displayLines.some((line) => line.unitPrice == null || line.unitPrice <= 0)) return 'Every quote line needs a unit price above zero.';\n      if (displayLines.some((line) => line.approvalRequired && !String(line.quoteAdjustmentReason ?? '').trim())) return 'Add a quote-only adjustment reason when the change requires approval.';\n    }")
# incoterm select replace options add descriptions
s=s.replace("                    {['FOB', 'CIF', 'EXW', 'DDP', 'CFR'].map((option) => <option key={option}>{option}</option>)}\n                  </select>\n                </div>", "                    {['FOB', 'CIF', 'EXW', 'DDP', 'CFR'].map((option) => <option key={option} value={option}>{option} — {getIncotermHelp(option)}</option>)}\n                  </select>\n                  <p className=\"text-[10px] leading-[1.45] text-[#64748b]\">{getIncotermHelp(termsIncoterm)}</p>\n                </div>")
# replace table header for unit price with baseline adjustment
s=s.replace("                      <th className=\"border-b border-[#e2e8f0] px-[10px] py-[6px]\">Unit price</th>\n                      <th className=\"border-b border-[#e2e8f0] px-[10px] py-[6px]\">Total</th>", "                      <th className=\"border-b border-[#e2e8f0] px-[10px] py-[6px]\">Baseline / adjustment</th>\n                      <th className=\"border-b border-[#e2e8f0] px-[10px] py-[6px]\">Quote price / total</th>")
# replace pricing row cells for price/total
oldrow="""                          <td className=\"px-[10px] py-[10px]\"><input title=\"Unit price updates this quote preview total immediately. Save via the governed quote workflow when ready.\" className=\"w-[90px] rounded-[6px] border border-[#cbd5e1] bg-white p-[5px_7px] text-right text-[12px] font-bold text-[#0f172a] outline-none\" value={price ?? ''} onChange={(event) => updateEditableLine(item.id, 'unitPrice', event.target.value)} placeholder=\"Price\" /></td>\n                          <td className=\"px-[10px] py-[10px] font-bold text-[#0f172a]\">{item.currency} {formatPreviewAmount(item.total)}</td>\n"""
newrow="""                          <td className=\"px-[10px] py-[10px]\">\n                            <div className=\"text-[10px] font-semibold text-[#475569]\">Default: {item.currency} {formatPreviewAmount(item.catalogPriceAmount ?? price ?? 0)}</div>\n                            <div className=\"mt-1 grid grid-cols-[1fr_72px] gap-1\">\n                              <select title=\"Quote-only adjustment type. This does not change product/category/default pricing.\" className=\"rounded-[6px] border border-[#cbd5e1] bg-white p-[5px] text-[10px] font-semibold text-[#0f172a] outline-none\" value={item.quoteAdjustmentType ?? 'none'} onChange={(event) => updateEditableLine(item.id, 'quoteAdjustmentType', event.target.value)}>\n                                {QUOTE_ADJUSTMENT_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}\n                              </select>\n                              <input title=\"Adjustment value in percent or quote currency based on selected adjustment type.\" className=\"rounded-[6px] border border-[#cbd5e1] bg-white p-[5px] text-right text-[10px] font-bold text-[#0f172a] outline-none\" value={item.quoteAdjustmentValue ?? ''} onChange={(event) => updateEditableLine(item.id, 'quoteAdjustmentValue', event.target.value)} placeholder=\"0\" />\n                            </div>\n                            <input title=\"Reason is required if the quote-only change exceeds the approval threshold.\" className=\"mt-1 w-full rounded-[6px] border border-[#e2e8f0] bg-white p-[5px] text-[10px] text-[#334155] outline-none\" value={item.quoteAdjustmentReason ?? ''} onChange={(event) => updateEditableLine(item.id, 'quoteAdjustmentReason', event.target.value)} placeholder=\"Adjustment reason for this quote only\" />\n                            {item.approvalRequired ? <div className=\"mt-1 rounded-[6px] border border-[#fde68a] bg-[#fffbeb] px-2 py-1 text-[10px] font-bold text-[#92400e]\">Approval needed: {formatPreviewAmount(Math.abs(item.adjustmentDeltaPercent ?? 0))}% change exceeds 15% threshold.</div> : null}\n                          </td>\n                          <td className=\"px-[10px] py-[10px]\"><input title=\"Final quote unit price for this quote only. Save via the governed quote workflow when ready.\" className=\"w-[90px] rounded-[6px] border border-[#cbd5e1] bg-white p-[5px_7px] text-right text-[12px] font-bold text-[#0f172a] outline-none\" value={price ?? ''} onChange={(event) => updateEditableLine(item.id, 'unitPrice', event.target.value)} placeholder=\"Price\" />\n                          <div className=\"mt-1 font-bold text-[#0f172a]\">{item.currency} {formatPreviewAmount(item.total)}</div></td>\n"""
s=s.replace(oldrow,newrow)
# pricing override old warning replace with approval summary
s=s.replace("                {subtotal > 0 && (subtotal / (displayLines.length || 1)) > 10000 ? (\n                  <div className=\"rounded-[6px] border border-[#fde68a] bg-[#fffbeb] p-[9px_13px] text-[11px] leading-[1.55] text-[#92400e]\">⚠ Pricing override detected — overrides above 10% require manager approval before send.</div>\n                ) : null}", "                {quoteAdjustmentApprovalRequired ? (\n                  <div className=\"rounded-[6px] border border-[#fde68a] bg-[#fffbeb] p-[9px_13px] text-[11px] leading-[1.55] text-[#92400e]\">⚠ Quote-only adjustment exceeds the 15% approval threshold. Save the draft, then request approval before sending.</div>\n                ) : null}")
# context card label
s=s.replace("            <div className=\"mb-2 text-[9px] font-bold uppercase tracking-[.16em] text-[#94a3b8]\">Approval threshold</div>\n            <div className=\"mb-[6px] text-[13px] font-bold text-[#0f172a]\">{blockerCount > 0 ? `${blockerCount} blocker${blockerCount === 1 ? '' : 's'}` : 'No blockers'}</div>\n            <div className=\"text-[11px] leading-[1.6] text-[#64748b]\">{sendReady ? 'Send gate clear — quote is safe to send.' : 'Resolve blockers before the send gate opens.'}</div>", "            <div className=\"mb-2 text-[9px] font-bold uppercase tracking-[.16em] text-[#94a3b8]\">Approval queue</div>\n            <div className=\"mb-[6px] text-[13px] font-bold text-[#0f172a]\">{approvalPending ? 'Approval pending' : blockerCount > 0 ? `${blockerCount} blocker${blockerCount === 1 ? '' : 's'}` : 'No blockers'}</div>\n            <div className=\"text-[11px] leading-[1.6] text-[#64748b]\">{approvalPending ? 'A quote-only adjustment needs owner approval. The requester sees pending until approved.' : sendReady ? 'Send gate clear — quote is safe to send.' : 'Resolve blockers before the send gate opens.'}</div>")
# readiness label include approval
s=s.replace("                    { label: 'Pricing complete', ok: pricingReady },\n                    { label: 'Compliance clear', ok: complianceItems.length === 0 },\n                    { label: 'Quote draft exists', ok: hasQuoteDraft },", "                    { label: 'Pricing complete', ok: pricingReady },\n                    { label: 'Approval cleared', ok: !approvalPending },\n                    { label: 'Compliance clear', ok: complianceItems.length === 0 },\n                    { label: 'Quote draft exists', ok: hasQuoteDraft },")
# Approval button text
s=s.replace("Request approval</button>", "{approvalPending ? 'Request approval / view queue' : 'Request approval'}</button>",1)
s=s.replace("Request approval</button>", "{approvalPending ? 'Request approval / view queue' : 'Request approval'}</button>",1)
# Add approval queue button in top tabs after Quote Preview button span perhaps
s=s.replace("          <span style={{ background: spotlightLead ? '#0c7fff' : '#e2e8f0', color: spotlightLead ? 'white' : '#94a3b8', borderRadius: '999px', padding: '1px 6px', fontSize: '9px', fontWeight: 800 }}>5 steps</span>\n        </button>", "          <span style={{ background: spotlightLead ? '#0c7fff' : '#e2e8f0', color: spotlightLead ? 'white' : '#94a3b8', borderRadius: '999px', padding: '1px 6px', fontSize: '9px', fontWeight: 800 }}>5 steps</span>\n        </button>\n        <button type=\"button\" onClick={() => setActiveView('quote')} style={{ padding: '12px 16px', fontSize: '12px', fontWeight: 700, color: quotes.some((quote) => quote.approval_required && !quote.approved_at) ? '#92400e' : '#94a3b8', borderTop: 'none', borderLeft: 'none', borderRight: 'none', borderBottom: '2px solid transparent', marginBottom: '-1px', display: 'flex', alignItems: 'center', gap: '6px', background: 'transparent', cursor: 'pointer' }}>\n          ✅ Approval Queue\n          <span style={{ background: quotes.some((quote) => quote.approval_required && !quote.approved_at) ? '#f59e0b' : '#e2e8f0', color: quotes.some((quote) => quote.approval_required && !quote.approved_at) ? 'white' : '#94a3b8', borderRadius: '999px', padding: '1px 6px', fontSize: '9px', fontWeight: 800 }}>{quotes.filter((quote) => quote.approval_required && !quote.approved_at).length}</span>\n        </button>")
# replace JSX typo if occurred? We'll check.
p.write_text(s)
