import { NextResponse } from 'next/server';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { requireWorkspace } from '@/lib/workspace/auth';
const MAX_ROWS=500;
type Row={contactName?:string;company?:string;mobile?:string;email?:string;city?:string;address?:string;country?:string;requirement?:string;notes?:string;assignedTo?:string;source?:string;profile?:string};
const clean=(v:unknown,n=2000)=>String(v??'').trim().slice(0,n); const phone=(v:unknown)=>clean(v,80).replace(/\D/g,''); const email=(v:unknown)=>clean(v,254).toLowerCase();
function indiaEvidence(v:string){return /\b(india|delhi|new delhi|noida|gurugram|gurgaon|ghaziabad|sahibabad|ludhiana|chennai|hapur|mumbai|bangalore|bengaluru|hyderabad|kolkata|pune|agra|uttar pradesh|\bup\b)\b/i.test(v)}
export async function POST(request:Request){
 const w=await requireWorkspace(); if(!w.organization||!w.user||!w.membership)return NextResponse.json({error:'Workspace access required.'},{status:401});
 const roles=w.currentRoles.map(r=>String(r).toLowerCase()), field=roles.includes('field_sales'); if(!w.canAccessAdmin&&!roles.some(r=>['owner','manager','admin','sales','field_sales'].includes(r)))return NextResponse.json({error:'Your role does not allow lead import.'},{status:403});
 const body=await request.json().catch(()=>null) as {action?:string;rows?:Row[];assignUserId?:string;fileName?:string}|null, rows=Array.isArray(body?.rows)?body!.rows:[]; if(!rows.length||rows.length>MAX_ROWS)return NextResponse.json({error:`Provide 1-${MAX_ROWS} lead rows.`},{status:400});
 const db=createAdminSupabaseClient() as any; const {data:members}=await db.from('organization_members').select('user_id,profiles(email,full_name)').eq('organization_id',w.organization.id).eq('is_active',true);
 const directory=(members??[]).map((m:any)=>{const p=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;return{userId:String(m.user_id),name:clean(p?.full_name,160),email:email(p?.email)}}); const me=directory.find((m:any)=>m.userId===w.user!.id); const forced=field?me:(body?.assignUserId?directory.find((m:any)=>m.userId===body.assignUserId):null);
 const {data:countries}=await db.from('countries').select('id,name,iso2_code,phone_code,market_id,search_aliases,markets(name)').eq('organization_id',w.organization.id).eq('is_active',true); const countryList=countries??[];
 const {data:existing}=await db.from('leads').select('id,phone,whatsapp_number,email').eq('organization_id',w.organization.id); const phones=new Set((existing??[]).flatMap((x:any)=>[phone(x.phone),phone(x.whatsapp_number)]).filter(Boolean)), emails=new Set((existing??[]).map((x:any)=>email(x.email)).filter(Boolean)); const seenP=new Set<string>(),seenE=new Set<string>(); const previewRows:any[]=[], inserts:any[]=[]; let dup=0,err=0;
 for(let i=0;i<rows.length;i++){const r=rows[i], company=clean(r.company,200), contact=clean(r.contactName,160), p=phone(r.mobile), e=email(r.email), location=[r.address,r.city,r.country].map(x=>clean(x,300)).filter(Boolean).join(', '); const errors:string[]=[]; if(!company&&!contact)errors.push('Company or Contact Name is required.'); if(!p&&!e)errors.push('Mobile or Email is required.'); if(e&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))errors.push('Email format is not valid.');
 let owner=forced||me; const wanted=clean(r.assignedTo,160).toLowerCase(); if(!field&&!body?.assignUserId&&wanted){const match=directory.filter((m:any)=>m.email===wanted||m.name.toLowerCase()===wanted); if(match.length===1)owner=match[0];} if(!owner)errors.push('A valid owner is required.');
 let c:any=null, confidence='unknown', basis=''; const explicit=clean(r.country,100).toLowerCase(); if(explicit){c=countryList.find((x:any)=>String(x.name).toLowerCase()===explicit||String(x.iso2_code).toLowerCase()===explicit); if(c){confidence='confirmed';basis='spreadsheet country';}}
 if(!c&&indiaEvidence(location)){c=countryList.find((x:any)=>String(x.iso2_code).toUpperCase()==='IN'); if(c){confidence='high';basis='location evidence';}}
 if(!c&&p.startsWith('91')){c=countryList.find((x:any)=>String(x.iso2_code).toUpperCase()==='IN'); if(c){confidence='high';basis='phone country code';}}
 const duplicate=(p&&(phones.has(p)||seenP.has(p)))||(e&&(emails.has(e)||seenE.has(e))); if(p)seenP.add(p);if(e)seenE.add(e); const marketName=Array.isArray(c?.markets)?c.markets[0]?.name:c?.markets?.name;
 if(errors.length){err++;previewRows.push({row:i+2,status:'error',message:errors.join(' '),ownerName:owner?.name,countryName:c?.name??null,marketName:marketName??null,countryConfidence:confidence});continue} if(duplicate){dup++;previewRows.push({row:i+2,status:'duplicate',message:'Possible duplicate by Mobile or Email.',ownerName:owner?.name,countryName:c?.name??null,marketName:marketName??null,countryConfidence:confidence});continue}
 previewRows.push({row:i+2,status:'ready',message:c?`Ready · ${c.name} (${confidence})`:'Ready · Country not confirmed',ownerName:owner.name,countryName:c?.name??null,marketName:marketName??null,countryConfidence:confidence}); inserts.push({organization_id:w.organization.id,lead_type:'buyer',owner_user_id:owner.userId,created_by:w.user.id,updated_by:w.user.id,company_name:company||contact,contact_name:contact||company,job_title:clean(r.profile,160)||null,phone:clean(r.mobile,80)||null,whatsapp_number:clean(r.mobile,80)||null,email:e||null,country:c?.name??null,country_id:c?.id??null,market_id:c?.market_id??null,products_or_needs:clean(r.requirement,1000)||null,notes:clean(r.notes)||null,source_type:'import',source_label:clean(r.source,160)||(field?'Field Sales Import':'Imported Prospect List'),industry_metadata:{city:clean(r.city,120)||null,address:clean(r.address,500)||null,country_inference:{confidence,basis,original:clean(r.country,100)||null}}}); }
 const summary={found:rows.length,ready:inserts.length,duplicates:dup,corrections:err}; if(body?.action!=='commit')return NextResponse.json({imported:0,...summary,previewRows}); if(!inserts.length)return NextResponse.json({imported:0,...summary,previewRows},{status:400}); const {data:inserted,error:insertError}=await db.from('leads').insert(inserts).select('id'); if(insertError)return NextResponse.json({error:insertError.message,...summary,previewRows},{status:500}); return NextResponse.json({imported:inserted?.length??inserts.length,...summary,previewRows});
}
