export type VCardIdentity = {
  fullName: string;
  email: string;
  organizationName: string;
  roleLabel?: string | null;
  username?: string | null;
  previewPath?: string | null;
  primaryPhone?: string | null;
  secondaryPhone?: string | null;
  website?: string | null;
  address?: string | null;
};

function escapeVCardValue(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/,/g, '\\,').replace(/;/g, '\\;');
}

function slugifyFilePart(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'setu-flow-contact';
}

function hasRealValue(value?: string | null) {
  const normalized = String(value ?? '').trim();
  return Boolean(normalized && !normalized.toLowerCase().startsWith('add '));
}

export function buildVCard(identity: VCardIdentity) {
  const lines = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    `FN:${escapeVCardValue(identity.fullName)}`,
    `ORG:${escapeVCardValue(identity.organizationName)}`,
    `EMAIL;TYPE=INTERNET:${escapeVCardValue(identity.email)}`,
  ];

  if (identity.roleLabel?.trim()) lines.push(`TITLE:${escapeVCardValue(identity.roleLabel.trim())}`);
  if (identity.username?.trim()) lines.push(`NICKNAME:${escapeVCardValue(identity.username.trim())}`);
  if (hasRealValue(identity.primaryPhone)) lines.push(`TEL;TYPE=CELL:${escapeVCardValue(String(identity.primaryPhone).trim())}`);
  if (hasRealValue(identity.secondaryPhone)) lines.push(`TEL;TYPE=WORK:${escapeVCardValue(String(identity.secondaryPhone).trim())}`);
  if (hasRealValue(identity.website)) lines.push(`URL:${escapeVCardValue(String(identity.website).trim())}`);
  if (hasRealValue(identity.previewPath)) lines.push(`URL;TYPE=WORK:${escapeVCardValue(String(identity.previewPath).trim())}`);
  if (hasRealValue(identity.address)) lines.push(`ADR;TYPE=WORK:;;${escapeVCardValue(String(identity.address).trim())}`);
  lines.push('NOTE:Generated by SETU Flow Global Contact Exchange');
  lines.push('END:VCARD');
  return `${lines.join('\r\n')}\r\n`;
}

export function getVCardFilename(identity: Pick<VCardIdentity, 'fullName'>) {
  return `${slugifyFilePart(identity.fullName)}-setu-flow-contact.vcf`;
}
