'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { Archive, CalendarPlus, Link2, Mail, MessageCircle, Pencil, PhoneCall, Plus, Search, Star, UserRound, X } from 'lucide-react';

type CrmLink = { id: string; entity_type: string; entity_id: string; is_primary?: boolean; record?: { id:string; company_name?:string|null; contact_name?:string|null; email?:string|null; lead_type?:string|null } | null };
type Candidate = { id:string; type:'lead'|'buyer'|'supplier'; company_name?:string|null; contact_name?:string|null; email?:string|null; href:string };
type Contact = { id:string; first_name:string; last_name:string; company:string|null; job_title:string|null; department:string|null; contact_role:string|null; email:string|null; phone:string|null; whatsapp_number:string|null; relationship_type:string; links:CrmLink[]; candidates:Candidate[] };
type FormState = { firstName:string; lastName:string; company:string; jobTitle:string; department:string; contactRole:string; email:string; phone:string; whatsappNumber:string; relationshipType:string; isPrimary:boolean };
const EMPTY:FormState={firstName:'',lastName:'',company:'',jobTitle:'',department:'',contactRole:'',email:'',phone:'',whatsappNumber:'',relationshipType:'other',isPrimary:false};
const RELATIONSHIPS=['buyer','supplier','prospect','customer','vendor','other'];
const DEPARTMENTS=['Purchasing / Procurement','Management / Owner','Finance / Accounts','Design / Creative','Operations','Logistics / Supply Chain','Quality / Compliance','Technical / Engineering','Sales','Marketing','Warehouse / Dispatch','Other'];
const CONTACT_ROLES=['Decision Maker','Buyer / Purchasing Contact','Approver','Influencer','Finance / Accounts Payable','Design Contact','Technical Contact','Operations Contact','Logistics / Delivery Contact','Owner / Director','Other'];
const displayName=(contact:Contact)=>`${contact.first_name} ${contact.last_name}`.trim()||contact.company||contact.email;
const title=(value:string)=>value ? value[0].toUpperCase()+value.slice(1) : value;

export function ContactsWorkspace(){
  const params=useSearchParams();
  const leadId=params.get('lead')||'';const leadCompany=params.get('company')||'';const leadContactName=params.get('contactName')||'';const leadNameParts=leadContactName.trim().split(/\s+/).filter(Boolean);const leadPrefill:FormState={...EMPTY,firstName:leadNameParts[0]||'',lastName:leadNameParts.slice(1).join(' '),company:leadCompany,jobTitle:params.get('jobTitle')||'',email:params.get('email')||'',phone:params.get('phone')||'',whatsappNumber:params.get('phone')||'',relationshipType:'buyer',isPrimary:Boolean(leadId)};
  const [contacts,setContacts]=useState<Contact[]>([]); const [selectedId,setSelectedId]=useState<string|null>(params.get('id')); const [search,setSearch]=useState('');
  const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(''); const [formOpen,setFormOpen]=useState(params.get('create')==='1'); const [editing,setEditing]=useState<Contact|null>(null); const [form,setForm]=useState<FormState>(()=>leadId?leadPrefill:{...EMPTY,email:params.get('email')||''}); const [saving,setSaving]=useState(false);
  async function load(){setLoading(true);try{const response=await fetch(`/api/contacts?q=${encodeURIComponent(search)}${leadId?`&lead=${encodeURIComponent(leadId)}`:''}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to load Contacts.');setContacts(payload.contacts||[]);if(!selectedId&&payload.contacts?.length)setSelectedId(payload.contacts[0].id);}catch(error){setNotice(error instanceof Error?error.message:'Unable to load Contacts.');}finally{setLoading(false);}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),search?220:0);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{const onSearch=(event:Event)=>setSearch(String((event as CustomEvent).detail??'').trim());window.addEventListener('setu-contacts-search',onSearch);return()=>window.removeEventListener('setu-contacts-search',onSearch);},[]);
  const selected=useMemo(()=>contacts.find(contact=>contact.id===selectedId)||contacts[0]||null,[contacts,selectedId]);
  function openNew(){setEditing(null);setForm({...EMPTY,company:leadCompany,relationshipType:leadId?'buyer':'other',isPrimary:Boolean(leadId&&contacts.length===0)});setFormOpen(true);}
  function openEdit(contact:Contact){setEditing(contact);const leadLink=leadId?contact.links.find(link=>link.entity_id===leadId):contact.links.find(link=>link.is_primary);setForm({firstName:contact.first_name,lastName:contact.last_name,company:contact.company||'',jobTitle:contact.job_title||'',department:contact.department||'',contactRole:contact.contact_role||'',email:contact.email||'',phone:contact.phone||'',whatsappNumber:contact.whatsapp_number||'',relationshipType:contact.relationship_type,isPrimary:Boolean(leadLink?.is_primary)});setFormOpen(true);}
  async function save(){setSaving(true);setNotice('');try{const response=await fetch(editing?`/api/contacts/${editing.id}`:'/api/contacts',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,leadId})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to save Contact.');setFormOpen(false);await load();if(payload.contact?.id)setSelectedId(payload.contact.id);}catch(error){setNotice(error instanceof Error?error.message:'Unable to save Contact.');}finally{setSaving(false);}}
  async function archive(contact:Contact){if(!confirm(`Archive ${displayName(contact)}? This does not delete or change any Lead.`))return;const response=await fetch(`/api/contacts/${contact.id}`,{method:'DELETE'});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||'Unable to archive Contact.');return;}setSelectedId(null);await load();}
  async function link(contact:Contact,candidate:Candidate){const response=await fetch(`/api/contacts/${contact.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({link:{entityType:candidate.type,entityId:candidate.id}})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||'Unable to link CRM record.');return;}await load();}
  async function makePrimary(contact:Contact){const item=(leadId?contact.links.find(link=>link.entity_id===leadId):contact.links[0]);if(!item)return;const response=await fetch(`/api/contacts/${contact.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({link:{entityType:item.entity_type,entityId:item.entity_id,isPrimary:true}})});const payload=await response.json().catch(()=>({}));if(!response.ok){setNotice(payload.error||'Unable to make this the primary contact.');return;}await load();}
  async function unlink(contact:Contact,item:CrmLink){const response=await fetch(`/api/contacts/${contact.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({unlink:{entityType:item.entity_type,entityId:item.entity_id}})});if(!response.ok){setNotice('Unable to unlink CRM record.');return;}await load();}
  return <div className="flex h-full min-h-[620px] bg-white text-slate-900">
    <aside className="w-full shrink-0 border-r border-slate-200 md:w-[360px]"><div className="border-b border-slate-200 p-4"><div className="flex items-center gap-2"><button onClick={openNew} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#0b2e4a] px-3 text-xs font-bold text-white"><Plus size={15}/>New contact</button><div className="ml-auto text-xs font-semibold text-slate-400">{contacts.length} contacts</div></div><label className="mt-3 flex items-center gap-2 rounded-lg border border-slate-200 px-3"><Search size={15} className="text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search contacts" className="min-w-0 flex-1 py-2 text-sm outline-none"/></label></div><div className="max-h-[calc(100vh-220px)] overflow-y-auto">{loading?<div className="p-5 text-sm text-slate-500">Loading contacts…</div>:contacts.map(contact=><button key={contact.id} onClick={()=>setSelectedId(contact.id)} className={`block w-full border-b border-slate-100 px-4 py-4 text-left ${selected?.id===contact.id?'bg-blue-50/70':'hover:bg-slate-50'}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-500"><UserRound size={17}/></div><div className="min-w-0"><div className="truncate text-sm font-bold text-slate-900">{displayName(contact)}</div><div className="mt-0.5 truncate text-xs text-slate-500">{contact.company||contact.email}</div><div className="mt-1 flex flex-wrap gap-1 text-[10px] font-bold uppercase tracking-wide text-blue-600">{contact.links.some(link=>link.is_primary)?<span className="rounded bg-amber-50 px-1.5 py-0.5 text-amber-700">Primary</span>:null}<span>{title(contact.relationship_type)}</span>{contact.department?<span className="text-slate-400">· {contact.department}</span>:null}</div></div></div></button>)}</div></aside>
    <main className="hidden min-w-0 flex-1 overflow-y-auto md:block">{selected?<div className="mx-auto max-w-4xl p-8"><div className="flex flex-wrap items-start gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-700"><UserRound size={25}/></div><div className="min-w-0 flex-1"><h1 className="text-2xl font-black text-slate-950">{displayName(selected)}</h1><p className="mt-1 text-sm text-slate-500">{[selected.job_title,selected.department,selected.company].filter(Boolean).join(' · ')||title(selected.relationship_type)}</p><div className="mt-2 flex flex-wrap gap-2">{selected.contact_role?<span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{selected.contact_role}</span>:null}{selected.links.some(link=>link.is_primary)?<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-[11px] font-bold text-amber-700"><Star size={11}/>Primary contact</span>:null}</div></div><button onClick={()=>openEdit(selected)} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600"><Pencil size={14}/>Edit</button><button onClick={()=>void archive(selected)} className="inline-flex items-center gap-2 rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700"><Archive size={14}/>Archive</button></div>
      <div className="mt-7 grid gap-4 sm:grid-cols-2"><Info label="Email" value={selected.email||'—'}/><Info label="Phone" value={selected.phone||'—'}/><Info label="WhatsApp" value={selected.whatsapp_number||selected.phone||'—'}/><Info label="Department" value={selected.department||'—'}/><Info label="Role" value={selected.contact_role||selected.job_title||'—'}/><Info label="Company" value={selected.company||'—'}/><Info label="Relationship" value={title(selected.relationship_type)}/></div>
      <div className="mt-6 flex flex-wrap gap-2">{selected.email?<Link href={`/mail?compose=1&to=${encodeURIComponent(selected.email)}`} className="inline-flex items-center gap-2 rounded-lg bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white"><Mail size={14}/>Email</Link>:null}{selected.whatsapp_number||selected.phone?<a href={`https://wa.me/${String(selected.whatsapp_number||selected.phone).replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><MessageCircle size={14}/>WhatsApp</a>:null}{selected.phone?<a href={`tel:${selected.phone}`} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700"><PhoneCall size={14}/>Call</a>:null}{selected.email?<Link href={`/calendar?compose=1&guest=${encodeURIComponent(selected.email)}&contact=${selected.id}`} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700"><CalendarPlus size={14}/>Meeting</Link>:null}{selected.links.some(link=>!link.is_primary)?<button onClick={()=>void makePrimary(selected)} className="inline-flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Star size={14}/>Make primary</button>:null}</div>
      <section className="mt-8 rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2"><Link2 size={16}/><h2 className="font-black">CRM relationships</h2></div><p className="mt-1 text-xs text-slate-500">Contacts stay independent. Linking does not create or modify a Lead.</p><div className="mt-4 space-y-2">{selected.links.length?selected.links.map(item=><div key={item.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase text-blue-600">{title(item.entity_type)}</div><Link href={`/leads/${item.entity_id}`} className="text-sm font-bold text-slate-800 hover:text-blue-700">{item.record?.company_name||item.record?.contact_name||'Open CRM record'}</Link></div><button onClick={()=>void unlink(selected,item)} className="text-xs font-bold text-slate-500">Unlink</button></div>):<div className="text-sm text-slate-400">No CRM record linked.</div>}</div>{selected.candidates.length?<div className="mt-4 border-t border-slate-100 pt-4"><div className="text-xs font-bold text-slate-600">Matching records by email</div><div className="mt-2 flex flex-wrap gap-2">{selected.candidates.map(candidate=><button key={`${candidate.type}-${candidate.id}`} onClick={()=>void link(selected,candidate)} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Link {title(candidate.type)} · {candidate.company_name||candidate.contact_name||candidate.email}</button>)}</div></div>:null}</section>
    </div>:<div className="grid h-full place-items-center text-sm text-slate-400">Select or create a contact.</div>}</main>
    {notice?<div className="fixed bottom-6 right-6 z-[700] max-w-md rounded-xl bg-slate-950 px-4 py-3 text-sm text-white shadow-xl">{notice}</div>:null}
    {formOpen?<div className="fixed inset-0 z-[700] grid place-items-center bg-slate-950/35 p-4" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setFormOpen(false);}}><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">Setu Contacts</div><h2 className="text-xl font-black">{editing?'Edit contact':'New contact'}</h2></div><button disabled={saving} onClick={()=>setFormOpen(false)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="First name" value={form.firstName} onChange={value=>setForm({...form,firstName:value})}/><Field label="Last name" value={form.lastName} onChange={value=>setForm({...form,lastName:value})}/><Field label="Company" value={form.company} onChange={value=>setForm({...form,company:value})}/><Field label="Job title" value={form.jobTitle} onChange={value=>setForm({...form,jobTitle:value})}/><Field label="Department" value={form.department} onChange={value=>setForm({...form,department:value})} list="contact-departments"/><Field label="Contact role" value={form.contactRole} onChange={value=>setForm({...form,contactRole:value})} list="contact-roles"/><Field label="Email" value={form.email} type="email" onChange={value=>setForm({...form,email:value})}/><Field label="Phone" value={form.phone} onChange={value=>setForm({...form,phone:value})}/><Field label="WhatsApp" value={form.whatsappNumber} onChange={value=>setForm({...form,whatsappNumber:value})}/><label className="text-xs font-bold text-slate-600">Relationship<select value={form.relationshipType} onChange={event=>setForm({...form,relationshipType:event.target.value})} className="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-3 text-sm font-medium text-slate-800">{RELATIONSHIPS.map(item=><option key={item} value={item}>{title(item)}</option>)}</select></label>{leadId?<label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={form.isPrimary} onChange={event=>setForm({...form,isPrimary:event.target.checked})}/>Primary contact for this lead</label>:null}</div><datalist id="contact-departments">{DEPARTMENTS.map(item=><option key={item} value={item}/>)}</datalist><datalist id="contact-roles">{CONTACT_ROLES.map(item=><option key={item} value={item}/>)}</datalist><div className="mt-6 flex justify-end gap-2"><button disabled={saving} onClick={()=>setFormOpen(false)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold text-slate-600">Cancel</button><button disabled={saving||!form.email.trim()} onClick={()=>void save()} className="rounded-lg bg-[#0b2e4a] px-5 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?'Saving…':'Save contact'}</button></div></div></div>:null}
  </div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 break-words text-sm font-bold text-slate-800">{value}</div></div>}
function Field({label,value,onChange,type='text',list}:{label:string;value:string;onChange:(value:string)=>void;type?:string;list?:string}){return <label className="text-xs font-bold text-slate-600">{label}<input type={type} list={list} value={value} onChange={event=>onChange(event.target.value)} className="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-3 text-sm font-medium text-slate-800 outline-none focus:border-blue-400"/></label>}
