import { SETU_GURU_PAGE_CONTEXTS, getSetuGuruPageContext, routeMatchesSetuGuruPath, type SetuGuruPageContext, type SetuGuruRouteKey } from './page-context';

export type SetuGuruHelpTopic = {
  id: string;
  slug: string;
  title: string;
  routeKeys: SetuGuruRouteKey[];
  routes: string[];
  helpFile: string;
  tags: string[];
  summary: string;
  answer: string[];
  commonBlockers: string[];
  dataSources: string[];
  allowedActions: string[];
  approvalRules: string[];
  actions: string[];
};

type TopicSeed = Partial<SetuGuruHelpTopic> & Pick<SetuGuruHelpTopic, 'id' | 'slug' | 'title' | 'tags' | 'summary' | 'answer' | 'approvalRules' | 'actions'>;

function topicFromContext(routeKey: SetuGuruRouteKey, seed: TopicSeed): SetuGuruHelpTopic {
  const context = SETU_GURU_PAGE_CONTEXTS.find((item) => item.routeKey === routeKey) ?? SETU_GURU_PAGE_CONTEXTS[0];
  return { routeKeys: [routeKey], routes: context.routes, helpFile: context.helpFile, commonBlockers: context.commonBlockers, dataSources: context.dataSources, allowedActions: context.allowedActions, ...seed };
}

export const SETU_GURU_HELP_TOPICS: SetuGuruHelpTopic[] = [
  topicFromContext('dashboard', { id: 'dashboard', slug: 'dashboard', title: 'Dashboard help', tags: ['dashboard', 'overview', 'queue', 'market', 'country', 'blocker', 'next action'], summary: 'Use Dashboard to understand queue health, market health, and what needs intervention now.', answer: ['Start with the visible queue, market, country, and blocker signals before giving generic CRM advice.', 'The safest Dashboard action is usually to open the specific Follow-up, Quote, Approval, Order, or Admin route that owns the blocker.', 'If a visible blocker involves compliance, documents, pricing, or send readiness, check live organization context before answering.'], approvalRules: ['Humans approve sends, waivers, write-backs, pricing changes, and order execution changes.'], actions: ['Open Leads', 'Open Quotes', 'Open Orders', 'Review organization profile'] }),
  topicFromContext('leads', { id: 'leads', slug: 'leads', title: 'Follow-up help', tags: ['lead', 'buyer', 'supplier', 'follow up', 'qualification', 'quote prep', 'next action'], summary: 'Use Follow-up to qualify the record, map product interest, and resolve quote blockers.', answer: ['For a lead question, identify the active lead, buyer/supplier type, country, product interest, next step, and linked quote before answering.', 'A lead is quote-ready only when product interest, buyer/country context, quote terms, pricing, and quote-stage blockers are clear.', 'Advisory dispatch documents should not be treated as quote-send blockers unless an active rule makes them mandatory at quote stage.'], approvalRules: ['Humans approve quote send, price deviation approval, compliance waivers, lead deletion, and write-back to defaults.'], actions: ['Open Leads', 'Check this quote blocker', 'Open compliance'] }),
  topicFromContext('pipeline', { id: 'pipeline', slug: 'pipeline', title: 'Pipeline help', tags: ['pipeline', 'kanban', 'stage', 'deal value', 'risk', 'quote ready', 'leads'], summary: 'Premium pipeline kanban with value waterfall bar (pipeline by stage), card density toggle (Full/Compact/Micro), stage readiness rings, 7-day momentum sparklines, and lane health bars.', answer: ['Pipeline is for managing deal stages, revenue movement, blockers, follow-up pressure, and quote-ready actions.', 'Leads is for managing contact details, product interests, qualification notes, and profile cleanup.', 'Use the pipeline board density toggle (Full/Compact/Micro) to see more cards at once. Compact is the default for 50+ leads.'], approvalRules: ['Humans approve stage moves, quote conversion, pricing, compliance, and quote sends.'], actions: ['Open Leads', 'Open Quotes', 'Check blockers'] }),
  topicFromContext('products', { id: 'products', slug: 'products', title: 'Products help', tags: ['product', 'catalog', 'hsn', 'hs code', 'pricing', 'variant', 'quote ready', 'default boundary', 'readiness'], summary: 'Use Products as the operating catalog and source of quote-ready product defaults.', answer: ['Product help should separate product defaults, category defaults, organization defaults, and quote-only adjustments.', 'Quote-ready product checks should look for HSN/HS code, pack, MOQ, origin, shelf life, lead time, category, and pricing assumptions.', 'For daily catalog work, open Products. For governance, imports, category defaults, and setup health, open Product Management.', 'Use live catalog search for product counts and missing HSN; use live research for HS/HSN, tariffs, duties, and country requirements.'], approvalRules: ['Humans approve saved product/category/organization default changes and compliance decisions. Quote-only price changes must stay in quote workspace.'], actions: ['Open Products', 'Check catalog readiness', 'Open Product Management', 'Ask live research'] }),
  topicFromContext('quotes', { id: 'quotes', slug: 'quotes', title: 'Quotes help', tags: ['quote', 'quote builder', 'approval', 'send', 'currency', 'incoterm', 'pdf'], summary: 'Use Quotes to assemble commercial lines, check approvals, and send only when quote-stage blockers are resolved.', answer: ['Quote answers should check quote terms, lines, display currency, approval status, mandatory quote-send rules, and advisory dispatch documents separately.', 'Quote-only price adjustments must not rewrite product, category, or organization defaults.', 'Quote PDFs should keep product details, pack, MOQ, origin, shelf life, lead time, tax wording, and incoterms clear.'], approvalRules: ['Humans approve quote send, price deviation approval, compliance waivers, and write-back to defaults.'], actions: ['Open Quotes', 'Open compliance', 'Check this quote blocker'] }),
  topicFromContext('orders', { id: 'orders', slug: 'orders', title: 'Orders help', tags: ['order', 'execution cockpit', 'actual lines', 'buyer doc', 'packing', 'freight queue', 'finance queue', 'pending adapter', 'manual whatsapp', 'final invoice', 'closeout'], summary: 'Use Orders Execution Cockpit after quote acceptance to manage actual lines, buyer docs, packing, pending freight queue, processing, delivery note, final invoice, pending finance queue, and paid closeout.', answer: ['The Orders Execution Cockpit has 8 stages: Actual Lines, Buyer Doc, Packing, Freight Queue, Processing, Delivery Note, Final Invoice, and Paid & Closed.', 'Finance queue-ready and Freight queue-ready mean pending adapter payload readiness only. No live Xero, QuickBooks, Tally, Flexport, Freightos, DHL, carrier booking, bank feed, payment processor, or WhatsApp Business API integration is live.', 'WhatsApp opens manually with a tracked preview link. Setu Guru can explain blockers and draft checklists, but it must not approve, send, waive, close, sync finance, book freight, or claim provider delivery.'], approvalRules: ['Humans approve actual order lines, order documents, trade requirement confirmation/waiver, packing, freight request approval, shipment/dispatch changes, finance/payment closeout, and order closeout.'], actions: ['Open Orders', 'Check order blockers', 'Explain KPI filters', 'Draft dispatch evidence checklist', 'Review Finance/Freight pending adapter boundary'] }),
  topicFromContext('compliance', { id: 'compliance', slug: 'compliance', title: 'Compliance and document help', tags: ['compliance', 'document', 'evidence', 'certificate', 'coa', 'packing list', 'waiver', 'required'], summary: 'Use Compliance to decide what is mandatory now, what is advisory later, and what evidence needs review.', answer: ['Always separate advisory guidance, mandatory blockers, human approval actions, and live research suggestions.', 'COA and Packing List can be advisory before dispatch unless organization policy explicitly makes them quote-send mandatory.', 'Setu Guru may suggest evidence, but a human must review, approve, waive, or clear compliance.'], approvalRules: ['Humans approve evidence, waivers, compliance clearing, document deletes, and policy changes.'], actions: ['Open compliance', 'Open lead documents', 'Ask AI evidence checklist'] }),
  topicFromContext('trade-events', { id: 'trade-events', slug: 'trade-events', title: 'Trade event capture help', tags: ['trade event', 'capture', 'scan', 'business card', 'convert lead', 'event'], summary: 'Use Trade Events to capture, clean, and convert event contacts into follow-up leads.', answer: ['Capture should stay fast: clean company, contact, email, phone, country, lead type, and product interest before conversion.', 'Check for duplicates and low-confidence scanned fields before creating or updating a lead.', 'Converted records should land in Follow-up with a clear next action.'], approvalRules: ['Humans approve questionable conversions, duplicate merges, overwrites, deletes, and any fake-data seeding.'], actions: ['Open Leads', 'Check blockers'] }),
  topicFromContext('admin-organization', { id: 'admin-organization', slug: 'admin-organization', title: 'Organization setup help', tags: ['admin', 'organization', 'setup', 'currency', 'country', 'roles', 'markets', 'defaults'], summary: 'Use Admin Organization for governance, setup, roles, defaults, and compliance policy.', answer: ['Setup should cover company profile, address, default country, default currency, markets, ports, terms, pricing defaults, compliance rules, users, and roles.', 'Daily operating work belongs in Dashboard, Leads, Products, Quotes, Orders, or Compliance; Admin is for setup and governance.', 'Role and policy changes require owner/admin review.'], approvalRules: ['Owners/admins approve roles, compliance policy, organization defaults, pricing defaults, and destructive changes.'], actions: ['Review organization profile', 'Open Product Management', 'Open compliance'] }),
  topicFromContext('pricing-calculator', { id: 'pricing-calculator', slug: 'pricing-calculator', title: 'Pricing calculator help', routeKeys: ['pricing-calculator', 'products', 'quotes', 'admin-organization'], tags: ['pricing calculator', 'default margin', 'markup', 'freight', 'duty', 'fx', 'quote-only'], summary: 'Use pricing help to explain organization, category, product, and quote-only pricing assumptions.', answer: ['Explain the hierarchy clearly: organization default, category default, product override, then quote-only adjustment.', 'Setu Guru can suggest draft assumptions, but humans approve saved defaults, margin decisions, quote sends, and write-backs.', 'Use live research for margin benchmarks, duties, tariffs, and country assumptions.'], approvalRules: ['Humans approve saved defaults, margin approvals, quote sends, and all write-backs.'], actions: ['Open Product Management', 'Open Products', 'Ask live research'] }),
  topicFromContext('trial', { id: 'trial', slug: 'trial', title: 'Guided trial workspace help', routeKeys: ['trial', 'leads', 'quotes', 'orders', 'products', 'pricing-calculator'], tags: ['trial', 'guided trial', 'two lead limit', 'stark packmate', 'packaging converter', 'dimensional pricing', 'trial template'], summary: 'Use Guided Trial to validate a controlled two-lead capture-to-dispatch flow before converting the workspace.', answer: ['Guided trials are intentionally capped: two leads, one quote, one order, and one user unless the workspace is converted.', 'For Stark Packmate, validate the Packaging Converter template, seeded packaging products, and dimensional pricing estimate before adding custom catalog data.', 'Setu Guru can explain limits, route users to Leads, Products, Quotes, Orders, or /trial, and draft a pricing checklist, but humans approve conversion, pricing defaults, quote send, and dispatch.'], approvalRules: ['Humans approve conversion, saved pricing defaults, quote sends, dispatch, and trial limit changes.'], actions: ['Open Guided Trial', 'Open Products', 'Open Leads', 'Review Stark Packmate pricing'] }),
  topicFromContext('setu-guru', { id: 'setu-guru', slug: 'setu-guru', title: 'Setu Guru response policy help', routeKeys: ['setu-guru', 'dashboard', 'leads', 'pipeline', 'products', 'quotes', 'orders', 'compliance'], tags: ['setu guru', 'help', 'policy', 'approval', 'live search', 'research', 'page context'], summary: 'Use Setu Guru policy to choose the right source and keep human approval boundaries clear.', answer: ['Answer in this order: current page context, live organization data, route help registry, live research when required, then generic guidance.', 'Never approve, waive, write back, send, delete, clear compliance, advance orders, or make pricing/compliance decisions without human approval.', 'Use live research with sources for HS/HSN, tariffs, duties, country requirements, and margin benchmarks.'], approvalRules: ['Human approval is required for write-back, send, waive, approve, delete, clear compliance, pricing, and execution decisions.'], actions: ['Ask live research', 'Review sources', 'Check blockers'] }),
];

function normalize(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); }
export function getHelpTopicById(id: string) { return SETU_GURU_HELP_TOPICS.find((topic) => topic.id === id || topic.slug === id) ?? null; }
export function getSetuGuruRouteTopics(pathname: string) { const pageContext = getSetuGuruPageContext(pathname); const matches = SETU_GURU_HELP_TOPICS.filter((topic) => topic.routeKeys.includes(pageContext.routeKey) || topic.routes.some((route) => routeMatchesSetuGuruPath(pathname, route))); return matches.length ? matches : SETU_GURU_HELP_TOPICS; }
export const getHelpTopicsForPath = getSetuGuruRouteTopics;
export function getBestSetuGuruHelpTopic(question: string, pathname: string) {
  const routeTopics = getSetuGuruRouteTopics(pathname);
  const q = normalize(question);
  if (!q) return routeTopics[0] ?? SETU_GURU_HELP_TOPICS[0];
  const WORKFLOW_KEYWORDS: Record<string, string[]> = {
    quotes: ['quote', 'quotation', 'quote approval', 'send quote', 'quote builder', 'quote lifecycle'],
    orders: ['order', 'dispatch', 'fulfillment', 'freight', 'packing', 'shipment', 'invoice', 'finance queue'],
    leads: ['lead', 'follow up', 'pipeline stage'],
    compliance: ['compliance', 'certificate', 'coa', 'waiver'],
    products: ['hsn', 'hs code', 'sku', 'variant', 'pricing rule'],
    trial: ['trial', 'guided trial', 'stark packmate', 'packmate', 'dimensional pricing', 'two lead'],
  };
  const currentRouteKey = getSetuGuruPageContext(pathname).routeKey;
  const questionMentionsOtherWorkflow = Object.entries(WORKFLOW_KEYWORDS).some(([key, words]) => {
    if (currentRouteKey === key) return false;
    return words.some((word) => q.includes(normalize(word)));
  });
  const ranked = SETU_GURU_HELP_TOPICS.map((topic) => {
    const isCurrentRouteMatch = routeTopics.some((routeTopic) => routeTopic.id === topic.id);
    const routeScore = isCurrentRouteMatch && !questionMentionsOtherWorkflow ? 4 : 0;
    const haystack = normalize([topic.title, topic.summary, ...topic.tags, ...topic.answer, ...topic.commonBlockers, ...topic.dataSources, ...topic.allowedActions].join(' '));
    const wordScore = q.split(/\s+/).filter(Boolean).reduce((score, token) => score + (haystack.includes(token) ? 1 : 0), 0);
    return { topic, score: routeScore + wordScore };
  }).sort((a, b) => b.score - a.score);
  return ranked[0]?.topic ?? routeTopics[0] ?? SETU_GURU_HELP_TOPICS[0];
}

export const getBestHelpTopic = getBestSetuGuruHelpTopic;
export function getSetuGuruActionHref(action: string) { const normalized = normalize(action); if (normalized.includes('guided trial')) return '/trial'; if (normalized.includes('stark packmate')) return '/trial'; if (normalized.includes('catalog readiness')) return '/products?gap=has_gap'; if (normalized.includes('dispatch evidence')) return '/documents'; if (normalized.includes('lead document')) return '/documents'; if (normalized.includes('compliance')) return '/compliance'; if (normalized.includes('product management')) return '/admin/product-management'; if (normalized.includes('open products')) return '/products'; if (normalized.includes('organization')) return '/admin/organization#company-profile'; if (normalized.includes('open leads')) return '/leads'; if (normalized.includes('order')) return '/orders'; if (normalized.includes('quote')) return '/quotes'; if (normalized.includes('approval') || normalized.includes('release')) return '/approval-send'; if (normalized.includes('product')) return '/products'; return null; }
export function getRouteHelpSummary(pathname: string) { const context: SetuGuruPageContext = getSetuGuruPageContext(pathname); const topic = getHelpTopicById(context.helpTopicId) ?? getSetuGuruRouteTopics(pathname)[0]; return { routeKey: context.routeKey, routeTitle: context.title, helpFile: topic.helpFile, summary: topic.summary, suggestedPrompts: context.suggestedPrompts, liveSearchModes: context.liveSearchModes, approvalRequiredActions: context.approvalRequiredActions }; }
