import { SETU_GURU_PAGE_CONTEXTS, getSetuGuruPageContext, routeMatchesSetuGuruPath, type SetuGuruPageContext, type SetuGuruRouteKey } from './page-context';

export const SETU_GURU_ROUTE_HELP_DOCS = [
  'docs/help/dashboard.md','docs/help/leads.md','docs/help/products.md','docs/help/quotes.md','docs/help/orders.md','docs/help/compliance.md','docs/help/trade-events.md','docs/help/admin-organization.md','docs/help/pricing-calculator.md','docs/help/setu-guru.md','docs/help/growth-agent.md','docs/setu-guru/SETU_GURU_PACKAGING_INTELLIGENCE.md','docs/packaging/SPRINT_50_PACKAGING_INTELLIGENCE.md',
] as const;

export type SetuGuruHelpTopic = {
  id: string; slug: string; title: string; routeKeys: SetuGuruRouteKey[]; routes: string[]; helpFile: string; tags: string[]; summary: string; answer: string[]; commonBlockers: string[]; dataSources: string[]; allowedActions: string[]; approvalRules: string[]; actions: string[];
};

type TopicSeed = Partial<SetuGuruHelpTopic> & Pick<SetuGuruHelpTopic, 'id'|'slug'|'title'|'tags'|'summary'|'answer'|'approvalRules'|'actions'>;

function topicFromContext(routeKey: SetuGuruRouteKey, seed: TopicSeed): SetuGuruHelpTopic {
  const context = SETU_GURU_PAGE_CONTEXTS.find((item) => item.routeKey === routeKey) ?? SETU_GURU_PAGE_CONTEXTS[0];
  return { routeKeys:[routeKey], routes:context.routes, helpFile:context.helpFile, commonBlockers:context.commonBlockers, dataSources:context.dataSources, allowedActions:context.allowedActions, ...seed };
}

const PACKAGING_APPROVAL = ['Humans approve pricing/template changes, quote send, artwork/proof approval, compliance decisions, production-stage movement, packing, and dispatch. Setu Guru remains advisory.'];
const PACKAGING_DOC = 'docs/setu-guru/SETU_GURU_PACKAGING_INTELLIGENCE.md';

export const SETU_GURU_HELP_TOPICS: SetuGuruHelpTopic[] = [
  topicFromContext('packaging-templates',{id:'packaging-templates',slug:'packaging-templates',title:'How Packaging pricing is calculated',helpFile:PACKAGING_DOC,tags:['packaging','pricing','material','m2','m²','pouch','gusset','finish','zipper','moq','setup','rush','waste','flexo','cylinder'],summary:'Packaging Pricing Templates are the governed rules used by both Live Preview and Quote Builder.',answer:['For pouch pricing, area per pouch = Width × (Height + Gusset) × 2 ÷ 1,000,000. Waste increases that to billable area.','Material cost per pouch = billable area × configured material rate per m². Printing adds only the configured multiplier above the 1.00× material basis.','Finishes/add-ons can be charged per pouch/piece or per m². They affect a quote only when selected.','MOQ blocks quantities below the minimum; the matching quantity-tier multiplier adjusts the variable subtotal.','Setup/pre-press and Flexo cylinder charges are job-level charges. Rush applies to the variable subtotal, not fixed setup/cylinder charges.','Final price per pouch/piece = complete job total ÷ quantity. Never invent a rate that is not configured.'],approvalRules:PACKAGING_APPROVAL,actions:['Check the live preview','Review template blockers','Open Packaging Templates']}),
  topicFromContext('packaging-templates',{id:'packaging-material-rate',slug:'packaging-material-rate',title:'How do I enter a material rate?',helpFile:PACKAGING_DOC,tags:['material rate','rate per m2','rate per m²','currency','material structure'],summary:'Material pricing on dimensional Packaging templates is entered in the template currency per square metre.',answer:['Choose the material/structure your team recognizes from Reference Library suggestions.','Enter the organization rate per m², not a per-pouch price. SETU Flow converts the selected pouch dimensions into area and then into material cost per pouch.','Thickness/basis is descriptive context such as 12/12/60; the monetary field is the material rate.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Reference Library','Check the live preview']}),
  topicFromContext('packaging-templates',{id:'packaging-addon-rate',slug:'packaging-addon-rate',title:'Should an add-on be per pouch or per m²?',helpFile:PACKAGING_DOC,tags:['finish','add-on','addon','zipper','matte','gloss','tear notch','per pouch','per m2'],summary:'Use the charge basis that matches the organization’s real rate card.',answer:['Use per pouch/piece when the organization charges a fixed amount for every pouch, such as a zipper priced per unit.','Use per m² only when the finish is genuinely priced by coated/processed material area.','Adding an available finish to the template does not automatically apply it to every quote; it must be selected in Live Preview or Quote Builder.'],approvalRules:PACKAGING_APPROVAL,actions:['Check the live preview','Open Packaging Templates']}),

  topicFromContext('packaging-families',{id:'packaging-families',slug:'packaging-families',title:'How do Packaging Service Families work?',helpFile:PACKAGING_DOC,tags:['service family','packaging family','pouch','stand up pouch','flat bottom','center seal','quote-time input','pcs'],summary:'A Service Family is the buyer/sales-facing packaging format. It organizes what is being quoted; the Pricing Template supplies the price rules.',answer:['Create families that sales and buyers recognize, such as Stand-Up Pouches, Flat Bottom Pouches, Center Seal Pouches, labels, sleeves, rollstock or service-based work.','Use quote-time inputs for specifications sales must capture, while pricing-driving dimensions/materials/add-ons remain controlled by the linked Pricing Template.','Use PCS when the quoted unit is an individual pouch/piece. Do not use a classic SKU/HSN workflow for Packaging Service Families.','A family becomes quote-ready only when it is active and linked to an appropriate active Pricing Template.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Packaging Families','Open Packaging Templates','Open Quote Builder']}),
  topicFromContext('packaging-reference-library',{id:'packaging-reference-library',slug:'packaging-reference-library',title:'How should I use the Packaging Reference Library?',helpFile:PACKAGING_DOC,tags:['reference library','materials','finishes','service items','standard names','pet','met pet','zipper'],summary:'Reference Library keeps organization naming consistent across Packaging Pricing Templates; it does not set the price itself.',answer:['Materials contains reusable material/structure names such as PET / MET PET / PE and optional thickness context.','Finishes contains reusable finish/add-on names such as Matte, Gloss, Zipper, Tear Notch, Valve or Hang Hole.','Service Items is for reusable service names used by service-based Packaging templates.','The price is still entered in the Pricing Template. Reference Library standardizes names so teams do not create duplicate spellings across templates.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Reference Library','Open Packaging Templates']}),

  topicFromContext('quotes',{id:'quotes',slug:'quotes',title:'Packaging Quote Builder help',helpFile:PACKAGING_DOC,tags:['quote builder','packaging quote','pouch price','moq','finish','material','template'],summary:'Quote Builder uses the selected Packaging Service Family and active Pricing Template to calculate the live packaging line price.',answer:['Choose the correct Service Family and Pricing Template, then enter the buyer specification: dimensions, material, colors, quantity and applicable build/finish options.','The calculation uses the same pricing engine as the Admin template preview. A matching preview and Quote Builder result is expected.','A finish/add-on changes price only when selected. MOQ and quantity-tier rules come from the template. Setup/pre-press, cylinder and rush rules are included according to their configured bases.','Quote-only adjustments must not silently rewrite the organization Pricing Template. After acceptance, the packaging line becomes execution work for Orders, Design and Dispatch.'],approvalRules:['Humans approve quote send, price deviation, compliance waivers and write-back.'],actions:['Open Quotes','Check Packaging quote readiness','Open Packaging Templates']}),
  topicFromContext('products',{id:'products',slug:'products',title:'Packaging Catalog help',helpFile:PACKAGING_DOC,tags:['catalog','packaging catalog','service family','classic product catalog','packaging family'],summary:'For a Packaging organization, Catalog presents buyer-facing Packaging Service Families rather than forcing every packaging configuration into a classic SKU.',answer:['Packaging Service Families organize what the buyer can request, such as pouch formats or packaging services.','Pricing comes from linked Packaging Pricing Templates, not from a separate fixed price on every catalog item.','Reference Library keeps shared material/finish/service names consistent. Classic Product Catalog remains for non-packaging SKU workflows and should not be mixed into the Packaging pricing path.'],approvalRules:['Humans approve catalog/default and Packaging template changes.'],actions:['Open Products','Open Packaging Families','Open Packaging Templates']}),

  topicFromContext('trade-events',{id:'trade-events',slug:'trade-events',title:'Packaging Trade Event capture help',helpFile:PACKAGING_DOC,tags:['event','trade event','capture','packaging inquiry','pouch','specifications'],summary:'At events, capture enough packaging intent to create a useful Follow-up record without pretending the booth conversation is a finished technical specification.',answer:['Capture company/contact, buyer/supplier role, product being packed, likely packaging format, approximate dimensions/fill, quantity or annual volume, artwork status, destination and timing when known.','Choose or suggest the likely Packaging Service Family, but let the sales/operator confirm the final technical family before quoting.','The contact should move into Follow-up with a clear next action to complete missing specifications before Quote Builder.'],approvalRules:['Humans confirm questionable captures, merges and conversion.'],actions:['Open Leads','Open Packaging Families']}),
  topicFromContext('growth-agent',{id:'growth-agent',slug:'growth-agent',title:'Packaging Growth Center help',helpFile:PACKAGING_DOC,tags:['growth center','packaging operations','quote readiness','pricing gap','proof','production','repeat order','cross sell'],summary:'Growth Center should prioritize Packaging opportunities and blockers using live organization evidence.',answer:['Packaging Operations can surface quote-readiness gaps, unhealthy Pricing Templates, artwork/proof blockers, production/dispatch delays and repeat-order opportunities.','A pricing gap should point back to the actual Service Family/Pricing Template configuration rather than inventing a market rate.','Repeat-order and cross-sell suggestions should use prior quote/order/dispatch timing and configured capabilities as evidence. Recommendations remain advisory until a human acts.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Growth Center','Open Packaging Templates','Open Design Queue','Open Dispatch Board']}),

  topicFromContext('packaging-design',{id:'packaging-design',slug:'packaging-design',title:'Packaging Design Queue help',helpFile:PACKAGING_DOC,tags:['design','artwork','proof','customer provided','design team','revision','prepress'],summary:'Design Queue controls whether an accepted Packaging line has final design evidence before production.',answer:['Customer-provided final artwork can satisfy design readiness unless it is rejected or incomplete.','When SETU/Design Team creates artwork, the latest proof must be explicitly approved before production release. A rejected proof requires a new version.','Pre-Press may prepare artwork, but Printing and later stages should not proceed without the required final design evidence.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Design Queue','Check proof status','Open Dispatch Board']}),
  topicFromContext('packaging-dispatch',{id:'packaging-dispatch',slug:'packaging-dispatch',title:'Packaging Production and Dispatch help',helpFile:PACKAGING_DOC,tags:['dispatch','pre press','printing','converting','finishing','qc','packed','production'],summary:'Dispatch Board manages the packaging production journey after the accepted quote and required design evidence are ready.',answer:['The expected production path is Pre-Press → Printing → Converting → Finishing → QC → Packed → Dispatched.','Before Printing, confirm the accepted quote line and final artwork/proof are ready.','Setu Guru may explain why a job is blocked or stalled, but it must not advance production, approve QC, pack or dispatch automatically.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Dispatch Board','Open Design Queue','Open Orders']}),

  topicFromContext('admin-organization',{id:'admin-organization',slug:'admin-organization',title:'Packaging Admin setup help',helpFile:PACKAGING_DOC,tags:['admin','packaging setup','owner','currency','roles','service family','reference library','pricing template'],summary:'For a Packaging organization, Admin establishes the governed configuration that Catalog and Quote Builder rely on.',answer:['Confirm organization profile, currency, users/roles and Packaging entitlement first.','Then maintain the Packaging Reference Library, create buyer-facing Service Families and create/activate Pricing Templates with the organization’s real pricing rules.','Test a known quote in the Pricing Template preview before relying on the template in Quote Builder. Owner/admin approval remains required for governed configuration changes.'],approvalRules:['Owners/admins approve roles, policy, defaults, pricing and template changes.'],actions:['Open Reference Library','Open Packaging Families','Open Packaging Templates']}),

  topicFromContext('packaging-proof',{id:'packaging-proof',slug:'packaging-proof',title:'Packaging proof approval help',helpFile:PACKAGING_DOC,tags:['proof','approve artwork','reject proof','version'],summary:'Proof Approval reviews one exact Design Team proof version.',answer:['Verify customer, quote line, file and version before deciding.','Approval makes that latest proof eligible for production release; rejection requires feedback and a new version.'],approvalRules:['The customer or authorized reviewer explicitly approves or rejects the displayed proof.'],actions:['Review proof','Return to Design Queue']}),
  topicFromContext('packaging-history',{id:'packaging-history',slug:'packaging-history',title:'Packaging history help',helpFile:PACKAGING_DOC,tags:['history','repeat order','proof versions','production events'],summary:'Packaging History explains what was quoted, approved, produced and dispatched.',answer:['Keep accepted quote history immutable.','Compare specifications, pricing, proof versions, production events and dispatch evidence by timestamp.','Use prior completed work as evidence when identifying repeat-order opportunities.'],approvalRules:PACKAGING_APPROVAL,actions:['Open quote','Open order','Review repeat-order opportunity']}),
  topicFromContext('packaging-academy',{id:'packaging-academy',slug:'packaging-academy',title:'Packaging Academy help',helpFile:'docs/packaging/SPRINT_50_PACKAGING_INTELLIGENCE.md',tags:['academy','training','packaging'],summary:'Packaging Academy is the click-by-click training path across the packaging workflow.',answer:['Follow the visible path instead of skipping directly to later routes.','Record expected and observed behavior for failures so the issue can be reproduced.'],approvalRules:['A human tester confirms production behavior.'],actions:['Open Packaging Academy']}),

  topicFromContext('leads',{id:'leads',slug:'leads',title:'Follow-up help',tags:['lead','buyer','packaging inquiry','qualification'],summary:'Use Follow-up to complete packaging qualification before quoting.',answer:['Confirm buyer/use case, Service Family, dimensions/specifications, quantity, artwork, destination and timing.','Do not treat a partially captured packaging inquiry as quote-ready until the required specification is complete.'],approvalRules:['Humans approve quote send, pricing deviations and write-back.'],actions:['Open Leads','Open Packaging Families','Open Quotes']}),
  topicFromContext('orders',{id:'orders',slug:'orders',title:'Orders help',tags:['order','packaging','artwork','dispatch'],summary:'Orders is the canonical execution record after quote acceptance.',answer:['Accepted Packaging lines coordinate with Design Queue and Dispatch Board while accepted quote history remains immutable.','Check design/proof readiness before production and execution blockers before dispatch.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Orders','Open Design Queue','Open Dispatch Board']}),
  topicFromContext('compliance',{id:'compliance',slug:'compliance',title:'Compliance and document help',tags:['compliance','packaging','material declaration','food contact'],summary:'Packaging compliance separates required evidence from pricing and production guidance.',answer:['Evidence may include material declarations, food-contact/migration, ink/adhesive, restricted substances, recycled-content/claims and other market-specific requirements.','Use current official sources for changing legal requirements; Setu Guru cannot approve or waive compliance.'],approvalRules:['Humans approve evidence, waivers and compliance decisions.'],actions:['Open compliance','Ask live research']}),
  topicFromContext('dashboard',{id:'dashboard',slug:'dashboard',title:'Dashboard help',tags:['dashboard','queue'],summary:'Use Dashboard to identify the Packaging workspace that owns the next blocker.',answer:['Route pricing gaps to Packaging Templates, quote gaps to Quotes, artwork/proof gaps to Design Queue and production/dispatch gaps to Dispatch Board.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Quotes','Open Packaging Templates','Open Design Queue','Open Dispatch Board']}),
  topicFromContext('pipeline',{id:'pipeline',slug:'pipeline',title:'Pipeline help',tags:['pipeline','packaging','quote ready'],summary:'Use Pipeline to track commercial momentum while packaging readiness is resolved in the owning workspace.',answer:['A deal should not be treated as quote-ready simply because its pipeline stage moved; required packaging specifications and pricing must still be complete.'],approvalRules:['Humans approve stage moves and quote sends.'],actions:['Open Leads','Open Quotes']}),
  topicFromContext('pricing-calculator',{id:'pricing-calculator',slug:'pricing-calculator',title:'Pricing calculator help',routeKeys:['pricing-calculator'],tags:['pricing calculator','margin','freight'],summary:'Generic pricing defaults are separate from Packaging Pricing Templates.',answer:['For Packaging vertical questions, use the Packaging Service Family and Pricing Template evidence first. Do not substitute generic product margin guidance for dimensional Packaging pricing.'],approvalRules:['Humans approve commercial pricing changes.'],actions:['Open Packaging Templates']}),
  topicFromContext('setu-guru',{id:'setu-guru',slug:'setu-guru',title:'Setu Guru response policy help',tags:['setu guru','help','packaging'],summary:'Setu Guru should answer Packaging questions from the active page, live organization data and canonical Packaging knowledge before generic guidance.',answer:['Never invent organization rates or policy.','Use Packaging Pricing Templates for current pricing rules, Service Families for buyer-facing structure, Reference Library for standardized names, and live workflow records for quote/design/dispatch status.'],approvalRules:PACKAGING_APPROVAL,actions:['Check blockers']}),
  topicFromContext('trial',{id:'trial',slug:'trial',title:'Guided Trial help',tags:['trial','packaging'],summary:'Use Guided Trial to validate the Packaging flow before conversion.',answer:['Validate family selection, pricing calculation, quote, accepted order, artwork/proof and dispatch behavior.'],approvalRules:PACKAGING_APPROVAL,actions:['Open Guided Trial']}),
];

function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
export function getHelpTopicById(id:string){return SETU_GURU_HELP_TOPICS.find((topic)=>topic.id===id||topic.slug===id)??null;}
export function getSetuGuruRouteTopics(pathname:string){
  const pageContext=getSetuGuruPageContext(pathname);
  const matches=SETU_GURU_HELP_TOPICS.filter((topic)=>topic.routeKeys.includes(pageContext.routeKey)||topic.routes.some((route)=>routeMatchesSetuGuruPath(pathname,route)));
  return matches.length?matches:SETU_GURU_HELP_TOPICS;
}
export const getHelpTopicsForPath=getSetuGuruRouteTopics;

export function getBestSetuGuruHelpTopic(question:string,pathname:string){
  const routeTopics=getSetuGuruRouteTopics(pathname); const q=normalize(question); if(!q)return routeTopics[0]??SETU_GURU_HELP_TOPICS[0];
  const ranked=routeTopics.map((topic)=>{const haystack=normalize([topic.title,topic.summary,...topic.tags,...topic.answer].join(' '));const wordScore=q.split(/\s+/).filter(Boolean).reduce((score,token)=>score+(haystack.includes(token)?1:0),0);return{topic,score:4+wordScore};}).sort((a,b)=>b.score-a.score);
  if(ranked[0]?.score>4)return ranked[0].topic;
  const global=SETU_GURU_HELP_TOPICS.map((topic)=>{const haystack=normalize([topic.title,topic.summary,...topic.tags,...topic.answer].join(' '));const wordScore=q.split(/\s+/).filter(Boolean).reduce((score,token)=>score+(haystack.includes(token)?1:0),0);return{topic,score:wordScore};}).sort((a,b)=>b.score-a.score);
  return global[0]?.score?global[0].topic:routeTopics[0]??SETU_GURU_HELP_TOPICS[0];
}
export const getBestHelpTopic=getBestSetuGuruHelpTopic;

export function getSetuGuruActionHref(action:string){
  const normalized=normalize(action);
  if(normalized.includes('reference library'))return '/admin/packaging-reference-library';
  if(normalized.includes('packaging operation')||normalized.includes('growth center'))return '/growth-agent';
  if(normalized.includes('design queue')||normalized.includes('artwork')||normalized.includes('proof status'))return '/design-queue';
  if(normalized.includes('dispatch board')||normalized.includes('production readiness'))return '/dispatch-board';
  if(normalized.includes('packaging template')||normalized.includes('template blocker')||normalized.includes('template health')||normalized.includes('live preview'))return '/admin/packaging-templates';
  if(normalized.includes('packaging famil'))return '/admin/packaging-families';
  if(normalized.includes('packaging academy'))return '/academy';
  if(normalized.includes('guided trial'))return '/trial';
  if(normalized.includes('compliance'))return '/compliance';
  if(normalized.includes('open products')||normalized.includes('catalog'))return '/products';
  if(normalized.includes('open leads'))return '/leads';
  if(normalized.includes('order'))return '/orders';
  if(normalized.includes('quote'))return '/quotes';
  if(normalized.includes('approval')||normalized.includes('release'))return '/approval-send';
  if(normalized.includes('organization'))return '/admin/organization#company-profile';
  return null;
}

export function getRouteHelpSummary(pathname:string){
  const context:SetuGuruPageContext=getSetuGuruPageContext(pathname);
  const topic=getHelpTopicById(context.helpTopicId)??getSetuGuruRouteTopics(pathname)[0];
  return {routeKey:context.routeKey,routeTitle:context.title,helpFile:topic.helpFile,summary:topic.summary,suggestedPrompts:context.suggestedPrompts,liveSearchModes:context.liveSearchModes,approvalRequiredActions:context.approvalRequiredActions};
}
