import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getCurrentWorkspace } from '@/lib/workspace/auth';

export const dynamic = 'force-dynamic';
const PROVIDERS = new Set(['zoom','custom','in_person','none']);
const RSVP = new Set(['needs_action','accepted','tentative','declined']);
async function context(){const workspace=await getCurrentWorkspace();if(!workspace.user)return{error:NextResponse.json({error:'Authentication required.'},{status:401})};if(!workspace.organization||!workspace.membership)return{error:NextResponse.json({error:'Active workspace required.'},{status:403})};const supabase=(await createClient()) as any;const{data:grant}=await supabase.from('org_module_grants').select('enabled').eq('organization_id',workspace.organization.id).eq('module_key','setu_mail').maybeSingle();if(!grant?.enabled)return{error:NextResponse.json({error:'Setu Communications is not enabled for this organization.'},{status:403})};return{workspace,supabase}}
function dates(body:any){const startsAt=new Date(body.startsAt),endsAt=new Date(body.endsAt);return{startsAt,endsAt,valid:!Number.isNaN(startsAt.valueOf())&&!Number.isNaN(endsAt.valueOf())&&endsAt>startsAt}}
async function conflict(db:any,organizationId:string,userId:string,start:string,end:string,excludeId?:string){let q=db.from('calendar_events').select('id,title,starts_at,ends_at').eq('organization_id',organizationId).eq('owner_user_id',userId).neq('status','cancelled').lt('starts_at',end).gt('ends_at',start).limit(1);if(excludeId)q=q.neq('id',excludeId);const{data}=await q;return data?.[0]??null}
async function syncChildren(db:any,organizationId:string,eventId:string,body:any){if(Array.isArray(body.attendees)){await db.from('calendar_attendees').delete().eq('event_id',eventId).eq('organization_id',organizationId);const rows=body.attendees.map((a:any)=>({organization_id:organizationId,event_id:eventId,email:String(a.email??a).trim().toLowerCase(),name:a.name||null,attendee_type:a.attendeeType==='optional'?'optional':'required',rsvp_status:RSVP.has(a.rsvpStatus)?a.rsvpStatus:'needs_action'})).filter((a:any)=>a.email.includes('@'));if(rows.length)await db.from('calendar_attendees').upsert(rows,{onConflict:'event_id,email'})}if(body.reminderMinutes!==undefined){const minutes=Number(body.reminderMinutes);if(Number.isFinite(minutes)&&minutes>=0&&minutes<=10080){await db.from('calendar_reminders').delete().eq('event_id',eventId).eq('organization_id',organizationId).eq('channel','in_app');await db.from('calendar_reminders').insert({organization_id:organizationId,event_id:eventId,channel:'in_app',minutes_before:minutes})}}}
export async function GET(req:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;const organizationId=ctx.workspace.organization!.id;const from=req.nextUrl.searchParams.get('from'),to=req.nextUrl.searchParams.get('to');let q=ctx.supabase.from('calendar_events').select('*,calendar_attendees(*),calendar_reminders(*),calendar_event_links(*)').eq('organization_id',organizationId).order('starts_at');if(from)q=q.gte('starts_at',from);if(to)q=q.lt('starts_at',to);const{data,error}=await q.limit(500);return error?NextResponse.json({error:'Unable to load calendar.'},{status:500}):NextResponse.json({events:data??[]})}
export async function POST(req:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;const body=await req.json();const title=String(body.title??'').trim(),d=dates(body);if(!title||!d.valid)return NextResponse.json({error:'Add a title and valid start/end time.'},{status:400});const organizationId=ctx.workspace.organization!.id,userId=ctx.workspace.user!.id;const hit=await conflict(ctx.supabase,organizationId,userId,d.startsAt.toISOString(),d.endsAt.toISOString());if(hit&&!body.allowConflict)return NextResponse.json({error:'This time overlaps another calendar event.',conflict:hit},{status:409});const provider=PROVIDERS.has(body.meetingProvider)?body.meetingProvider:'none';const{data:event,error}=await ctx.supabase.from('calendar_events').insert({organization_id:organizationId,owner_user_id:userId,created_by:userId,title,description:body.description||null,location:body.location||null,starts_at:d.startsAt.toISOString(),ends_at:d.endsAt.toISOString(),timezone:body.timezone||'UTC',is_all_day:Boolean(body.isAllDay),meeting_provider:provider,meeting_url:provider==='custom'?body.meetingUrl||null:null}).select('*').single();if(error||!event)return NextResponse.json({error:'Unable to create event.'},{status:500});await syncChildren(ctx.supabase,organizationId,event.id,body);return NextResponse.json({event},{status:201})}
export async function PATCH(req:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;const body=await req.json(),id=String(body.id||'');if(!id)return NextResponse.json({error:'Event id required.'},{status:400});const organizationId=ctx.workspace.organization!.id;const{data:existing}=await ctx.supabase.from('calendar_events').select('*').eq('id',id).eq('organization_id',organizationId).single();if(!existing)return NextResponse.json({error:'Event not found.'},{status:404});const start=new Date(body.startsAt??existing.starts_at),end=new Date(body.endsAt??existing.ends_at);if(Number.isNaN(start.valueOf())||Number.isNaN(end.valueOf())||end<=start)return NextResponse.json({error:'Add a valid start/end time.'},{status:400});const hit=await conflict(ctx.supabase,organizationId,existing.owner_user_id,start.toISOString(),end.toISOString(),id);if(hit&&!body.allowConflict)return NextResponse.json({error:'This time overlaps another calendar event.',conflict:hit},{status:409});const patch:any={updated_at:new Date().toISOString(),starts_at:start.toISOString(),ends_at:end.toISOString()};for(const[k,v]of Object.entries({title:body.title!==undefined?String(body.title).trim():undefined,description:body.description!==undefined?body.description||null:undefined,location:body.location!==undefined?body.location||null:undefined,timezone:body.timezone,is_all_day:body.isAllDay,status:body.status,meeting_provider:body.meetingProvider,meeting_url:body.meetingUrl!==undefined?body.meetingUrl||null:undefined})){if(v!==undefined)patch[k]=v}const{data,error}=await ctx.supabase.from('calendar_events').update(patch).eq('id',id).eq('organization_id',organizationId).select('*').single();if(error)return NextResponse.json({error:'Unable to update event.'},{status:500});await syncChildren(ctx.supabase,organizationId,id,body);return NextResponse.json({event:data})}
export async function DELETE(req:NextRequest){const ctx=await context();if('error'in ctx)return ctx.error;const id=req.nextUrl.searchParams.get('id');if(!id)return NextResponse.json({error:'Event id required.'},{status:400});const{error}=await ctx.supabase.from('calendar_events').delete().eq('id',id).eq('organization_id',ctx.workspace.organization!.id);return error?NextResponse.json({error:'Unable to delete event.'},{status:500}):NextResponse.json({ok:true})}
