'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { CheckCircle2, ChevronDown, ChevronRight, CircleAlert, Copy, Globe2, Mail, Plus, RefreshCw, ShieldCheck, Users, X } from 'lucide-react';

type Domain={id:string;domain:string;status:string;sending_status:string;receiving_status:string;dns_records:Array<Record<string,unknown>>;last_checked_at:string|null};
type Mailbox={id:string;user_id:string;address:string;display_name:string|null;status:string;inbound_enabled:boolean};
type Alias={id:string;mailbox_id:string;address:string;alias_type:string;is_active:boolean};
type Member={id:string;user_id:string;display_name:string|null;is_active:boolean};
type Entitlement={plan_key:string;status:string;mailbox_limit:number;domain_limit:number;storage_limit_bytes:number;monthly_message_limit:number;current_period_messages:number};
type Payload={organization:{name:string};domains:Domain[];mailboxes:Mailbox[];aliases:Alias[];members:Member[];entitlement:Entitlement|null;providerConfigured:boolean;webhookConfigured:boolean;senderConfigured:boolean;webhookPath:string};
const READY=new Set(['enabled','verified','active','ready']);
const isReady=(v:string|undefined|null)=>READY.has(String(v||'').toLowerCase());
const friendlyStatus=(v:string|undefined|null)=>{const n=String(v||'').toLowerCase();if(READY.has(n))return'Ready';if(['pending','pending_verification','not_started'].includes(n))return'Pending';if(['failed','error','invalid'].includes(n))return'Needs attention';return n?n.replaceAll('_',' '):'Not configured'};
const dnsValue=(r:Record<string,unknown>,k:string)=>r[k]==null?'':String(r[k]);

export function MailAdminWorkspace(){
 const[data,setData]=useState<Payload|null>(null);const[notice,setNotice]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const[mailboxOpen,setMailboxOpen]=useState(false);const[aliasOpen,setAliasOpen]=useState(false);const[domainOpen,setDomainOpen]=useState(false);const[dnsOpen,setDnsOpen]=useState<Record<string,boolean>>({});
 const[domain,setDomain]=useState('');const[userId,setUserId]=useState('');const[localPart,setLocalPart]=useState('');const[mailboxDomain,setMailboxDomain]=useState('');const[displayName,setDisplayName]=useState('');const[aliasMailbox,setAliasMailbox]=useState('');const[aliasLocalPart,setAliasLocalPart]=useState('');
 const readyDomains=useMemo(()=>data?.domains.filter(d=>isReady(d.sending_status)&&isReady(d.receiving_status))??[],[data?.domains]);
 const activeMailboxes=useMemo(()=>data?.mailboxes.filter(m=>m.status==='active')??[],[data?.mailboxes]);
 const memberRows=useMemo(()=>data?.members.map(member=>({member,mailboxes:data.mailboxes.filter(m=>m.user_id===member.user_id)}))??[],[data]);
 async function load(){const r=await fetch('/api/mail/admin',{cache:'no-store'});const p=await r.json() as Payload&{error?:string};if(!r.ok){setNotice(p.error||'Setu Mail could not be loaded.');return}setData(p);if(!userId&&p.members[0]?.user_id)setUserId(p.members[0].user_id);const rd=p.domains.find(d=>isReady(d.sending_status)&&isReady(d.receiving_status));if(!mailboxDomain&&rd)setMailboxDomain(rd.domain);const mb=p.mailboxes.find(m=>m.status==='active');if(!aliasMailbox&&mb)setAliasMailbox(mb.id)}
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function act(payload:Record<string,unknown>,success='Changes saved.'){setBusy(true);setNotice(null);try{const r=await fetch('/api/mail/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const x=await r.json() as{error?:string};if(!r.ok)throw new Error(x.error||'We could not complete that action.');setNotice(success);await load()}catch(e){setNotice(e instanceof Error?e.message:'We could not complete that action.')}finally{setBusy(false)}}
 const entitlement=data?.entitlement;const internalPlan=entitlement?.plan_key==='internal';const mailReady=Boolean(data?.providerConfigured&&data?.webhookConfigured);const mailboxAddress=localPart.trim()&&mailboxDomain?`${localPart.trim().toLowerCase()}@${mailboxDomain}`:'';const aliasDestination=data?.mailboxes.find(m=>m.id===aliasMailbox);const aliasDomain=aliasDestination?.address.split('@')[1]||'';const aliasAddress=aliasLocalPart.trim()&&aliasDomain?`${aliasLocalPart.trim().toLowerCase()}@${aliasDomain}`:'';
 return <div className="space-y-5">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-blue-700"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50"><Mail size={17}/></span>Setu Mail</div><h2 className="mt-3 text-2xl font-black text-slate-950">Mail administration</h2><p className="mt-1 text-sm text-slate-500">Manage who has email, where shared addresses route, and the health of your company mail service.</p></div><div className="flex gap-2"><button onClick={()=>setMailboxOpen(true)} className="h-10 rounded-xl bg-blue-600 px-4 text-sm font-black text-white"><Plus size={15} className="mr-1 inline"/>Add mailbox</button><Link href="/mail" className="flex h-10 items-center rounded-xl bg-slate-950 px-4 text-sm font-black text-white">Open Mail</Link></div></div></section>
  {notice?<div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900">{notice}</div>:null}
  <div className="grid gap-3 md:grid-cols-4"><Stat title="Mail service" value={mailReady?'Ready':'Setup needed'} icon={<ShieldCheck size={17}/>} tone={mailReady?'success':'warning'}/><Stat title="Team mailboxes" value={`${activeMailboxes.length} active`} icon={<Users size={17}/>}/><Stat title="Shared addresses" value={`${data?.aliases.filter(a=>a.is_active).length??0} active`} icon={<Mail size={17}/>}/><Stat title="Messages this month" value={new Intl.NumberFormat().format(entitlement?.current_period_messages??0)} icon={<CheckCircle2 size={17}/>}/></div>

  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="text-lg font-black text-slate-900">Users & mailboxes</h3><p className="mt-1 text-sm text-slate-500">Every active Setu Flow user is shown, including users who do not have email yet.</p></div><button onClick={()=>setMailboxOpen(true)} className="h-9 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-700">+ Add mailbox</button></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Team member</th><th className="px-4 py-3">Mailbox</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Incoming</th><th className="px-4 py-3">Shared addresses</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{memberRows.map(({member,mailboxes})=>{const mb=mailboxes[0];const aliases=mb?data?.aliases.filter(a=>a.mailbox_id===mb.id)??[]:[];return <tr key={member.user_id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="font-bold text-slate-900">{member.display_name||'Team member'}</div><div className="mt-0.5 text-xs text-slate-400">Active workspace user</div></td><td className="px-4 py-4">{mb?<><div className="font-semibold text-slate-700">{mb.address}</div>{mb.display_name?<div className="text-xs text-slate-400">Sender: {mb.display_name}</div>:null}</>:<span className="text-sm font-semibold text-amber-700">No mailbox</span>}</td><td className="px-4 py-4"><Status ok={mb?.status==='active'} text={mb?.status==='active'?'Active':mb?'Disabled':'Not configured'}/></td><td className="px-4 py-4"><Status ok={Boolean(mb?.inbound_enabled)} text={mb?.inbound_enabled?'Ready':mb?'Unavailable':'—'}/></td><td className="px-4 py-4 text-sm text-slate-600">{aliases.length?aliases.map(a=>a.address).join(', '):'—'}</td><td className="px-5 py-4 text-right">{mb?<button disabled={busy} onClick={()=>void act({action:'set_mailbox_status',id:mb.id,status:mb.status==='active'?'disabled':'active'},mb.status==='active'?'Mailbox disabled.':'Mailbox enabled.')} className="h-8 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-600">{mb.status==='active'?'Disable':'Enable'}</button>:<button onClick={()=>{setUserId(member.user_id);setDisplayName(member.display_name||'');setMailboxOpen(true)}} className="h-8 rounded-lg bg-blue-50 px-3 text-xs font-black text-blue-700">Create mailbox</button>}</td></tr>})}</tbody></table></div>
  </section>

  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="text-lg font-black text-slate-900">Shared addresses</h3><p className="mt-1 text-sm text-slate-500">See exactly where sales@, orders@ and other shared addresses are delivered.</p></div><button onClick={()=>setAliasOpen(true)} className="h-9 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-700">+ Add shared address</button></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Address</th><th className="px-4 py-3">Routes to mailbox</th><th className="px-4 py-3">Mailbox owner</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.aliases.length?data.aliases.map(a=>{const mb=data.mailboxes.find(m=>m.id===a.mailbox_id);const owner=data.members.find(m=>m.user_id===mb?.user_id);return <tr key={a.id}><td className="px-5 py-4 font-bold text-slate-900">{a.address}</td><td className="px-4 py-4 text-sm text-slate-600">{mb?.address||'—'}</td><td className="px-4 py-4 text-sm text-slate-600">{owner?.display_name||'—'}</td><td className="px-4 py-4"><Status ok={a.is_active} text={a.is_active?'Active':'Disabled'}/></td><td className="px-5 py-4 text-right"><button disabled={busy} onClick={()=>void act({action:'set_alias_status',id:a.id,isActive:!a.is_active},a.is_active?'Shared address disabled.':'Shared address enabled.')} className="h-8 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-600">{a.is_active?'Disable':'Enable'}</button></td></tr>}):<tr><td colSpan={5} className="px-5 py-8 text-center text-sm text-slate-500">No shared addresses configured.</td></tr>}</tbody></table></div></section>

  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between p-5"><div><h3 className="text-lg font-black text-slate-900">Domains & delivery health</h3><p className="mt-1 text-sm text-slate-500">DNS is kept out of the way when everything is healthy, but remains available for troubleshooting.</p></div><button onClick={()=>setDomainOpen(v=>!v)} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-700">{domainOpen?<ChevronDown size={14}/>:<ChevronRight size={14}/>} Manage domains</button></div>{domainOpen?<div className="border-t border-slate-200 p-5"><div className="mb-4 flex gap-2"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="yourcompany.com" className="h-10 flex-1 rounded-xl border border-slate-200 px-3 text-sm"/><button disabled={busy||!domain.trim()} onClick={()=>void act({action:'create_domain',domain},'Domain added. Complete DNS verification to activate email.')} className="rounded-xl bg-blue-600 px-4 text-sm font-black text-white disabled:opacity-50">Add domain</button></div><div className="space-y-3">{data?.domains.map(d=>{const ready=isReady(d.sending_status)&&isReady(d.receiving_status);return <div key={d.id} className="rounded-xl border border-slate-200"><div className="flex items-center justify-between p-4"><div><div className="flex items-center gap-2 font-black text-slate-900">{d.domain}<Status ok={ready} text={ready?'Ready':'Action needed'}/></div><div className="mt-1 text-xs text-slate-500">Sending: {friendlyStatus(d.sending_status)} · Receiving: {friendlyStatus(d.receiving_status)}</div></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void act({action:'refresh_domain',id:d.id},'Domain status refreshed.')} className="h-8 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-600"><RefreshCw size={13} className="mr-1 inline"/>Refresh</button><button onClick={()=>setDnsOpen(x=>({...x,[d.id]:!x[d.id]}))} className="h-8 rounded-lg border border-slate-200 px-3 text-xs font-black text-slate-600">DNS {dnsOpen[d.id]?'▲':'▼'}</button></div></div>{dnsOpen[d.id]&&d.dns_records?.length?<div className="border-t border-slate-200 bg-slate-50 p-3">{d.dns_records.map((r,i)=>{const type=dnsValue(r,'type')||dnsValue(r,'record')||'DNS';const host=dnsValue(r,'name')||dnsValue(r,'host')||'@';const value=dnsValue(r,'value')||dnsValue(r,'content');return <div key={i} className="grid grid-cols-[60px_180px_1fr_30px] gap-2 border-b border-slate-200 py-2 text-xs last:border-0"><b>{type}</b><code className="truncate">{host}</code><code className="truncate">{value}</code><button onClick={()=>navigator.clipboard?.writeText(value)}><Copy size={13}/></button></div>})}</div>:null}</div>})}</div></div>:null}</section>

  <div className="grid gap-3 md:grid-cols-3"><Readiness label="Outgoing mail" ready={Boolean(data?.providerConfigured)} text="Ready to send"/><Readiness label="Incoming mail" ready={Boolean(data?.webhookConfigured)} text="Ready to receive"/><Readiness label="Default sender" ready={Boolean(data?.senderConfigured)} text="Configured"/></div>

  {mailboxOpen?<Modal title="Create team mailbox" onClose={()=>setMailboxOpen(false)}><select value={userId} onChange={e=>setUserId(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="">Select team member</option>{data?.members.map(m=><option key={m.user_id} value={m.user_id}>{m.display_name||'Team member'}</option>)}</select><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Sender name" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><input value={localPart} onChange={e=>setLocalPart(e.target.value.replace(/@.*/,''))} placeholder="name" className="h-11 min-w-0 rounded-xl border border-slate-200 px-3 text-sm"/><span>@</span><select value={mailboxDomain} onChange={e=>setMailboxDomain(e.target.value)} className="h-11 min-w-0 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Choose domain</option>{readyDomains.map(d=><option key={d.id}>{d.domain}</option>)}</select></div><button disabled={busy||!userId||!mailboxAddress} onClick={()=>void act({action:'create_mailbox',userId,address:mailboxAddress,displayName},'Mailbox created for the selected team member.').then(()=>setMailboxOpen(false))} className="h-11 w-full rounded-xl bg-blue-600 text-sm font-black text-white disabled:opacity-50">Create mailbox</button></Modal>:null}
  {aliasOpen?<Modal title="Add shared address" onClose={()=>setAliasOpen(false)}><select value={aliasMailbox} onChange={e=>setAliasMailbox(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="">Destination mailbox</option>{activeMailboxes.map(m=><option key={m.id} value={m.id}>{m.address}</option>)}</select><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><input value={aliasLocalPart} onChange={e=>setAliasLocalPart(e.target.value.replace(/@.*/,''))} placeholder="sales" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><span>@</span><input readOnly value={aliasDomain} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"/></div><button disabled={busy||!aliasAddress||!aliasMailbox} onClick={()=>void act({action:'create_alias',mailboxId:aliasMailbox,address:aliasAddress,aliasType:'shared'},'Shared address added.').then(()=>setAliasOpen(false))} className="h-11 w-full rounded-xl bg-blue-600 text-sm font-black text-white disabled:opacity-50">Add shared address</button></Modal>:null}
 </div>
}
function Status({ok,text}:{ok:boolean;text:string}){return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${ok?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{text}</span>}
function Stat({title,value,icon,tone='default'}:{title:string;value:string;icon:ReactNode;tone?:'default'|'success'|'warning'}){return <div className={`rounded-2xl border p-4 shadow-sm ${tone==='success'?'border-emerald-100 bg-emerald-50/50':tone==='warning'?'border-amber-100 bg-amber-50/50':'border-slate-200 bg-white'}`}><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wide text-slate-400">{icon}{title}</div><div className="mt-3 text-xl font-black text-slate-900">{value}</div></div>}
function Readiness({label,ready,text}:{label:string;ready:boolean;text:string}){return <div className={`rounded-xl border p-3 ${ready?'border-emerald-100 bg-emerald-50':'border-amber-100 bg-amber-50'}`}><div className="flex items-center gap-2">{ready?<CheckCircle2 size={16} className="text-emerald-600"/>:<CircleAlert size={16} className="text-amber-600"/>}<span className="text-sm font-black text-slate-800">{label}</span></div><p className="mt-1 text-xs font-semibold text-slate-600">{ready?text:'Setup required'}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/25 p-4"><div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-black text-slate-900">{title}</h3><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></button></div><div className="space-y-3">{children}</div></div></div>}
