'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, CircleAlert, Copy, Mail, Plus, RefreshCw, ShieldCheck, Users } from 'lucide-react';

type Domain = { id:string; domain:string; status:string; sending_status:string; receiving_status:string; dns_records:any[]; last_checked_at:string|null };
type Mailbox = { id:string; user_id:string; address:string; display_name:string|null; status:string; inbound_enabled:boolean };
type Alias = { id:string; mailbox_id:string; address:string; alias_type:string; is_active:boolean };
type Member = { id:string; user_id:string; display_name:string|null; is_active:boolean };
type Entitlement = { plan_key:string; status:string; mailbox_limit:number; domain_limit:number; storage_limit_bytes:number; monthly_message_limit:number; current_period_messages:number };
type Payload = { organization:{name:string}; domains:Domain[]; mailboxes:Mailbox[]; aliases:Alias[]; members:Member[]; entitlement:Entitlement|null; providerConfigured:boolean; webhookConfigured:boolean; senderConfigured:boolean; webhookPath:string };

const READY = new Set(['enabled','verified','active','ready']);
function isReady(value:string|undefined|null){ return READY.has(String(value||'').toLowerCase()); }

export function MailAdminWorkspace(){
 const [data,setData]=useState<Payload|null>(null); const [notice,setNotice]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const [domain,setDomain]=useState(''); const [userId,setUserId]=useState(''); const [localPart,setLocalPart]=useState(''); const [mailboxDomain,setMailboxDomain]=useState(''); const [displayName,setDisplayName]=useState('');
 const [aliasMailbox,setAliasMailbox]=useState(''); const [aliasLocalPart,setAliasLocalPart]=useState('');
 const readyDomains=useMemo(()=>data?.domains.filter(d=>isReady(d.sending_status)&&isReady(d.receiving_status))??[],[data?.domains]);
 const activeMailboxes=useMemo(()=>data?.mailboxes.filter(m=>m.status==='active')??[],[data?.mailboxes]);
 async function load(){ const r=await fetch('/api/mail/admin',{cache:'no-store'}); const p=await r.json(); if(!r.ok){setNotice(p.error||'Unable to load Setu Mail admin.');return;} setData(p); if(!userId&&p.members?.[0]?.user_id)setUserId(p.members[0].user_id); const firstReady=p.domains?.find((d:Domain)=>isReady(d.sending_status)&&isReady(d.receiving_status)); if(!mailboxDomain&&firstReady?.domain)setMailboxDomain(firstReady.domain); const firstActive=p.mailboxes?.find((m:Mailbox)=>m.status==='active'); if(!aliasMailbox&&firstActive?.id)setAliasMailbox(firstActive.id); }
 useEffect(()=>{void load();},[]);
 async function act(payload:Record<string,unknown>,success='Saved.'){setBusy(true);setNotice(null);try{const r=await fetch('/api/mail/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)throw new Error(p.error||'Action failed.');setNotice(success);await load();}catch(e){setNotice(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false)}}
 const ent=data?.entitlement;
 const mailboxAddress=localPart.trim()&&mailboxDomain?`${localPart.trim().toLowerCase()}@${mailboxDomain}`:'';
 const aliasDestination=data?.mailboxes.find(m=>m.id===aliasMailbox);
 const aliasDomain=aliasDestination?.address.split('@')[1]||'';
 const aliasAddress=aliasLocalPart.trim()&&aliasDomain?`${aliasLocalPart.trim().toLowerCase()}@${aliasDomain}`:'';
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Setu Mail</p><h1 className="mt-1 text-3xl font-black text-slate-950">Business email administration</h1><p className="mt-2 text-sm text-slate-500">Domains, mailboxes, aliases and plan usage for {data?.organization?.name||'this workspace'}.</p></div><Link href="/mail" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Open Mail</Link></div>
  {notice?<div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900">{notice}</div>:null}
  <div className="grid gap-4 md:grid-cols-4">
   <Stat title="Plan" value={ent?.plan_key?.toUpperCase()||'—'} icon={<ShieldCheck size={18}/>}/><Stat title="Mailboxes" value={`${activeMailboxes.length} / ${ent?.mailbox_limit||0}`} icon={<Users size={18}/>}/><Stat title="Domains" value={`${data?.domains.length||0} / ${ent?.domain_limit||0}`} icon={<Mail size={18}/>}/><Stat title="Messages this month" value={`${ent?.current_period_messages||0} / ${ent?.monthly_message_limit||0}`} icon={<CheckCircle2 size={18}/>}/>
  </div>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
   <div><h2 className="text-lg font-black text-slate-900">Service readiness</h2><p className="mt-1 text-sm text-slate-500">These checks show whether Setu Mail can send, verify inbound Resend events, and fall back to a configured sender. Secret values are never displayed.</p></div>
   <div className="mt-4 grid gap-3 md:grid-cols-3"><Readiness label="Resend transport" ready={Boolean(data?.providerConfigured)} readyText="API key connected" missingText="RESEND_API_KEY missing"/><Readiness label="Inbound webhook" ready={Boolean(data?.webhookConfigured)} readyText="Signature verification ready" missingText="RESEND_WEBHOOK_SECRET missing"/><Readiness label="Fallback sender" ready={Boolean(data?.senderConfigured)} readyText="Sender configured" missingText="Setu Mail sender missing"/></div>
   <div className="mt-4 flex flex-col gap-2 rounded-xl bg-slate-50 p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="text-[11px] font-black uppercase tracking-wide text-slate-400">Resend inbound endpoint</div><div className="mt-1 truncate font-mono text-xs text-slate-700">{data?.webhookPath||'/api/mail/webhooks/resend'}</div></div><button type="button" onClick={()=>navigator.clipboard?.writeText(data?.webhookPath||'/api/mail/webhooks/resend')} className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-black text-slate-600"><Copy size={14}/>Copy path</button></div>
  </section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-slate-900">Company domain</h2><p className="text-sm text-slate-500">Register the domain with Resend and verify both sending and receiving before creating mailboxes.</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${data?.providerConfigured?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{data?.providerConfigured?'Resend connected':'Resend key missing'}</span></div>
   <div className="mt-4 flex gap-2"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="company.com" className="h-11 flex-1 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-400"/><button disabled={busy||!domain.trim()} onClick={()=>void act({action:'create_domain',domain},'Domain added. Add the DNS records, then refresh verification.')} className="rounded-xl bg-blue-600 px-4 text-sm font-black text-white disabled:opacity-50"><Plus size={16} className="mr-1 inline"/>Add domain</button></div>
   <div className="mt-4 space-y-3">{data?.domains.map(d=>{const ready=isReady(d.sending_status)&&isReady(d.receiving_status);return <div key={d.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><div className="font-black text-slate-900">{d.domain}</div><span className={`rounded-full px-2 py-0.5 text-[10px] font-black uppercase ${ready?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{ready?'Mail ready':'DNS pending'}</span></div><div className="mt-1 text-xs text-slate-500">Sending: {d.sending_status} · Receiving: {d.receiving_status}</div></div><button disabled={busy} onClick={()=>void act({action:'refresh_domain',id:d.id},'Domain status refreshed.')} className="rounded-lg border border-slate-200 p-2 text-slate-600"><RefreshCw size={16}/></button></div>{Array.isArray(d.dns_records)&&d.dns_records.length?<div className="mt-4 overflow-hidden rounded-xl bg-slate-50"><div className="grid grid-cols-[75px_1fr_34px] border-b border-slate-200 px-3 py-2 text-[10px] font-black uppercase text-slate-400"><span>Type</span><span>Value</span><span/></div>{d.dns_records.map((r:any,i:number)=><div key={i} className="grid grid-cols-[75px_1fr_34px] items-center gap-2 border-b border-slate-100 px-3 py-2 text-xs last:border-0"><span className="font-black text-slate-600">{r.type||r.record||'DNS'}</span><span className="truncate text-slate-600" title={String(r.value||r.name||'')}>{String(r.value||r.name||'')}</span><button onClick={()=>navigator.clipboard?.writeText(String(r.value||''))} className="text-slate-400"><Copy size={14}/></button></div>)}</div>:<div className="mt-3 flex items-center gap-2 text-xs text-amber-700"><CircleAlert size={14}/>DNS records will appear after provider registration.</div>}</div>})}</div>
  </section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-900">Create mailbox</h2><p className="text-sm text-slate-500">Assign a verified company email address to an active Setu Flow user.</p><div className="mt-4 space-y-3"><select value={userId} onChange={e=>setUserId(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="">Select user</option>{data?.members.map(m=><option key={m.user_id} value={m.user_id}>{m.display_name||m.user_id}</option>)}</select><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name" className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><input value={localPart} onChange={e=>setLocalPart(e.target.value.replace(/@.*/,''))} placeholder="name" className="h-11 min-w-0 rounded-xl border border-slate-200 px-3 text-sm"/><span className="text-slate-400">@</span><select value={mailboxDomain} onChange={e=>setMailboxDomain(e.target.value)} className="h-11 min-w-0 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Verified domain</option>{readyDomains.map(d=><option key={d.id} value={d.domain}>{d.domain}</option>)}</select></div>{readyDomains.length===0?<div className="rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800">Verify both sending and receiving on a company domain before creating mailboxes.</div>:null}<button disabled={busy||!userId||!mailboxAddress} onClick={()=>void act({action:'create_mailbox',userId,address:mailboxAddress,displayName},'Mailbox created.')} className="h-11 w-full rounded-xl bg-blue-600 text-sm font-black text-white disabled:opacity-50">Create mailbox</button></div><div className="mt-5 space-y-2">{data?.mailboxes.map(m=><div key={m.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="min-w-0 flex-1"><div className="font-bold text-slate-800">{m.display_name||'Mailbox'}</div><div className="truncate text-sm text-slate-500">{m.address}</div><div className="mt-1 text-[10px] font-black uppercase text-slate-400">{m.status} · {m.inbound_enabled?'Inbound enabled':'Inbound disabled'}</div></div><button disabled={busy} onClick={()=>void act({action:'set_mailbox_status',id:m.id,status:m.status==='active'?'disabled':'active'},m.status==='active'?'Mailbox disabled.':'Mailbox enabled.')} className={`rounded-lg border px-3 py-2 text-xs font-black ${m.status==='active'?'border-rose-200 text-rose-700':'border-emerald-200 text-emerald-700'}`}>{m.status==='active'?'Disable':'Enable'}</button></div>)}</div></div>
   <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-900">Aliases & shared addresses</h2><p className="text-sm text-slate-500">Create addresses like sales@, orders@ or accounts@ and route them to an active mailbox.</p><div className="mt-4 space-y-3"><select value={aliasMailbox} onChange={e=>setAliasMailbox(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="">Select destination mailbox</option>{activeMailboxes.map(m=><option key={m.id} value={m.id}>{m.address}</option>)}</select><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><input value={aliasLocalPart} onChange={e=>setAliasLocalPart(e.target.value.replace(/@.*/,''))} placeholder="sales" className="h-11 min-w-0 rounded-xl border border-slate-200 px-3 text-sm"/><span className="text-slate-400">@</span><input value={aliasDomain} readOnly placeholder="domain" className="h-11 min-w-0 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-500"/></div><button disabled={busy||!aliasMailbox||!aliasAddress} onClick={()=>void act({action:'create_alias',mailboxId:aliasMailbox,address:aliasAddress,aliasType:'shared'},'Shared address added.')} className="h-11 w-full rounded-xl border border-blue-200 bg-blue-50 text-sm font-black text-blue-700 disabled:opacity-50">Add shared address</button></div><div className="mt-5 space-y-2">{data?.aliases.map(a=><div key={a.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="min-w-0 flex-1"><div className="truncate font-bold text-slate-800">{a.address}</div><div className="text-xs uppercase text-slate-400">{a.alias_type} · {a.is_active?'active':'disabled'}</div></div><button disabled={busy} onClick={()=>void act({action:'set_alias_status',id:a.id,isActive:!a.is_active},a.is_active?'Shared address disabled.':'Shared address enabled.')} className={`rounded-lg border px-3 py-2 text-xs font-black ${a.is_active?'border-rose-200 text-rose-700':'border-emerald-200 text-emerald-700'}`}>{a.is_active?'Disable':'Enable'}</button></div>)}</div></div>
  </section>
 </div>
}

function Stat({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-slate-400">{icon}<span className="text-xs font-black uppercase tracking-wide">{title}</span></div><div className="mt-3 text-2xl font-black text-slate-900">{value}</div></div>}
function Readiness({label,ready,readyText,missingText}:{label:string;ready:boolean;readyText:string;missingText:string}){return <div className={`rounded-xl border p-3 ${ready?'border-emerald-100 bg-emerald-50':'border-amber-100 bg-amber-50'}`}><div className={`flex items-center gap-2 text-xs font-black uppercase tracking-wide ${ready?'text-emerald-700':'text-amber-700'}`}>{ready?<CheckCircle2 size={15}/>:<CircleAlert size={15}/>} {label}</div><div className={`mt-2 text-sm font-bold ${ready?'text-emerald-900':'text-amber-900'}`}>{ready?readyText:missingText}</div></div>}
