'use client';

import Image from 'next/image';
import {
  Activity, ArrowLeft, ArrowRight, BarChart3, BookOpenCheck, Boxes, BriefcaseBusiness,
  Building2, CalendarDays, Check, ChevronDown, CircleDollarSign, ClipboardCheck,
  ContactRound, FileCheck2, House, KeyRound, ListChecks, LockKeyhole,
  MessageCircleMore, PackageCheck, PanelLeft, Presentation, ScanLine, Search, Send,
  Settings, ShieldCheck, ShoppingBag, Store, Truck, UsersRound, WandSparkles, X, ZoomIn,
  type LucideIcon,
} from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { SiteShell } from '@/components/marketing/site-shell';

type Screenshot = { src: string; alt: string; focus?: string; portrait?: boolean };
type OverviewPage = {
  slug: string; short: string; title: string; eyebrow: string; description: string;
  outcomes: string[]; icon: LucideIcon; screenshots?: Screenshot[]; placeholder?: string;
  guru?: string; composition: 'hero' | 'journey' | 'workspaces' | 'single' | 'duo' | 'mobile' | 'security';
};

const pages: OverviewPage[] = [
  { slug:'welcome', short:'Welcome', eyebrow:'Setu Flow CRM', title:'One connected system for the work behind every trade relationship.', description:'See the real product from opportunity discovery and capture through commercial decisions, execution, and growth.', outcomes:['A shared operating view','Connected customer context','Built for importer and exporter teams'], icon:House, composition:'hero', screenshots:[{src:'/internal/product-overview/01-welcome-dashboard.png',alt:'Setu Flow welcome dashboard'}] },
  { slug:'business-journey', short:'Business Journey', eyebrow:'End-to-end workflow', title:'From inquiry to dispatch—one connected operating journey.', description:'Every stage has a clear purpose, owner, and next action. Teams move forward without losing the relationship context created earlier.', outcomes:['Capture the opportunity','Convert with confidence','Execute with visibility'], icon:Activity, composition:'journey', guru:'Setu Guru supports research, next actions, follow-up, quote readiness, and execution decisions throughout the journey.' },
  { slug:'connected-workspaces', short:'Connected Workspaces', eyebrow:'Product architecture', title:'Focused workspaces. One source of truth.', description:'Each team works in the right space for the task while buyer, supplier, product, quote, communication, and order context stays connected.', outcomes:['Less tool switching','Clear ownership','Shared business context'], icon:Boxes, composition:'workspaces', guru:'Setu Guru works across the platform as an intelligent guidance layer, not a disconnected destination.' },
  { slug:'discover-opportunities', short:'Discover Opportunities', eyebrow:'Growth Center', title:'Turn market signals into focused opportunities.', description:'Research markets, shape the ideal customer profile, organize targets, and move promising signals into the CRM.', outcomes:['Prioritize markets','Build stronger target lists','Move research into action'], icon:Search, composition:'single', screenshots:[{src:'/internal/product-overview/04-growth-center.png',alt:'Setu Flow Growth Center'}], guru:'Ask Setu Guru to frame an ICP, research a market, or prepare outreach.' },
  { slug:'capture', short:'Capture', eyebrow:'Fast lead capture', title:'Capture useful lead context while the conversation is fresh.', description:'Use desktop or mobile capture for trade-show conversations, introductions, scans, and direct entry without slowing the team down.', outcomes:['Fast structured entry','Trade-event context','A next step from day one'], icon:ScanLine, composition:'duo', screenshots:[{src:'/internal/product-overview/05-capture-lead.png',alt:'Desktop lead capture'},{src:'/internal/product-overview/05b-mobile-capture.png',alt:'Mobile lead capture',portrait:true}] },
  { slug:'relationship-workspace', short:'Relationship Workspace', eyebrow:'Buyer and supplier detail', title:'See the complete relationship—not another disconnected record.', description:'Contacts, activity, communications, documents, follow-ups, commercial context, and audit history stay together.', outcomes:['Shared relationship memory','Visible ownership','Complete activity context'], icon:Building2, composition:'duo', screenshots:[{src:'/internal/product-overview/06-buyer-lead-detail.png',alt:'Buyer lead detail'},{src:'/internal/product-overview/06b-supplier-lead-detail.png',alt:'Supplier lead detail'},{src:'/internal/product-overview/6c-audit-trail.png',alt:'Relationship audit trail'}], guru:'Setu Guru can summarize the relationship and recommend the next best action.' },
  { slug:'research-intelligence', short:'Research & Intelligence', eyebrow:'Decision support', title:'Prepare with context before the next conversation.', description:'Combine account knowledge, market research, product fit, tasks, pipeline signals, and trade-event context before acting.', outcomes:['Better prepared outreach','Consistent research','Actionable intelligence'], icon:BookOpenCheck, composition:'duo', screenshots:[{src:'/internal/product-overview/pipeline.png',alt:'Pipeline intelligence'},{src:'/internal/product-overview/trade-events.png',alt:'Trade events workspace'},{src:'/internal/product-overview/tasks.png',alt:'Tasks workspace'}], guru:'Setu Guru converts research and CRM context into concise questions and next actions.' },
  { slug:'communication-hub', short:'Communication Hub', eyebrow:'Conversations and follow-up', title:'Keep every communication connected to the relationship.', description:'Bring communication history, reminders, meetings, documents, and follow-up into the same working context.', outcomes:['Fewer dropped follow-ups','Shared communication history','Clear action ownership'], icon:MessageCircleMore, composition:'duo', screenshots:[{src:'/internal/product-overview/08b-lead-communication.png',alt:'Lead communication workspace'},{src:'/internal/product-overview/document-management.png',alt:'Document management'}], guru:'Setu Guru helps prepare relevant follow-up using the relationship history already in Setu Flow.' },
  { slug:'catalog-management', short:'Catalog Management', eyebrow:'Products and categories', title:'Keep product information ready for commercial use.', description:'Manage product records, categories, images, specifications, and buyer-ready information from a structured catalog.', outcomes:['Cleaner product truth','Faster quote preparation','Consistent product information'], icon:ShoppingBag, composition:'duo', screenshots:[{src:'/internal/product-overview/09-product-catalog.png',alt:'Product catalog'},{src:'/internal/product-overview/09b-product-detail.png',alt:'Product detail'}] },
  { slug:'price-lists-buyer-sharing', short:'Price Lists & Sharing', eyebrow:'Buyer-ready commerce', title:'Prepare and share commercial information professionally.', description:'Move from internal product and pricing context to a controlled buyer-facing price-list experience.', outcomes:['Market-specific views','Professional sharing','Controlled buyer access'], icon:CircleDollarSign, composition:'single', screenshots:[{src:'/internal/product-overview/10-price-list-share.png',alt:'Price list sharing workspace'}] },
  { slug:'digital-business-card', short:'Digital Business Card', eyebrow:'Mobile vCard', title:'A professional identity that travels with every introduction.', description:'Share contact details, company identity, catalog links, and useful business information through one mobile-first profile.', outcomes:['Fast contact sharing','Mobile-first presentation','One professional profile'], icon:ContactRound, composition:'mobile', screenshots:[{src:'/internal/product-overview/11-digital-vcard.png',alt:'Setu Flow digital business card',portrait:true}] },
  { slug:'commercial-workspace', short:'Commercial Workspace', eyebrow:'Quotes and approvals', title:'Build, review, approve, and send commercial proposals.', description:'Keep buyer, product, pricing, review, document, and sending context connected from draft to approved quote.', outcomes:['Faster quote creation','Clear review path','Continuity into orders'], icon:BriefcaseBusiness, composition:'duo', screenshots:[{src:'/internal/product-overview/12-quotes-workspace.png',alt:'Quotes workspace'},{src:'/internal/product-overview/12b-quote-builder.png',alt:'Quote builder'},{src:'/internal/product-overview/12c-mobile-quote.png',alt:'Mobile quote',portrait:true}], guru:'Setu Guru can review quote readiness and identify missing commercial inputs before sending.' },
  { slug:'supplier-workspace', short:'Supplier Workspace', eyebrow:'Supply-side readiness', title:'Manage supplier readiness alongside buyer demand.', description:'Track supplier capability, sourcing follow-up, documentation, comparisons, and commercial context in one workspace.', outcomes:['Structured supplier records','Clear sourcing follow-up','Better supplier comparison'], icon:Store, composition:'duo', screenshots:[{src:'/internal/product-overview/13-supplier-detail.png',alt:'Supplier detail'},{src:'/internal/product-overview/13b-supplier-comparison.png',alt:'Supplier comparison'}], guru:'Setu Guru can summarize supplier context and identify missing information.' },
  { slug:'orders-execution', short:'Orders / Execution', eyebrow:'Delivery workspace', title:'Carry accepted business into organized execution.', description:'Keep order details, documents, responsibilities, milestones, risks, and next actions visible through delivery.', outcomes:['Clear execution ownership','Visible milestones','Continuity from quote to order'], icon:Truck, composition:'duo', screenshots:[{src:'/internal/product-overview/14-orders-workspace.png',alt:'Orders workspace'},{src:'/internal/product-overview/14b-order-detail.png',alt:'Order detail'}] },
  { slug:'analytics-reports', short:'Analytics & Reports', eyebrow:'Performance intelligence', title:'See what is moving, what is stuck, and where attention is needed.', description:'Use live analytics for operational decisions and owner-ready reports for performance review and sharing.', outcomes:['Understand conversion','Spot pipeline movement','Turn activity into decisions'], icon:BarChart3, composition:'duo', screenshots:[{src:'/internal/product-overview/15-analytics.png',alt:'Analytics workspace'},{src:'/internal/product-overview/15b-reports.png',alt:'Reports workspace'}], guru:'Setu Guru can surface patterns and explain what the team should investigate next.' },
  { slug:'integrations-access-security', short:'Integrations, Access & Security', eyebrow:'Administration and governance', title:'Connect the workspace and control access responsibly.', description:'Manage supported integrations, users, roles, access, and administrative settings from controlled workspaces.', outcomes:['Role-aware access','Central administration','Clear operational controls'], icon:ShieldCheck, composition:'security', screenshots:[{src:'/internal/product-overview/16-integrations.png',alt:'Integrations workspace'},{src:'/internal/product-overview/16b-users-access.png',alt:'Users and access workspace'}] },
];

const journeyGroups = [
  { label:'CAPTURE', tone:'teal', items:[['Discover',Search],['Lead Capture',ScanLine],['Trade Shows',CalendarDays],['Mobile vCard',ContactRound],['Tasks',ClipboardCheck]] },
  { label:'CONVERT', tone:'indigo', items:[['Research',BookOpenCheck],['Setu Guru',WandSparkles],['Quote',BriefcaseBusiness],['Approvals',FileCheck2]] },
  { label:'EXECUTE', tone:'orange', items:[['Orders',PackageCheck],['Documents',PanelLeft],['Dispatch',Truck]] },
] as const;
const workspaces = [
  ['Home',House],['Capture',ScanLine],['Follow-up',ListChecks],['Quote',BriefcaseBusiness],['Approvals & Sending',Send],['Orders / Execution',Truck],['Pipeline / Risks',Activity],['Trade Events',CalendarDays],['Tasks',ClipboardCheck],['Catalog',Store],['Analytics',BarChart3],['Reports',Presentation],['Admin & Settings',Settings],['Setu Guru',WandSparkles],
] as const;

function OutcomePills({ outcomes, dark=false }: { outcomes:string[]; dark?:boolean }) {
  return <div className="flex flex-wrap gap-2">{outcomes.map(item=><span key={item} className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-bold ${dark?'bg-white/10 text-white':'border border-slate-200 bg-white text-slate-700'}`}><Check className="h-3.5 w-3.5 text-teal-500"/>{item}</span>)}</div>;
}
function ScreenshotFrame({ shot, onZoom, className='' }: { shot:Screenshot; onZoom:()=>void; className?:string }) {
  return <button type="button" onClick={onZoom} className={`group relative min-h-0 overflow-hidden rounded-[1.25rem] border border-slate-200 bg-white shadow-[0_22px_60px_rgba(15,23,42,.13)] ${className}`}>
    <div className="flex h-8 items-center gap-1.5 border-b border-slate-200 bg-slate-50 px-3"><i className="h-2 w-2 rounded-full bg-slate-300"/><i className="h-2 w-2 rounded-full bg-slate-300"/><i className="h-2 w-2 rounded-full bg-slate-300"/><span className="ml-auto inline-flex items-center gap-1 text-[10px] font-bold text-slate-500"><ZoomIn className="h-3 w-3"/> Zoom</span></div>
    <div className={`relative w-full bg-slate-100 ${shot.portrait?'aspect-[9/16]':'aspect-[16/9]'}`}><Image src={shot.src} alt={shot.alt} fill sizes="(max-width: 1024px) 100vw, 900px" className={`transition duration-500 group-hover:scale-[1.01] ${shot.portrait?'object-cover object-top':'object-contain object-top'}`}/></div>
  </button>;
}
function GuruStrip({ children }: { children:string }) { return <div className="flex items-center gap-3 rounded-xl border border-cyan-200 bg-gradient-to-r from-cyan-50 to-blue-50 px-4 py-3"><Image src="/setu-guru/guru-avatar-128.png" alt="Setu Guru" width={40} height={40} className="h-9 w-9 rounded-full"/><p className="text-sm leading-5 text-slate-700"><b className="mr-2 text-xs uppercase tracking-[.16em] text-teal-700">Setu Guru</b>{children}</p></div>; }

function JourneyVisual() {
  return <div className="rounded-[1.5rem] border border-slate-200 bg-white p-4 shadow-[0_24px_70px_rgba(15,23,42,.10)] sm:p-5">
    <div className="grid gap-3 xl:grid-cols-[1.35fr_.95fr_.7fr]">{journeyGroups.map((group)=>{
      const styles=group.tone==='teal'?'border-teal-200 bg-teal-50/70 text-teal-800':group.tone==='indigo'?'border-indigo-200 bg-indigo-50/70 text-indigo-700':'border-orange-200 bg-orange-50/70 text-orange-700';
      return <section key={group.label} className={`rounded-2xl border p-3 ${styles}`}><div className="mb-3 flex items-center justify-between"><h3 className="text-[11px] font-black tracking-[.28em]">{group.label}</h3><span className="text-[10px] font-bold opacity-60">{group.items.length} steps</span></div><div className={`grid gap-2 ${group.items.length>4?'grid-cols-2 sm:grid-cols-5':group.items.length>3?'grid-cols-2 sm:grid-cols-4':'grid-cols-3'}`}>{group.items.map(([label,Icon],i)=><div key={label} className="rounded-xl border border-white/80 bg-white p-3 shadow-sm"><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-50"><Icon className="h-4 w-4"/></span><span className="text-[9px] font-black opacity-50">{String(i+1).padStart(2,'0')}</span></div><p className="mt-4 text-xs font-extrabold leading-tight text-slate-900">{label}</p></div>)}</div></section>})}</div>
    <div className="mt-4 flex items-center gap-3 text-xs font-bold text-slate-700"><span className="h-px flex-1 border-t border-dashed border-slate-300"/>One connected flow. One source of truth.<span className="h-px flex-1 border-t border-dashed border-slate-300"/></div>
  </div>;
}
function WorkspacesVisual() { return <div className="rounded-[1.5rem] bg-[#071b3d] p-4 text-white shadow-[0_24px_70px_rgba(7,27,61,.22)] sm:p-5"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{workspaces.map(([label,Icon],i)=><div key={label} className={`rounded-xl border p-3 ${i===workspaces.length-1?'border-cyan-300 bg-cyan-300/10':'border-white/10 bg-white/[.06]'}`}><div className="flex items-center justify-between"><Icon className={`h-4 w-4 ${i===workspaces.length-1?'text-cyan-300':'text-white/70'}`}/><span className="text-[9px] font-black text-white/35">{String(i+1).padStart(2,'0')}</span></div><p className="mt-4 text-xs font-bold leading-tight">{label}</p></div>)}</div></div>; }

function Visual({ page, onZoom }:{page:OverviewPage;onZoom:(s:Screenshot)=>void}) {
  if(page.composition==='journey') return <JourneyVisual/>;
  if(page.composition==='workspaces') return <WorkspacesVisual/>;
  const shots=page.screenshots||[];
  if(!shots.length) return <div className="flex min-h-[360px] items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 text-center"><div><PanelLeft className="mx-auto h-8 w-8 text-teal-600"/><p className="mt-3 text-xs font-black uppercase tracking-[.18em] text-teal-700">Product screenshot coming soon</p><p className="mt-2 font-bold text-slate-800">{page.placeholder}</p></div></div>;
  if(page.composition==='hero') return <div className="rounded-[1.5rem] bg-[#071b3d] p-4 sm:p-5"><ScreenshotFrame shot={shots[0]} onZoom={()=>onZoom(shots[0])}/></div>;
  if(page.composition==='mobile') return <div className="grid min-h-[520px] items-center gap-6 rounded-[1.5rem] bg-gradient-to-br from-[#071b3d] to-[#0b4762] p-6 text-white lg:grid-cols-[1fr_340px]"><div><ContactRound className="h-10 w-10 text-cyan-300"/><h3 className="mt-5 max-w-xl text-3xl font-black tracking-[-.04em]">One tap. One scan. One professional profile.</h3><div className="mt-6"><OutcomePills outcomes={page.outcomes} dark/></div></div><ScreenshotFrame shot={shots[0]} onZoom={()=>onZoom(shots[0])} className="mx-auto w-full max-w-[320px]"/></div>;
  if(page.composition==='single') return <ScreenshotFrame shot={shots[0]} onZoom={()=>onZoom(shots[0])} className="w-full"/>;
  if(page.composition==='security') return <div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><div className="rounded-[1.5rem] bg-[#071b3d] p-6 text-white"><LockKeyhole className="h-8 w-8 text-cyan-300"/><h3 className="mt-6 text-2xl font-black">Access that follows the way teams work.</h3><div className="mt-6 space-y-2">{[['Users and roles',UsersRound],['Workspace access',KeyRound],['Administrative controls',Settings],['Operational boundaries',ShieldCheck]].map(([label,Icon])=>{const I=Icon as LucideIcon;return <div key={label as string} className="flex items-center gap-3 rounded-xl bg-white/[.07] p-3 text-sm font-semibold"><I className="h-4 w-4 text-cyan-300"/>{label as string}</div>})}</div></div><div className="grid gap-3 sm:grid-cols-2">{shots.map(s=><ScreenshotFrame key={s.src} shot={s} onZoom={()=>onZoom(s)}/>)}</div></div>;
  const portrait=shots.find(s=>s.portrait); const desktop=shots.filter(s=>!s.portrait);
  return <div className={`grid gap-3 ${portrait?'lg:grid-cols-[1fr_260px]':'sm:grid-cols-2'}`}><div className={`grid gap-3 ${desktop.length>1?'':'contents'}`}>{desktop.map((s,i)=><ScreenshotFrame key={s.src} shot={s} onZoom={()=>onZoom(s)} className={desktop.length===3&&i===0?'sm:col-span-2':''}/>)}</div>{portrait&&<ScreenshotFrame shot={portrait} onZoom={()=>onZoom(portrait)} className="mx-auto w-full max-w-[280px]"/>}</div>;
}

export function ProductOverviewExperience(){
  const [activeSlug,setActiveSlug]=useState('welcome'); const [zoomed,setZoomed]=useState<Screenshot|null>(null); const [menu,setMenu]=useState(false);
  useEffect(()=>{const read=()=>{const slug=new URLSearchParams(location.search).get('page');if(slug&&pages.some(p=>p.slug===slug))setActiveSlug(slug)};read();addEventListener('popstate',read);return()=>removeEventListener('popstate',read)},[]);
  useEffect(()=>{if(!zoomed)return;const close=(e:KeyboardEvent)=>e.key==='Escape'&&setZoomed(null);addEventListener('keydown',close);return()=>removeEventListener('keydown',close)},[zoomed]);
  const index=Math.max(0,pages.findIndex(p=>p.slug===activeSlug)); const page=pages[index]; const previous=pages[(index-1+pages.length)%pages.length]; const next=pages[(index+1)%pages.length]; const progress=useMemo(()=>((index+1)/pages.length)*100,[index]);
  const select=(slug:string)=>{setActiveSlug(slug);setMenu(false);const url=new URL(location.href);url.searchParams.set('page',slug);history.pushState({},'',url);requestAnimationFrame(()=>document.getElementById('overview-top')?.scrollIntoView({behavior:'smooth',block:'start'}))};
  return <SiteShell><main className="min-h-screen bg-[#f2f5f8] text-slate-950"><div id="overview-top" className="mx-auto max-w-[1500px] px-3 py-3 sm:px-5 lg:px-7 lg:py-5">
    <div className="mb-3 lg:hidden"><button onClick={()=>setMenu(!menu)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-left shadow-sm"><span><small className="block text-[10px] font-black uppercase tracking-[.18em] text-teal-700">{String(index+1).padStart(2,'0')} of 16</small><b className="text-sm">{page.short}</b></span><ChevronDown className={`h-4 w-4 transition ${menu?'rotate-180':''}`}/></button>{menu&&<div className="mt-2 max-h-[55vh] overflow-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl">{pages.map((p,i)=><button key={p.slug} onClick={()=>select(p.slug)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm ${p.slug===page.slug?'bg-[#071b3d] text-white':'hover:bg-slate-50'}`}><span className="text-[10px] font-black opacity-60">{String(i+1).padStart(2,'0')}</span>{p.short}</button>)}</div>}</div>
    <div className="grid gap-4 lg:grid-cols-[230px_minmax(0,1fr)] xl:grid-cols-[250px_minmax(0,1fr)]">
      <aside className="hidden lg:block"><div className="sticky top-20 rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_18px_50px_rgba(15,23,42,.08)]"><div className="px-3 pb-2 pt-2 text-[10px] font-black uppercase tracking-[.2em] text-slate-400">16 guided pages</div>{pages.map((p,i)=><button key={p.slug} onClick={()=>select(p.slug)} className={`flex w-full items-center gap-2.5 rounded-xl px-2.5 py-2 text-left transition ${p.slug===page.slug?'bg-[#071b3d] text-white shadow-lg':'text-slate-600 hover:bg-slate-50 hover:text-slate-950'}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg ${p.slug===page.slug?'bg-cyan-300/10 text-cyan-300':'bg-slate-100 text-slate-500'}`}><p.icon className="h-3.5 w-3.5"/></span><span className="min-w-0"><small className="block text-[9px] font-black opacity-45">{String(i+1).padStart(2,'0')}</small><b className="block truncate text-[11px] leading-tight">{p.short}</b></span></button>)}</div></aside>
      <section className="min-w-0"><article className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(15,23,42,.08)]"><header className="relative overflow-hidden border-b border-slate-100 px-5 py-5 sm:px-7 lg:px-8"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-teal-100/60 blur-3xl"/><div className="relative"><div className="flex items-center gap-3"><span className="rounded-full bg-[#071b3d] px-2.5 py-1 text-[10px] font-black text-white">{String(index+1).padStart(2,'0')}</span><p className="text-[10px] font-black uppercase tracking-[.22em] text-teal-700">{page.eyebrow}</p></div><h1 className="mt-3 max-w-5xl text-[clamp(1.8rem,3.5vw,3.35rem)] font-black leading-[.98] tracking-[-.055em] text-[#071b3d]">{page.title}</h1><div className="mt-3 flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><p className="max-w-3xl text-sm leading-6 text-slate-600 sm:text-base">{page.description}</p><OutcomePills outcomes={page.outcomes}/></div></div></header>
        <div className="p-3 sm:p-4 lg:p-5"><Visual page={page} onZoom={setZoomed}/>{page.guru&&<div className="mt-3"><GuruStrip>{page.guru}</GuruStrip></div>}</div>
      </article>
      <nav className="mt-3 grid grid-cols-2 gap-3"><button onClick={()=>select(previous.slug)} className="flex min-h-14 items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 text-left shadow-sm transition hover:-translate-y-0.5"><ArrowLeft className="h-4 w-4 text-teal-700"/><span><small className="block text-[9px] font-black uppercase tracking-[.16em] text-slate-400">Previous</small><b className="text-xs sm:text-sm">{previous.short}</b></span></button><button onClick={()=>select(next.slug)} className="flex min-h-14 items-center justify-end gap-3 rounded-xl bg-[#071b3d] px-4 text-right text-white shadow-lg transition hover:-translate-y-0.5"><span><small className="block text-[9px] font-black uppercase tracking-[.16em] text-cyan-300">Next</small><b className="text-xs sm:text-sm">{next.short}</b></span><ArrowRight className="h-4 w-4 text-cyan-300"/></button></nav>
      <div className="mt-3 h-1 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-gradient-to-r from-teal-500 to-cyan-400 transition-all" style={{width:`${progress}%`}}/></div>
      </section>
    </div>
  </div>{zoomed&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/90 p-3 sm:p-6" onClick={()=>setZoomed(null)}><button className="absolute right-4 top-4 rounded-full bg-white p-2 text-slate-900"><X className="h-5 w-5"/></button><div className="relative h-[90vh] w-[95vw]" onClick={e=>e.stopPropagation()}><Image src={zoomed.src} alt={zoomed.alt} fill sizes="95vw" className="object-contain"/></div></div>}</main></SiteShell>;
}
