import type { MarketingLang } from './language-selector';

type TranslationMap = Partial<Record<MarketingLang, string>>;

export const supplementalTranslations: Record<string, TranslationMap> = {
  'You': { de: 'Sie', fr: 'Vous', es: 'Usted', zh: '您', hi: 'आप', ar: 'أنت' },
  'Prioritize event leads that need follow-up today.': { de: 'Event-Leads priorisieren, die heute Follow-up brauchen.', fr: 'Prioriser les leads à relancer aujourd’hui.', es: 'Priorizar leads que necesitan seguimiento hoy.', zh: '优先处理今天需要跟进的活动线索。', hi: 'आज फॉलो-अप वाली इवेंट लीड्स को प्राथमिकता दें।', ar: 'رتب أولوية العملاء الذين يحتاجون متابعة اليوم.' },
  'Found 4 contacts from Gulfood — 2 overdue. Opening the follow-up queue...': { de: '4 Kontakte von Gulfood gefunden — 2 überfällig. Follow-up-Queue wird geöffnet...', fr: '4 contacts trouvés depuis Gulfood — 2 en retard. Ouverture de la file...', es: '4 contactos de Gulfood — 2 vencidos. Abriendo la cola...', zh: '找到 4 个来自 Gulfood 的联系人，2 个已逾期。正在打开队列...', hi: 'Gulfood से 4 संपर्क मिले — 2 ओवरड्यू। फॉलो-अप क्यू खुल रही है...', ar: 'تم العثور على 4 جهات من Gulfood — 2 متأخرة. يتم فتح قائمة المتابعة...' },
  "What is blocking this order's dispatch readiness?": { de: 'Was hält diesen Auftrag vom Versand ab?', fr: 'Qu’est-ce qui bloque cette expédition ?', es: '¿Qué bloquea este despacho?', zh: '是什么阻碍了此订单发运？', hi: 'इस ऑर्डर के डिस्पैच में क्या रुकावट है?', ar: 'ما الذي يعيق شحن هذا الطلب؟' },
  'Certificate of Origin and Packing List not uploaded. Flagged for operations.': { de: 'Ursprungszeugnis und Packliste fehlen. Für Operations markiert.', fr: 'Certificat d’origine et liste de colisage manquants. Signalé aux opérations.', es: 'Faltan certificado de origen y lista de empaque. Marcado para operaciones.', zh: '原产地证书和装箱单未上传，已标记给运营。', hi: 'Certificate of Origin और Packing List अपलोड नहीं हैं। ऑपरेशंस को फ्लैग किया गया।', ar: 'شهادة المنشأ وقائمة التعبئة غير مرفوعتين. تم تنبيه العمليات.' },
  'Draft a quote follow-up for Kenya Family Grocers.': { de: 'Angebots-Follow-up für Kenya Family Grocers entwerfen.', fr: 'Rédiger un suivi de devis pour Kenya Family Grocers.', es: 'Redactar seguimiento de cotización para Kenya Family Grocers.', zh: '为 Kenya Family Grocers 起草报价跟进。', hi: 'Kenya Family Grocers के लिए कोट फॉलो-अप ड्राफ्ट करें।', ar: 'اكتب متابعة عرض لـ Kenya Family Grocers.' },
  'Draft ready — referencing Q-0294 (AUD 3,650). Awaiting your review before sending.': { de: 'Entwurf bereit — Q-0294 (AUD 3.650). Wartet auf Prüfung.', fr: 'Brouillon prêt — Q-0294 (AUD 3 650). En attente de validation.', es: 'Borrador listo — Q-0294 (AUD 3.650). Esperando revisión.', zh: '草稿已准备好——Q-0294（AUD 3,650）。等待审核。', hi: 'ड्राफ्ट तैयार — Q-0294 (AUD 3,650)। समीक्षा का इंतज़ार।', ar: 'المسودة جاهزة — Q-0294 (AUD 3,650). بانتظار المراجعة.' },
  'Guru works where the work is — in leads, quotes, documents and dispatch — not in a separate chat window disconnected from your data.': { de: 'Guru arbeitet dort, wo die Arbeit ist — in Leads, Angeboten, Dokumenten und Versand.', fr: 'Guru travaille dans les leads, devis, documents et expéditions.', es: 'Guru trabaja en leads, cotizaciones, documentos y despacho.', zh: 'Guru 在线索、报价、文件和发运中工作，而不是独立聊天窗口。', hi: 'Guru वहीं काम करता है जहाँ काम है — लीड, कोट, दस्तावेज़ और डिस्पैच में।', ar: 'يعمل Guru داخل العملاء والعروض والمستندات والشحن.' },
  'How Guru works': { de: 'Wie Guru funktioniert', fr: 'Comment fonctionne Guru', es: 'Cómo funciona Guru', zh: 'Guru 如何工作', hi: 'Guru कैसे काम करता है', ar: 'كيف يعمل Guru' },
  'Guru reads': { de: 'Guru liest', fr: 'Guru lit', es: 'Guru lee', zh: 'Guru 读取', hi: 'Guru पढ़ता है', ar: 'Guru يقرأ' },
  'Guru suggests': { de: 'Guru schlägt vor', fr: 'Guru suggère', es: 'Guru sugiere', zh: 'Guru 建议', hi: 'Guru सुझाव देता है', ar: 'Guru يقترح' },
  'You review': { de: 'Sie prüfen', fr: 'Vous validez', es: 'Usted revisa', zh: '您审核', hi: 'आप समीक्षा करते हैं', ar: 'أنت تراجع' },
  'Nothing leaves without approval': { de: 'Nichts geht ohne Freigabe raus', fr: 'Rien ne part sans approbation', es: 'Nada sale sin aprobación', zh: '未经批准不会发送任何内容', hi: 'अनुमोदन के बिना कुछ नहीं जाता', ar: 'لا يخرج شيء دون موافقة' }
};
