import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getCurrentWorkspace } from '@/lib/workspace/auth';
export const dynamic = 'force-dynamic';
type Intent={key:string;label:string;confidence:'high'|'medium';suggestedAction:string;evidence:string;actionLabel:string|null;actionHref:string|null};
type IntentRule={key:string;label:string;confidence:'high'|'medium';suggestedAction:string;pattern:RegExp};
const INTENT_RULES:IntentRule[]=[
 {key:'meeting',label:'Meeting request',confidence:'high',suggestedAction:'Review the conversation and schedule a meeting.',pattern:/\b(meet|meeting|schedule a call|book a call|available (?:on|for)|calendar invite|zoom)\b/i},
 {key:'rfq',label:'RFQ / pricing request',confidence:'high',suggestedAction:'Review the request and start the commercial workflow.',pattern:/\b(rfq|request for quote|quotation|please quote|price for|pricing for)\b/i},
 {key:'purchase_order',label:'Purchase order',confidence:'high',suggestedAction:'Review the PO against the related commercial record before changing execution state.',pattern:/\b(purchase order|po\b|attached po|po number|order confirmation)\b/i},
 {key:'follow_up',label:'Follow-up signal',confidence:'medium',suggestedAction:'Review the conversation and confirm the next follow-up.',pattern:/\b(follow up|following up|checking in|any update|status update|haven't heard|have not heard)\b/i},
 {key:'execution_risk',label:'Execution risk',confidence:'high',suggestedAction:'Review the lead/order context and execution timeline before committing.',pattern:/\b(delay|delayed|late|postpone|cannot meet|can't meet|shortage|issue with production)\b/i},
 {key:'sample_request',label:'Sample request',confidence:'medium',suggestedAction:'Review the lead and capture the sample requirement as the next action.',pattern:/\b(sample|samples|send sample|sample order)\b/i},
];
function compactEvidence(subject:string,text:string,pattern:RegExp){const source=`${subject?`Subject: ${subject}. `:''}${text}`.replace(/\s+/g,' ').trim();if(!source)return'';const match=pattern.exec(source);if(!match||match.index===undefined)return source.slice(0,140);const start=Math.max(0,match.index-55),end=Math.min(source.length,match.index+match[0].length+75);return `${start>0?'…':''}${source.slice(start,end).trim()}${end<source.length?'…':''}`.slice(0,180)}
function actionForIntent(key:string,leadId:string|null,peer=''){if(key==='meeting')return{actionLabel:'Schedule meeting',actionHref:`/calendar?compose=1${peer?`&guest=${encodeURIComponent(peer)}`:''}${leadId?`&lead=${leadId}`:''}`};if(!leadId)return{actionLabel:null,actionHref:null};if(key==='rfq')return{actionLabel:'Start RFQ',actionHref:`/leads/${leadId}/rfq/new`};if(key==='quote_acceptance')return{actionLabel:'Review quote',actionHref:`/leads/${leadId}/quote`};if(key==='follow_up')return{actionLabel:'Open follow-up',actionHref:`/leads/${leadId}`};if(key==='execution_risk')return{actionLabel:'Review execution context',actionHref:`/leads/${leadId}`};return{actionLabel:'Open lead',actionHref:`/leads/${leadId}`}}
function detectIntent(subject:string,text:string,leadId:string|null,peer:string):Intent[]{const value=`${subject}\n${text}`,results:Intent[]=[];const quote=/\b(approved|accept(?:ed)?|proceed|go ahead|confirmed)\b/i.test(value)&&/\b(quote|quotation|proposal|price)\b/i.test(value);if(quote){const pattern=/\b(approved|accept(?:ed)?|proceed|go ahead|confirmed|quote|quotation|proposal|price)\b/i;results.push({key:'quote_acceptance',label:'Quote acceptance',confidence:'high',suggestedAction:'Review the approved commercial terms before converting anything to an order.',evidence:compactEvidence(subject,text,pattern),...actionForIntent('quote_acceptance',leadId,peer)})}for(const rule of INTENT_RULES)if(rule.pattern.test(value)&&!results.some(x=>x.key===rule.key))results.push({key:rule.key,label:rule.label,confidence:rule.confidence,suggestedAction:rule.suggestedAction,evidence:compactEvidence(subject,text,rule.pattern),...actionForIntent(rule.key,leadId,peer)});return results.slice(0,4)}
export async function GET(_:Request,{params}:{params:{id:string}}){const w=await getCurrentWorkspace();if(!w.user)return NextResponse.json({error:'Authentication required.'},{status:401});if(!w.organization||!w.membership)return NextResponse.json({error:'Active workspace required.'},{status:403});const db=(await createClient()) as any;const org=w.organization.id;const[{data:grant},{data:mailbox}]=await Promise.all([db.from('org_module_grants').select('enabled').eq('organization_id',org).eq('module_key','setu_mail').maybeSingle(),db.from('mail_mailboxes').select('id,address').eq('organization_id',org).eq('user_id',w.user.id).eq('status','active').limit(1).maybeSingle()]);if(!grant?.enabled)return NextResponse.json({error:'Setu Communications is not enabled for this organization.'},{status:403});if(!mailbox)return NextResponse.json({error:'Mailbox not found.'},{status:404});const{data:m}=await db.from('mail_messages').select('id,direction,from_address,to_addresses,subject,text_body,thread_id').eq('id',params.id).eq('mailbox_id',mailbox.id).maybeSingle();if(!m)return NextResponse.json({error:'Message not found.'},{status:404});const peer=String(m.direction==='inbound'?m.from_address:m.to_addresses?.[0]??'').trim().toLowerCase();let crmMatch:any=null;if(peer){const{data:lead}=await db.from('leads').select('id,lead_type,company_name,contact_name,email,stage_id,owner_user_id').eq('organization_id',org).ilike('email',peer).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(lead)crmMatch={type:'lead',...lead,href:`/leads/${lead.id}`}}const createCrmHref=peer?`/leads?quickLead=1&leadType=buyer&sourceType=setu_mail&sourceLabel=${encodeURIComponent(`Setu Mail · ${peer}`)}`:'/leads?quickLead=1&sourceType=setu_mail&sourceLabel=Setu%20Mail';return NextResponse.json({messageId:m.id,mailThreadId:m.thread_id,peerAddress:peer,crmMatch,createCrmHref:crmMatch?null:createCrmHref,intents:detectIntent(String(m.subject??''),String(m.text_body??''),crmMatch?.id??null,peer),autonomousActions:false})}
