import type { FollowUpVisualState as LeadFollowUpVisualState } from '@/lib/lead-status';
import type { StageMoveReadiness } from '@/lib/queries/pipeline-stage-gating';
import type { TodayLayerState, WorkspaceMode } from '@/features/workspace/types';
import type { LeadJourney } from '@/lib/journey';

export type Stage = { id: string; name: string; sort_order: number; pipeline_id: string; is_closed: boolean; is_won: boolean; is_lost: boolean };
export type Lead = {
  id: string;
  company_name: string;
  contact_name: string | null;
  job_title: string | null;
  email: string | null;
  phone: string | null;
  phone_secondary: string | null;
  website: string | null;
  social_handle: string | null;
  lead_type: 'buyer' | 'supplier';
  country: string | null;
  country_id: string | null;
  source_type: string | null;
  source_label: string | null;
  next_follow_up_at: string | null;
  created_at: string | null;
  updated_at: string | null;
  last_contacted_at: string | null;
  stage_id: string | null;
  next_step_id: string | null;
  owner_user_id: string | null;
  trade_event_id: string | null;
  notes: string | null;
  pipeline_id: string | null;
  intro_sent: boolean;
  deal_value: number | null;
  deal_currency: string | null;
  phone_country_code: string | null;
  phone_secondary_country_code: string | null;
};
export type Pipeline = { id: string; name: string; lead_type: 'buyer' | 'supplier' | 'both'; is_default: boolean };
export type Option = { id: string; name: string };
export type ProductCategory = { id: string; name: string; is_active?: boolean; sort_order?: number; parent_id?: string | null };
export type Product = { id: string; name: string; sku: string | null; category_id: string | null };
export type Profile = { id: string; full_name: string | null; username: string | null };
export type Country = { id: string; name: string; phone_code: string | null; market_id: string | null; iso2_code?: string | null };
export type FollowUp = { id: string; lead_id: string | null; scheduled_at: string | null; status: string; created_at?: string | null; completed_at?: string | null; notes?: string | null };
export type Activity = { id: string; lead_id: string; kind: string; message: string; occurred_at: string };
export type StageHistory = { id: string; lead_id: string; from_stage_id: string | null; to_stage_id: string | null; changed_at: string; note: string | null };
export type RfqLineItem = { id: string; rfq_id: string | null; product_id: string | null; product_variant_id?: string | null; catalog_price_id?: string | null; catalog_price_amount?: number | null; unit_price?: number | null; currency?: string | null; is_price_overridden?: boolean | null };
export type QuoteLineItem = { id: string; quote_id: string | null; product_id: string | null; product_variant_id?: string | null; catalog_price_id?: string | null; catalog_price_amount?: number | null; unit_price?: number | null; currency?: string | null; is_price_overridden?: boolean | null };
export type Rfq = { id: string; lead_id: string | null; status: string; currency: string | null; validity_date: string | null; created_at: string | null; updated_at: string | null; notes?: string | null; lineItems?: RfqLineItem[] };
export type Quote = { id: string; lead_id: string; rfq_id: string | null; status: string; currency: string | null; created_at: string; updated_at: string; notes?: string | null; lineItems?: QuoteLineItem[] };
export type ComplianceItem = { id: string; lead_id: string; compliance_item_id: string; status: string; created_at: string; submitted_at: string | null; approved_at: string | null };
export type ComplianceDefinition = { id: string; code: string; description: string };
export type LeadDocument = { id: string; related_entity?: string | null; related_id?: string | null; requirement_code: string | null; status: string | null; expires_at: string | null; uploaded_at?: string | null };
export type Variant = { id: string; name: string; product_id: string };
export type Price = { id: string; product_variant_id: string; market_id: string | null; price: number; currency: string; effective_from: string; effective_to: string | null };
export type PricingRule = { id: string; product_id: string | null; product_variant_id: string | null; effective_from: string | null; effective_to: string | null; ex_factory_usd?: number | null; fob_usd?: number | null; ex_factory_inr?: number | null; fob_inr?: number | null; ex_factory_usd_per_case?: number | null; ex_factory_usd_per_unit?: number | null; fob_usd_per_case?: number | null; fob_usd_per_unit?: number | null; bulk_usd_per_kg?: number | null; pricing_type?: string | null };

export type LeadCardMoveOption = { stageId: string; label: string; disabled: boolean; sortOrder: number };
export type FollowUpVisualState = LeadFollowUpVisualState;

export interface LeadCardProps {
  canManageLeads: boolean;
  readOnlyMessage?: string | null;
  lead: Lead;
  state: FollowUpVisualState;
  history: FollowUp[];
  nextStepMap: Map<string, string>;
  handleMove: (leadId: string, stageId: string) => void;
  handleAddNote: (leadId: string, note: string) => Promise<{ error?: string; success?: string } | undefined>;
  handleScheduleFollowUp: (leadId: string, scheduledAt: string) => Promise<{ error?: string; success?: string } | undefined>;
  isPending: boolean;
  commandCenterHref: string;
  setDraggedLeadId: (id: string | null) => void;
  setDragOverStageId: (id: string | null) => void;
  safeFormatDateTime: (value?: string | null) => string;
  health: string;
  ownerLabel: string;
  blockerCount: number;
  pricingLabel: string;
  pricingClassName: string;
  stageLabel: string;
  blockerSummary: string;
  openRfqCount: number;
  activeQuoteCount: number;
  agingLabel: string;
  moveReadiness: StageMoveReadiness;
  moveOptions: LeadCardMoveOption[];
  countryCode?: string | null;
  coverageSummary?: string;
  isSelected?: boolean;
  onSelectedChange?: (leadId: string, selected: boolean) => void;
}

export interface PipelineBoardProps {
  currentUserId: string;
  canManageLeads: boolean;
  readOnlyMessage?: string | null;
  isWorkspaceEmpty: boolean;
  isStageConfigurationEmpty: boolean;
  stages: Stage[];
  leads: Lead[];
  pipelines: Pipeline[];
  nextSteps: Option[];
  tradeEvents: Option[];
  productCategories: ProductCategory[];
  products: Product[];
  markets: Array<{ id: string; name: string }>;
  profiles: Profile[];
  countries: Country[];
  leadMarkets: Array<{ lead_id: string; market_id: string }>;
  leadProductInterests: Array<{ lead_id: string; product_id: string }>;
  followUps: FollowUp[];
  activities: Activity[];
  stageHistory?: StageHistory[];
  rfqs?: Rfq[];
  quotes?: Quote[];
  complianceItems?: ComplianceItem[];
  complianceDefinitions?: ComplianceDefinition[];
  documents?: LeadDocument[];
  documentRequirementRules?: any[];
  variants?: Variant[];
  prices?: Price[];
  pricingRules?: PricingRule[];
  initialLeadType?: '' | LeadJourney;
  initialMode?: WorkspaceMode;
  initialTodayState?: TodayLayerState;
}
