
'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type Meeting = { id:string; title:string; starts_at:string; ends_at:string; location?:string|null; meeting_metadata?:Record<string,any>|null };

function localValue(date:Date){const pad=(n:number)=>String(n).padStart(2,'0');return date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate())+'T'+pad(date.getHours())+':'+pad(date.getMinutes());}

export function StarkMeetingPanel({entityType,entityId,customerName,customerEmail,customerPhone,companyName,canWork,compact=false}:{entityType:'lead'|'inbound_lead';entityId:string;customerName:string;customerEmail?:string|null;customerPhone?:string|null;companyName:string;canWork:boolean;compact?:boolean}){
  const initial=useMemo(()=>{const d=new Date(Date.now()+60*60*1000);d.setSeconds(0,0);return localValue(d);},[]);
  const [bookingType,setBookingType]=useState('scheduled'),[editingId,setEditingId]=useState<string|null>(null),[editingAction,setEditingAction]=useState('no_show'),[rescheduleAt,setRescheduleAt]=useState(initial),[statusNote,setStatusNote]=useState(''),[when,setWhen]=useState(initial),[duration,setDuration]=useState(45),[meetingType,setMeetingType]=useState('customer_visit'),[purpose,setPurpose]=useState(''),[location,setLocation]=useState(''),[internalEmails,setInternalEmails]=useState(''),[inviteCustomer,setInviteCustomer]=useState(false),[meetings,setMeetings]=useState<Meeting[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[whatsAppShare,setWhatsAppShare]=useState<string|null>(null);
  const load=useCallback(async()=>{const query=new URLSearchParams({entityType,entityId});const response=await fetch('/api/stark/meetings?'+query.toString(),{cache:'no-store'});if(response.ok){const data=await response.json();setMeetings(data.meetings||[]);}},[entityType,entityId]);
  useEffect(()=>{void load();},[load]);
  async function schedule(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');setWhatsAppShare(null);try{const startsAt=new Date(when);const attendeeEmails=internalEmails.split(',').map(v=>v.trim()).filter(Boolean);const response=await fetch('/api/stark/meetings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType,entityId,customerName,customerEmail,companyName,startsAt:startsAt.toISOString(),durationMinutes:duration,bookingType,meetingType,purpose,location,attendeeEmails,inviteCustomer})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to schedule meeting.');const digits=String(customerPhone||'').replace(/[^0-9]/g,'');
      if(digits&&bookingType==='scheduled'){const details=['Hi '+customerName+', confirming our meeting with '+companyName+' on '+startsAt.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})+'.',location?'Location: '+location+'.':'',purpose?'Purpose: '+purpose+'.':''].filter(Boolean).join(' ');setWhatsAppShare('https://wa.me/'+digits+'?text='+encodeURIComponent(details));}
      setPurpose('');setInternalEmails('');setMessage(data.warning||(bookingType==='walk_in'?'Walk-in meeting recorded.':'Meeting scheduled successfully. Customer email is optional; share the details by WhatsApp or email if needed.'));await load();}catch(error){setMessage(error instanceof Error?error.message:'Unable to schedule meeting.');}finally{setBusy(false);}}
  async function markDone(id:string,outcome:string,action='completed'){setBusy(true);setMessage('');try{const response=await fetch('/api/stark/meetings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:id,entityType,entityId,action,outcome,note:statusNote,startsAt:new Date(rescheduleAt).toISOString()})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to update meeting.');setMessage('Meeting updated.');setEditingId(null);setStatusNote('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Unable to update meeting.');}finally{setBusy(false);}}
  const upcoming=meetings.filter(m=>String(m.meeting_metadata?.meeting_status||'scheduled')==='scheduled');
  return <section className={compact?'':'rounded-2xl border border-violet-200 bg-white p-4 shadow-sm'}>
    <div className="flex items-start justify-between gap-3"><div><h3 className="text-[10px] font-black uppercase tracking-[.12em] text-violet-700">📅 Meeting details</h3><p className="mt-1 text-xs font-black text-slate-950">{upcoming.length?String(upcoming.length)+' upcoming meeting'+(upcoming.length===1?'':'s'):'Schedule this follow-up as a meeting'}</p></div>{compact?null:<Link href="/leads/meetings" className="rounded-lg border border-violet-200 bg-violet-50 px-2.5 py-1.5 text-[10px] font-black text-violet-700">Team meetings</Link>}</div>
    {upcoming.slice(0,2).map(meeting=><div key={meeting.id} className="mt-3 rounded-xl border border-violet-100 bg-violet-50/60 p-3"><p className="text-xs font-black text-slate-900">{new Date(meeting.starts_at).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</p><p className="mt-1 text-[10px] text-slate-600">{String(meeting.meeting_metadata?.meeting_type||'meeting').replace(/_/g,' ')}{meeting.location?' · '+meeting.location:''}</p><div className="mt-2 flex flex-wrap gap-1.5">{['positive','follow_up_required','quote_requested','sample_requested','neutral'].map(outcome=><button key={outcome} type="button" disabled={busy} onClick={()=>markDone(meeting.id,outcome)} className="rounded-lg border border-violet-200 bg-white px-2 py-1 text-[9px] font-bold text-violet-700">{outcome.replace(/_/g,' ')}</button>)}</div><div className="mt-2 flex flex-wrap gap-2">{['no_show','cancelled','rescheduled'].map(action=><button key={action} type="button" onClick={()=>{setEditingId(meeting.id);setEditingAction(action);setStatusNote('');}} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-[10px] font-semibold text-slate-700">{action==='no_show'?'No Show':action==='cancelled'?'Cancel':'Reschedule'}</button>)}</div>{editingId===meeting.id?<div className="mt-3 space-y-2 rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold">Update meeting</p><select value={editingAction} onChange={e=>setEditingAction(e.target.value)} className="w-full rounded-lg border border-slate-200 p-2 text-xs"><option value="no_show">No Show</option><option value="cancelled">Cancelled</option><option value="rescheduled">Reschedule</option></select>{editingAction==='rescheduled'?<input type="datetime-local" value={rescheduleAt} onChange={e=>setRescheduleAt(e.target.value)} className="w-full rounded-lg border border-slate-200 p-2 text-xs"/>:null}<textarea value={statusNote} onChange={e=>setStatusNote(e.target.value)} placeholder="Reason or meeting note" className="w-full rounded-lg border border-slate-200 p-2 text-xs"/><button type="button" disabled={busy} onClick={()=>{void markDone(meeting.id,'',editingAction);}} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Save update</button></div>:null}</div>)}
    <form onSubmit={schedule} className="mt-3 space-y-2">
      <div className="grid gap-2 sm:grid-cols-2"><select value={bookingType} onChange={e=>{setBookingType(e.target.value);if(e.target.value==='walk_in')setMeetingType('office_visit');}} className="rounded-xl border border-violet-200 px-3 py-2 text-xs"><option value="scheduled">Scheduled meeting</option><option value="walk_in">Walk-in meeting completed</option></select><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2 text-xs" required/><select value={meetingType} onChange={e=>setMeetingType(e.target.value)} className="rounded-xl border border-violet-200 px-3 py-2 text-xs"><option value="customer_visit">Visit customer</option><option value="office_visit">Customer visits office</option><option value="video_call">Video call</option><option value="other">Other meeting</option></select></div>
      <div className="grid gap-2 sm:grid-cols-[120px_1fr]"><select value={duration} onChange={e=>setDuration(Number(e.target.value))} className="rounded-xl border border-violet-200 px-3 py-2 text-xs"><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={90}>90 min</option></select><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location / address / video link" className="rounded-xl border border-violet-200 px-3 py-2 text-xs"/></div>
      <input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Purpose — trust building, requirement review, pricing discussion…" className="w-full rounded-xl border border-violet-200 px-3 py-2 text-xs" required/>
      <input value={internalEmails} onChange={e=>setInternalEmails(e.target.value)} placeholder="Invite internal team by email, comma separated" className="w-full rounded-xl border border-violet-200 px-3 py-2 text-xs"/>
      <div className="rounded-xl border border-violet-100 bg-violet-50/50 p-3"><p className="text-[10px] font-black text-violet-900">Customer invite is optional</p><p className="mt-1 text-[9px] leading-4 text-violet-700">The meeting can be saved without an email address. Share it by WhatsApp, email, or verbally after scheduling.</p>{customerEmail?<label className="mt-2 flex items-center gap-2 text-[10px] font-semibold text-slate-600"><input type="checkbox" checked={inviteCustomer} onChange={e=>setInviteCustomer(e.target.checked)}/>Also email calendar invitation to {customerEmail}</label>:null}</div>
      <p className="text-[9px] leading-4 text-violet-700">15-minute reminder is automatic. Invited staff receive alerts. Surbhi receives management visibility by email and in-app alert without being added as an attendee.</p>
      {message?<p className="rounded-lg bg-slate-50 px-2.5 py-2 text-[10px] font-semibold text-slate-700">{message}</p>:null}{whatsAppShare?<a href={whatsAppShare} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center rounded-xl border border-emerald-300 bg-emerald-50 px-3 py-2.5 text-xs font-black text-emerald-800">💬 Share meeting via WhatsApp</a>:null}
      <button disabled={!canWork||busy||!when||!purpose.trim()} className="w-full rounded-xl bg-violet-700 px-3 py-2.5 text-xs font-black text-white disabled:opacity-50">{busy?'Saving…':bookingType==='walk_in'?'Record walk-in meeting':'Schedule meeting'}</button>
    </form>
  </section>;
}
