export type RoleOption = { id: string; name: string; organizationId: string | null };
export type UserDrawerTab = 'profile' | 'role' | 'security' | 'activity';
export type AdminUserRow = { id: string; membershipId: string | null; invitationId: string | null; userId: string | null; name: string; username: string | null; email: string | null; roleId: string | null; roleName: string | null; status: 'active' | 'disabled' | 'invited'; lastActiveAt: string | null; invitedAt: string | null; detailNote: string | null; canChangeRole: boolean; canDeactivate: boolean; canResendInvite: boolean; tabs: UserDrawerTab[] };
export type AdminUsersSummary = { totalUsers: number; activeUsers: number; invitedUsers: number; disabledUsers: number };
type MemberRecord = { id?: unknown; user_id?: unknown; is_active?: unknown; created_at?: unknown; updated_at?: unknown; profiles?: unknown; user_roles?: unknown };
type InvitationRecord = { id?: unknown; email?: unknown; status?: unknown; created_at?: unknown; updated_at?: unknown; expires_at?: unknown; last_sent_at?: unknown; accepted_at?: unknown; roles?: unknown; role_id?: unknown };
type RoleRecord = { id?: unknown; name?: unknown; organization_id?: unknown };
const asOptionalString = (value: unknown): string | null => typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
const asBoolean = (value: unknown, fallback = false): boolean => typeof value === 'boolean' ? value : fallback;
const asRecord = (value: unknown): Record<string, unknown> | null => value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
const asArray = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const firstRelation = (value: unknown): Record<string, unknown> | null => asRecord(value) ?? asRecord(asArray(value)[0]);
function normalizeRole(record: RoleRecord): RoleOption | null { const id = asOptionalString(record.id); const name = asOptionalString(record.name); if (!id || !name) return null; return { id, name, organizationId: asOptionalString(record.organization_id) }; }
function buildMemberRow(member: MemberRecord): AdminUserRow | null { const membershipId = asOptionalString(member.id); if (!membershipId) return null; const profile = firstRelation(member.profiles); const roleWrapper = firstRelation(member.user_roles); const role = firstRelation(roleWrapper?.roles); const fullName = asOptionalString(profile?.full_name); const username = asOptionalString(profile?.username); const email = asOptionalString(profile?.email); const isActive = asBoolean(member.is_active, true); return { id: `member-${membershipId}`, membershipId, invitationId: null, userId: asOptionalString(member.user_id), name: fullName ?? username ?? email ?? 'Unnamed user', username, email, roleId: asOptionalString(role?.id) ?? asOptionalString(roleWrapper?.role_id), roleName: asOptionalString(role?.name), status: isActive ? 'active' : 'disabled', lastActiveAt: asOptionalString(member.updated_at) ?? asOptionalString(member.created_at), invitedAt: null, detailNote: username ? `Username: ${username}` : null, canChangeRole: true, canDeactivate: isActive, canResendInvite: false, tabs: ['profile','role','security','activity'] }; }
function buildInvitationRow(invitation: InvitationRecord): AdminUserRow | null { const invitationId = asOptionalString(invitation.id); if (!invitationId) return null; const status = asOptionalString(invitation.status); if (status !== 'draft' && status !== 'pending' && status !== 'sent') return null; const role = firstRelation(invitation.roles); const invitedAt = asOptionalString(invitation.last_sent_at) ?? asOptionalString(invitation.created_at); return { id: `invite-${invitationId}`, membershipId: null, invitationId, userId: null, name: asOptionalString(invitation.email) ?? 'Pending invitation', username: null, email: asOptionalString(invitation.email), roleId: asOptionalString(invitation.role_id) ?? asOptionalString(role?.id), roleName: asOptionalString(role?.name), status: 'invited', lastActiveAt: asOptionalString(invitation.accepted_at) ?? invitedAt, invitedAt, detailNote: asOptionalString(invitation.expires_at) ? `Expires ${asOptionalString(invitation.expires_at)}` : null, canChangeRole: false, canDeactivate: false, canResendInvite: true, tabs: ['profile','security','activity'] }; }
export function buildAdminUsersViewModel(data: { members: MemberRecord[]; invitations: InvitationRecord[]; roles: RoleRecord[] }): { rows: AdminUserRow[]; roles: RoleOption[]; summary: AdminUsersSummary } { const roles = data.roles.map(normalizeRole).filter((i): i is RoleOption => i !== null).sort((a,b)=>{ if (a.organizationId && !b.organizationId) return -1; if (!a.organizationId && b.organizationId) return 1; return a.name.localeCompare(b.name); }); const memberRows = data.members.map(buildMemberRow).filter((i): i is AdminUserRow => i !== null); const invitationRows = data.invitations.map(buildInvitationRow).filter((i): i is AdminUserRow => i !== null); const rows = [...memberRows, ...invitationRows].sort((a,b)=>{ const at=Date.parse(a.lastActiveAt ?? a.invitedAt ?? '') || 0; const bt=Date.parse(b.lastActiveAt ?? b.invitedAt ?? '') || 0; return bt-at || a.name.localeCompare(b.name); }); return { rows, roles, summary: { totalUsers: rows.length, activeUsers: memberRows.filter(r=>r.status==='active').length, invitedUsers: invitationRows.length, disabledUsers: memberRows.filter(r=>r.status==='disabled').length } }; }
