import { z } from 'zod';

export const leadSchema = z.object({
  lead_id: z.string().optional(),
  lead_type: z.enum(['buyer', 'supplier']).default('buyer'),
  company_name: z.string().min(1, 'Company name is required.'),
  contact_name: z.string().optional(),
  job_title: z.string().optional(),
  email: z.union([z.string().email(), z.literal('')]).optional(),
  phone: z.string().optional(),
  phone_secondary: z.string().optional(),
  phone_country_code: z.string().optional(),
  phone_secondary_country_code: z.string().optional(),
  website: z.string().optional(),
  social_handle: z.string().optional(),
  country: z.string().optional(),
  country_id: z.string().optional(),
  source_type: z.string().optional(),
  source_label: z.string().optional(),
  stage_id: z.string().optional(),
  pipeline_id: z.string().optional(),
  next_step_id: z.string().optional(),
  owner_user_id: z.string().optional(),
  trade_event_id: z.string().optional(),
  notes: z.string().optional(),
  deal_currency: z.string().optional(),
  next_follow_up_at: z.string().optional(),
  deal_value: z.union([z.string(), z.number()]).optional(),
  intro_sent: z.union([z.literal('true'), z.literal('false'), z.string()]).optional(),
});
