'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { savePricingComponentChargeV4, savePricingComponentCostV4 } from '@/features/packaging/server/pricing-v4-admin-ux-actions';
import { savePackagingChargeMasterRateV4, savePackagingCostMasterRateV4 } from '@/features/packaging/server/pricing-v4-admin-catalog-actions';

const YELLOW='rounded-lg border border-yellow-300 bg-yellow-50 px-2.5 py-2 text-sm text-slate-900 outline-none ring-yellow-200 focus:ring-2';
const PRIMARY='rounded-lg bg-slate-900 px-3.5 py-2 text-sm font-semibold text-white hover:bg-slate-800';
const SECONDARY='rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50';
const RATE_BUTTON='shrink-0 rounded-lg border border-slate-300 bg-white px-2.5 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50';

type Tab='materials'|'production'|'extras'|'charges';
type RateAction=(formData:FormData)=>Promise<void>;

function familyNames(ids:string[],families:any[]){return ids.map(id=>families.find(f=>String(f.id)===id)?.name).filter(Boolean).join(', ')||'Not linked';}
function titleFor(tab:Tab){return tab==='materials'?'Materials':tab==='production'?'Production':tab==='extras'?'Finishes & Extras':'Other Charges';}

export default function PricingComponentsV4Manager({data}:{data:any}){
  const {families=[],costs=[],charges=[],costLinks=[],chargeLinks=[],referenceItems=[]}=data;
  const [tab,setTab]=useState<Tab>('materials');
  const materialSuggestions=referenceItems.filter((item:any)=>item.category==='material'&&item.is_active);
  const finishSuggestions=referenceItems.filter((item:any)=>item.category==='finish'&&item.is_active);
  const serviceSuggestions=referenceItems.filter((item:any)=>item.category==='service_item'&&item.is_active);
  const rows=useMemo(()=>{
    if(tab==='materials')return costs.filter((row:any)=>row.item_type==='material');
    if(tab==='production')return costs.filter((row:any)=>row.item_type==='process');
    if(tab==='extras')return charges.filter((row:any)=>row.category==='extra');
    return charges.filter((row:any)=>row.category!=='extra');
  },[tab,costs,charges]);
  const needsRate=[...costs,...charges].filter((row:any)=>row.current_rate==null).length;

  return <div className="space-y-4 pb-16">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">Pricing Components</p><h2 className="mt-1 text-xl font-bold text-slate-950">Reusable materials, processes, extras and charges</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">This is the shared pricing library. Recipes pick components from here; rates are maintained once and reused everywhere.</p></div><Link href="/admin/packaging-templates" className={SECONDARY}>Open Pricing Builder →</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Metric label="Materials" value={costs.filter((x:any)=>x.item_type==='material').length}/><Metric label="Production" value={costs.filter((x:any)=>x.item_type==='process').length}/><Metric label="Extras & charges" value={charges.length}/><Metric label="Needs rate" value={needsRate} warn={needsRate>0}/></div></section>

    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-1 border-b border-slate-200 px-4 pt-3">{(['materials','production','extras','charges'] as Tab[]).map(key=><button key={key} type="button" onClick={()=>setTab(key)} className={`border-b-2 px-3 py-2.5 text-sm font-semibold ${tab===key?'border-emerald-600 text-emerald-700':'border-transparent text-slate-500 hover:text-slate-800'}`}>{titleFor(key)}</button>)}</div><div className="p-5">
      <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{titleFor(tab)}</h3><p className="mt-1 text-sm text-slate-500">Rates are yellow and can be changed directly in the list for fast price-impact checks. Use Edit setup only for basis, specification, product availability or other configuration.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{rows.length} items</span></div>
      <datalist id="pricing-material-names">{materialSuggestions.map((item:any)=><option key={item.id} value={item.name}/>)}</datalist><datalist id="pricing-finish-names">{finishSuggestions.map((item:any)=><option key={item.id} value={item.name}/>)}</datalist><datalist id="pricing-service-names">{serviceSuggestions.map((item:any)=><option key={item.id} value={item.name}/>)}</datalist>
      <div className="space-y-2">{rows.map((row:any)=>tab==='materials'||tab==='production'?<CostRow key={row.id} row={row} families={families} links={costLinks} suggestions={tab==='materials'?'pricing-material-names':'pricing-service-names'}/>:<ChargeRow key={row.id} row={row} families={families} links={chargeLinks} suggestions={tab==='extras'?'pricing-finish-names':'pricing-service-names'}/>)}</div>
      <details className="mt-4 rounded-xl border border-dashed border-yellow-300 bg-yellow-50/40 p-4"><summary className="cursor-pointer font-bold text-slate-800">+ Add {titleFor(tab).replace(/s$/,'')} component</summary><div className="mt-4">{tab==='materials'||tab==='production'?<CostForm row={null} families={families} selected={new Set<string>()} itemType={tab==='materials'?'material':'process'} suggestions={tab==='materials'?'pricing-material-names':'pricing-service-names'}/>:<ChargeForm row={null} families={families} selected={new Set<string>()} category={tab==='extras'?'extra':'pre'} suggestions={tab==='extras'?'pricing-finish-names':'pricing-service-names'}/>}</div></details>
    </div></section>

    <section className="rounded-xl border border-blue-200 bg-blue-50/50 p-4 text-sm text-slate-700"><b>Reference Library reused:</b> {referenceItems.filter((item:any)=>item.is_active).length} existing reusable names remain available as suggestions. Pricing Components adds the authoritative rate, basis and product availability needed by the v4 engine.</section>
  </div>;
}

function Metric({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className={`rounded-xl border p-3 ${warn?'border-amber-200 bg-amber-50':'border-slate-200 bg-slate-50'}`}><div className="text-xl font-black text-slate-950">{value}</div><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</div></div>;}

function QuickRateForm({row,action}:{row:any;action:RateAction}){return <form action={action} className="flex min-w-0 items-center gap-2"><input type="hidden" name="id" value={row.id}/><div className="relative min-w-0 flex-1"><span className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-[10px] font-bold text-slate-500">INR</span><input aria-label={`Rate for ${row.name}`} name="current_rate" type="number" min="0" step="0.0001" defaultValue={row.current_rate??''} placeholder="Needs rate" className={`${YELLOW} w-full pl-10 tabular-nums`}/></div><button type="submit" className={RATE_BUTTON}>Save rate</button></form>;}

function CostRow({row,families,links,suggestions}:{row:any;families:any[];links:any[];suggestions:string}){
  const [open,setOpen]=useState(false);
  const selected=new Set<string>(links.filter((link:any)=>String(link.cost_master_item_id)===String(row.id)).map((link:any)=>String(link.family_id)));
  return <div className="rounded-xl border border-slate-200 bg-white"><div className="grid gap-3 px-4 py-3 md:grid-cols-[minmax(180px,1fr)_110px_minmax(220px,290px)_minmax(180px,1fr)_90px_96px] md:items-center"><div><div className="font-semibold text-slate-900">{row.name}</div><div className="text-xs text-slate-500">{row.specification||row.code}</div></div><span className="text-sm text-slate-600">{row.rate_basis?.replaceAll('_',' ')}</span><QuickRateForm row={row} action={savePackagingCostMasterRateV4}/><span className="truncate text-xs text-slate-500">{familyNames([...selected],families)}</span><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-bold ${row.current_rate==null?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{row.current_rate==null?'Needs rate':'Ready'}</span><button type="button" onClick={()=>setOpen(value=>!value)} className={SECONDARY}>{open?'Close':'Edit setup'}</button></div>{open?<div className="border-t border-slate-100 bg-slate-50/60 p-4"><CostForm row={row} families={families} selected={selected} itemType={row.item_type} suggestions={suggestions}/></div>:null}</div>;
}
function ChargeRow({row,families,links,suggestions}:{row:any;families:any[];links:any[];suggestions:string}){
  const [open,setOpen]=useState(false);
  const selected=new Set<string>(links.filter((link:any)=>String(link.charge_master_item_id)===String(row.id)).map((link:any)=>String(link.family_id)));
  return <div className="rounded-xl border border-slate-200 bg-white"><div className="grid gap-3 px-4 py-3 md:grid-cols-[minmax(180px,1fr)_110px_minmax(220px,290px)_minmax(180px,1fr)_90px_96px] md:items-center"><div><div className="font-semibold text-slate-900">{row.name}</div><div className="text-xs text-slate-500">{row.category} · {row.code}</div></div><span className="text-sm text-slate-600">{row.basis?.replaceAll('_',' ')||'Needs basis'}</span><QuickRateForm row={row} action={savePackagingChargeMasterRateV4}/><span className="truncate text-xs text-slate-500">{familyNames([...selected],families)}</span><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-bold ${row.current_rate==null?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{row.current_rate==null?'Needs rate':'Ready'}</span><button type="button" onClick={()=>setOpen(value=>!value)} className={SECONDARY}>{open?'Close':'Edit setup'}</button></div>{open?<div className="border-t border-slate-100 bg-slate-50/60 p-4"><ChargeForm row={row} families={families} selected={selected} category={row.category} suggestions={suggestions}/></div>:null}</div>;
}

function FamilyChecks({families,selected}:{families:any[];selected:Set<string>}){return <div><div className="mb-1 text-[10px] font-bold uppercase text-slate-500">Available for products</div><div className="flex flex-wrap gap-2">{families.map((family:any)=><label key={family.id} className="flex items-center gap-1.5 rounded-lg border border-yellow-300 bg-yellow-50 px-2 py-1.5 text-xs font-semibold text-slate-700"><input type="checkbox" name="family_ids" value={family.id} defaultChecked={selected.has(String(family.id))}/>{family.name}</label>)}</div></div>;}
function CostForm({row,families,selected,itemType,suggestions}:{row:any|null;families:any[];selected:Set<string>;itemType:'material'|'process';suggestions:string}){return <form action={savePricingComponentCostV4} className="space-y-3"><input type="hidden" name="id" value={row?.id??''}/><input type="hidden" name="item_type" value={itemType}/><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Name<input list={suggestions} name="name" required defaultValue={row?.name??''} className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Code<input name="code" required defaultValue={row?.code??''} placeholder="MAT_..." className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Specification<input name="specification" defaultValue={row?.specification??''} className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Pricing basis<select name="rate_basis" defaultValue={row?.rate_basis??(itemType==='material'?'per_kg':'per_running_metre')} className={`${YELLOW} mt-1 w-full`}><option value="per_kg">Per kg</option><option value="per_running_metre">Per running metre</option><option value="per_frame">Per frame</option><option value="per_unit">Per piece</option><option value="flat">Flat</option></select></label><label className="text-xs font-semibold text-slate-600">Rate (INR)<input name="current_rate" type="number" min="0" step="0.0001" defaultValue={row?.current_rate??''} placeholder="Needs rate if blank" className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Rate UOM<input name="rate_uom" required defaultValue={row?.rate_uom??(itemType==='material'?'kg':'running_m')} className={`${YELLOW} mt-1 w-full`}/></label><input type="hidden" name="currency" value={row?.currency??'INR'}/>{itemType==='material'?<><label className="text-xs font-semibold text-slate-600">Micron<input name="micron" type="number" min="0" step="0.001" defaultValue={row?.micron??''} className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Density<input name="density" type="number" min="0" step="0.001" defaultValue={row?.density??''} className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">GSM<input name="gsm" type="number" min="0" step="0.001" defaultValue={row?.gsm??''} className={`${YELLOW} mt-1 w-full`}/></label></>:null}</div><FamilyChecks families={families} selected={selected}/><label className="flex items-center gap-2 text-xs font-semibold text-slate-700"><input type="checkbox" name="is_active" defaultChecked={row?.is_active??true}/> Active</label><button className={PRIMARY}>{row?'Save component':'Add component'}</button></form>;}
function ChargeForm({row,families,selected,category,suggestions}:{row:any|null;families:any[];selected:Set<string>;category:'extra'|'pre'|'post';suggestions:string}){return <form action={savePricingComponentChargeV4} className="space-y-3"><input type="hidden" name="id" value={row?.id??''}/><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Name<input list={suggestions} name="name" required defaultValue={row?.name??''} className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Code<input name="code" required defaultValue={row?.code??''} placeholder="EXTRA_..." className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">Type<select name="category" defaultValue={row?.category??category} className={`${YELLOW} mt-1 w-full`}><option value="extra">Finish / Extra</option><option value="pre">Pre-press</option><option value="post">Post / Handling</option></select></label><label className="text-xs font-semibold text-slate-600">Charge basis<select name="basis" defaultValue={row?.basis??'per_unit'} className={`${YELLOW} mt-1 w-full`}><option value="per_unit">Per piece</option><option value="per_running_metre">Per running metre</option><option value="per_frame">Per frame</option><option value="flat">Flat</option><option value="percent">Percent</option></select></label><label className="text-xs font-semibold text-slate-600">Rate (INR)<input name="current_rate" type="number" min="0" step="0.0001" defaultValue={row?.current_rate??''} placeholder="Needs rate if blank" className={`${YELLOW} mt-1 w-full`}/></label><label className="text-xs font-semibold text-slate-600">When applied<select name="application_stage" defaultValue={row?.application_stage??'separate_quote_line'} className={`${YELLOW} mt-1 w-full`}><option value="before_wastage_margin">Before waste & margin</option><option value="after_core_price">After core product price</option><option value="separate_quote_line">Separate quote line</option></select></label><label className="text-xs font-semibold text-slate-600">Percent base<select name="percent_base" defaultValue={row?.metadata?.percent_base??'product_total'} className={`${YELLOW} mt-1 w-full`}><option value="material_process_cogs_total">Material + Process COGS</option><option value="core_product_total">Core product total</option><option value="product_total">Product total</option></select></label><input type="hidden" name="currency" value={row?.currency??'INR'}/></div><FamilyChecks families={families} selected={selected}/><label className="flex items-center gap-2 text-xs font-semibold text-slate-700"><input type="checkbox" name="is_active" defaultChecked={row?.is_active??true}/> Active</label><button className={PRIMARY}>{row?'Save component':'Add component'}</button></form>;}
