'use client';

import { useEffect, useMemo, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { previewPackagingPricingV5, savePackagingPricingV5QuoteLine } from '@/features/packaging/server/pricing-v5-actions';
import { getPricingV5SupSampleKld } from '@/lib/packaging-pricing-v5/sample-klds';

function money(value:unknown,currency='INR'){const n=Number(value??0);return `${currency} ${Number.isFinite(n)?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'0.00'}`;}
function kldMatchesSize(item:any,size:any){if(!item||!size)return false;const file=String(item.file_name??'').toLowerCase().replace(/\s+/g,'');const w=String(Number(size.width_mm));const h=String(Number(size.height_mm));return file.includes(`${w}mmxh${h}mm`)||file.includes(`${w}x${h}`)||file.includes(`w${w}mmxh${h}mm`)||String(item.size_preset_key??'')===String(size.size_key??'');}

export default function PricingV5SalesConfiguratorV2({quoteId,leadId,options}:{quoteId:string;leadId:string;options:any}){
  const router=useRouter(); const families=options?.families??[]; const templates=options?.templates??[]; const sizes=options?.sizes??[]; const constructions=options?.constructions??[]; const klds=options?.klds??[]; const charges=options?.charges??[];
  const family=families[0]??null; const template=templates[0]??null;
  const [sizeId,setSizeId]=useState(sizes[0]?.id??''); const [constructionId,setConstructionId]=useState(constructions[0]?.id??''); const [print,setPrint]=useState<'CMYK'|'CMYKW'>('CMYKW'); const [quantity,setQuantity]=useState(5000); const [bottomPrintMode,setBottomPrintMode]=useState<'solid_unregistered'|'registered_artwork'|''>('');
  const [selectedChargeCodes,setSelectedChargeCodes]=useState<string[]>(()=>charges.some((x:any)=>x.code==='EXTRA_ZIPPER')?['EXTRA_ZIPPER']:[]); const [kldFileId,setKldFileId]=useState(''); const [preview,setPreview]=useState<any>(null); const [error,setError]=useState(''); const [saved,setSaved]=useState(''); const [pending,startTransition]=useTransition();
  const size=sizes.find((x:any)=>x.id===sizeId)??sizes[0]; const construction=constructions.find((x:any)=>x.id===constructionId)??constructions[0]; const askBottomPrint=size?.bottom_registration_mode==='optional'&&size?.gusset_production_mode==='conditional';
  const matchingKlds=useMemo(()=>klds.filter((x:any)=>kldMatchesSize(x,size)),[klds,size]); const sampleKld=getPricingV5SupSampleKld(size);
  const canPrice=Boolean(family?.id&&template?.id&&size?.id&&construction?.id&&quantity>0&&(!askBottomPrint||bottomPrintMode)); const currency=preview?.selling_price?.currency??template?.currency??'INR'; const alternativeRows=useMemo(()=>preview?.alternative_quantities??[],[preview]);
  const betterRows=useMemo(()=>{const current=Number(preview?.selling_price?.unit_price??0);return alternativeRows.filter((r:any)=>Number(r.quantity)>Number(quantity)&&Number(r.unit_price)>0&&Number(r.unit_price)<current).sort((a:any,b:any)=>Number(a.unit_price)-Number(b.unit_price));},[alternativeRows,preview,quantity]);

  useEffect(()=>{if(!sizes.some((x:any)=>x.id===sizeId))setSizeId(sizes[0]?.id??'');if(!constructions.some((x:any)=>x.id===constructionId))setConstructionId(constructions[0]?.id??'');},[sizes,constructions,sizeId,constructionId]);
  useEffect(()=>{if(!askBottomPrint)setBottomPrintMode('');setKldFileId('');setSaved('');},[sizeId,askBottomPrint]);

  function buildInput(targetQty=quantity){return{size_profile_id:size?.id??'',construction_id:construction?.id??'',print,quantity:targetQty,bottom_print_mode:askBottomPrint?(bottomPrintMode||undefined):undefined,selected_charge_codes:selectedChargeCodes,kld_file_id:kldFileId||null} as any;}
  function runPreview(){if(!canPrice)return;setError('');setSaved('');startTransition(async()=>{const r:any=await previewPackagingPricingV5({templateId:template.id,input:buildInput()});setPreview(r.result??null);if(!r.ok)setError(r.error??'Pricing needs attention.');});}
  useEffect(()=>{if(!canPrice){setPreview(null);return;}let cancelled=false;const timer=setTimeout(()=>{startTransition(async()=>{const r:any=await previewPackagingPricingV5({templateId:template.id,input:buildInput()});if(cancelled)return;setPreview(r.result??null);setError(r.ok?'':(r.error??'Pricing needs attention.'));});},220);return()=>{cancelled=true;clearTimeout(timer);};},[template?.id,size?.id,construction?.id,print,quantity,bottomPrintMode,selectedChargeCodes.join('|'),kldFileId,askBottomPrint]);
  function toggleCharge(code:string){setSelectedChargeCodes(cur=>cur.includes(code)?cur.filter(x=>x!==code):[...cur,code]);setSaved('');}
  function saveLine(){if(!canPrice||!preview?.ok)return;setError('');setSaved('');startTransition(async()=>{const r:any=await savePackagingPricingV5QuoteLine({quoteId,leadId,familyId:family.id,templateId:template.id,input:buildInput()});if(!r.ok){setError(r.error??'Packaging line could not be saved.');return;}setPreview(r.result??preview);setSaved('Packaging line added to this quote.');router.refresh();});}
  if(!family||!template||!sizes.length||!constructions.length)return null;

  const currentUnit=Number(preview?.selling_price?.unit_price??0); const best=betterRows[0]??null; const bestSavings=best&&currentUnit?((currentUnit-Number(best.unit_price))/currentUnit)*100:0;

  return <section className="rounded-2xl border border-teal-200 bg-white p-4 shadow-sm">
    <div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-teal-700">Packaging Pricing v5</p><h2 className="mt-1 text-xl font-black text-slate-950">Build a stand-up pouch quote</h2><p className="mt-1 max-w-3xl text-sm font-semibold text-slate-500">Sales chooses only valid published options. Price recalculates automatically and SETU suggests a better quantity when the approved commercial bands reduce unit price.</p></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Published v5 pricing</span></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-4"><Step number="1" title="Requirement" active/><Step number="2" title="Options & KLD" active={Boolean(size?.id&&construction?.id)}/><Step number="3" title="Live price" active={Boolean(preview?.ok)}/><Step number="4" title="Add to quote" active={Boolean(saved)}/></div>

    <div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]">
      <div className="space-y-4">
        <div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><div><div className="text-xs font-black text-slate-900">1. Customer requirement</div><div className="mt-1 text-[11px] text-slate-500">Unavailable sizes, constructions and commercial routes are hidden rather than disabled.</div></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-600">Sales view</span></div>
          <div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-black text-slate-600">Pouch size<select value={size?.id??''} onChange={e=>setSizeId(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-900">{sizes.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="text-[10px] font-black uppercase tracking-wide text-slate-400">Dimensions</div><div className="mt-1 text-sm font-black text-slate-800">{size?.width_mm} × {size?.height_mm} mm · BG {size?.bottom_gusset_each_mm}+{size?.bottom_gusset_each_mm}</div></div><label className="text-xs font-black text-slate-600">Material & finish<select value={construction?.id??''} onChange={e=>setConstructionId(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-900">{constructions.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs font-black text-slate-600">Printing<select value={print} onChange={e=>setPrint(e.target.value as any)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-900"><option value="CMYK">CMYK</option><option value="CMYKW">CMYKW</option></select></label></div>
          <div className="mt-3 rounded-xl border border-blue-200 bg-blue-50/60 p-3"><div className="text-[10px] font-black uppercase tracking-wide text-blue-500">Structure selected automatically</div><div className="mt-1 text-sm font-black text-slate-800">{construction?.structure_label}</div><p className="mt-1 text-xs text-slate-500">{construction?.layer_count} layers. Internal rates, waste and margin stay hidden.</p></div>
          {askBottomPrint?<div className="mt-3 rounded-xl border border-cyan-200 bg-cyan-50/50 p-3"><div className="text-xs font-black text-slate-700">Printing on the bottom gusset?</div><p className="mt-1 text-xs text-slate-500">Only shown because this answer changes the production route.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className={`cursor-pointer rounded-xl border p-3 text-sm font-bold ${bottomPrintMode==='solid_unregistered'?'border-teal-500 bg-white text-teal-800':'border-slate-200 bg-white text-slate-700'}`}><input className="mr-2" type="radio" checked={bottomPrintMode==='solid_unregistered'} onChange={()=>setBottomPrintMode('solid_unregistered')}/>Solid color only</label><label className={`cursor-pointer rounded-xl border p-3 text-sm font-bold ${bottomPrintMode==='registered_artwork'?'border-teal-500 bg-white text-teal-800':'border-slate-200 bg-white text-slate-700'}`}><input className="mr-2" type="radio" checked={bottomPrintMode==='registered_artwork'} onChange={()=>setBottomPrintMode('registered_artwork')}/>Logo, text or artwork</label></div></div>:<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50/60 p-3 text-xs font-bold text-emerald-700">{size?.gusset_production_mode==='separate'?'SETU automatically uses split-gusset production for this size.':'Bottom artwork question does not apply to this size.'}</div>}
        </div>

        <div className="rounded-2xl border border-slate-200 p-4"><div className="text-xs font-black text-slate-900">2. Options, quantity & KLD</div>{charges.length?<div className="mt-3 grid gap-2 md:grid-cols-2">{charges.map((x:any)=><label key={x.code} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 p-2.5 text-sm font-bold text-slate-700"><input type="checkbox" checked={selectedChargeCodes.includes(x.code)} onChange={()=>toggleCharge(x.code)}/><span>{x.name}</span></label>)}</div>:null}
          <div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-xs font-black text-slate-600">Quantity<input type="number" min={1} value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold"/></label><label className="text-xs font-black text-slate-600">KLD / dieline<select value={kldFileId} onChange={e=>setKldFileId(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold"><option value="">{matchingKlds.length?'No production KLD selected':'No approved production KLD for this size'}</option>{matchingKlds.map((x:any)=><option key={x.id} value={x.id}>{x.file_name}{x.version?` · v${x.version}`:''}</option>)}</select><span className={`mt-1 block text-[11px] font-semibold ${matchingKlds.length?'text-emerald-600':'text-amber-600'}`}>{matchingKlds.length?`${matchingKlds.length} size-matched production KLD${matchingKlds.length===1?'':'s'} available.`:'KLDs from other sizes are hidden. Review sample is available below but cannot be selected for a customer quote.'}</span>{sampleKld?<a href={sampleKld.sample_url} target="_blank" className="mt-1 inline-flex text-[11px] font-black text-blue-700">Preview blank sample KLD →</a>:null}</label></div>
        </div>

        {!canPrice?<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-800">Complete the required selections before pricing.</div>:null}{error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}{saved?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{saved}</div>:null}
        <div className="flex flex-wrap gap-2"><button type="button" disabled={!canPrice||pending} onClick={runPreview} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">{pending?'Recalculating…':'Recalculate now'}</button>{preview?.ok?<button type="button" disabled={pending} onClick={saveLine} className="rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Add packaging line</button>:null}</div>
      </div>

      <aside className="space-y-3"><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="text-[10px] font-black uppercase tracking-[0.16em] text-teal-300">Customer price</div>{preview?.ok?<><div className="mt-3 text-3xl font-black">{money(preview.selling_price.unit_price,currency)}</div><div className="text-xs font-bold text-white/50">per pouch</div><div className="mt-4 border-t border-white/10 pt-3"><div className="flex justify-between text-xs text-white/60"><span>Order total</span><span className="font-black text-white">{money(preview.selling_price.product_total,currency)}</span></div><div className="mt-2 flex justify-between text-xs text-white/60"><span>GST</span><span>{money(preview.selling_price.gst,currency)}</span></div><div className="mt-2 flex justify-between text-xs text-white/60"><span>Total incl. GST</span><span className="font-black text-white">{money(preview.selling_price.grand_total_before_freight,currency)}</span></div></div></>:<div className="mt-3 text-sm font-bold text-white/55">Price appears automatically once required selections are complete.</div>}</div>
        {best?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3"><div className="text-[10px] font-black uppercase text-emerald-700">Better price option</div><div className="mt-2 text-sm font-black text-slate-900">{Number(best.quantity).toLocaleString()} pcs at {money(best.unit_price,currency)} / pc</div><div className="mt-1 text-xs text-emerald-800">About {bestSavings.toFixed(1)}% lower unit price than the current quantity.</div><button type="button" onClick={()=>setQuantity(Number(best.quantity))} className="mt-3 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Use {Number(best.quantity).toLocaleString()} pcs</button></div>:null}
        {alternativeRows.length?<div className="rounded-xl border border-slate-200 bg-white p-3"><div className="text-[10px] font-black uppercase text-slate-400">Quantity options</div><div className="mt-2 space-y-2">{alternativeRows.map((r:any)=><button type="button" key={r.quantity} onClick={()=>setQuantity(Number(r.quantity))} className={`w-full rounded-lg border p-2.5 text-left ${Number(r.quantity)===quantity?'border-teal-300 bg-teal-50':'border-slate-200 bg-white hover:bg-slate-50'}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black text-slate-700">{Number(r.quantity).toLocaleString()} pcs</span><span className="text-xs font-black text-slate-950">{money(r.unit_price,currency)} / pc</span></div><div className="mt-1 text-[11px] text-slate-500">Order {money(r.product_total,currency)}</div></button>)}</div></div>:null}
        <div className="rounded-xl border border-blue-200 bg-blue-50/50 p-3"><div className="text-[10px] font-black uppercase text-blue-500">Sales-safe view</div><p className="mt-1 text-xs font-semibold text-slate-600">No raw material rates, COGS, wastage, margin/frame or competitor intelligence is exposed here.</p></div>
      </aside>
    </div>
  </section>;
}
function Step({number,title,active}:{number:string;title:string;active:boolean}){return <div className={`rounded-xl border px-3 py-2 ${active?'border-teal-300 bg-teal-50':'border-slate-200 bg-slate-50'}`}><div className={`text-[10px] font-black ${active?'text-teal-700':'text-slate-400'}`}>STEP {number}</div><div className="mt-0.5 text-xs font-black text-slate-800">{title}</div></div>}
