import { NextRequest, NextResponse } from 'next/server';
import { createServiceRoleClient } from '@/lib/supabase/service-role';
import { getValidZoomAccessToken, zoomApi } from '@/lib/calendar/zoom';
export const dynamic='force-dynamic';
const emailOk=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
function timeParts(v:string){const[h,m]=String(v).split(':').map(Number);return h*60+m}
function withinAvailability(start:Date,end:Date,rules:any[]){return rules.some(r=>{if(Number(r.weekday)!==start.getDay())return false;const s=start.getHours()*60+start.getMinutes(),e=end.getHours()*60+end.getMinutes();return s>=timeParts(r.start_time)&&e<=timeParts(r.end_time)})}
export async function GET(req:NextRequest){const slug=req.nextUrl.searchParams.get('slug');if(!slug)return NextResponse.json({error:'Booking page required.'},{status:400});const db=createServiceRoleClient();if(!db)return NextResponse.json({error:'Booking service unavailable.'},{status:503});const{data:page}=await db.from('calendar_booking_pages').select('*').eq('slug',slug).eq('is_active',true).maybeSingle();if(!page)return NextResponse.json({error:'Booking page not found.'},{status:404});const[{data:availability},{data:events}]=await Promise.all([db.from('calendar_availability').select('weekday,start_time,end_time,timezone').eq('organization_id',page.organization_id).eq('user_id',page.user_id).eq('is_active',true),db.from('calendar_events').select('starts_at,ends_at').eq('organization_id',page.organization_id).eq('owner_user_id',page.user_id).gte('ends_at',new Date().toISOString()).lte('starts_at',new Date(Date.now()+page.booking_window_days*86400000).toISOString()).neq('status','cancelled')]);return NextResponse.json({page:{slug:page.slug,title:page.title,description:page.description,durationMinutes:page.duration_minutes,bufferMinutes:page.buffer_minutes,minimumNoticeMinutes:page.minimum_notice_minutes,bookingWindowDays:page.booking_window_days,meetingProvider:page.meeting_provider,timezone:availability?.[0]?.timezone||'UTC'},availability:availability??[],busy:events??[]})}
export async function POST(req:NextRequest){const body=await req.json();const db=createServiceRoleClient();if(!db)return NextResponse.json({error:'Booking service unavailable.'},{status:503});const email=String(body.email||'').trim().toLowerCase(),name=String(body.name||'').trim();if(!name||!emailOk(email))return NextResponse.json({error:'Enter your name and a valid email address.'},{status:400});const{data:p}=await db.from('calendar_booking_pages').select('*').eq('slug',body.slug).eq('is_active',true).single();if(!p)return NextResponse.json({error:'Booking page not found.'},{status:404});const start=new Date(body.startsAt),end=new Date(start.getTime()+p.duration_minutes*60000),latest=new Date(Date.now()+p.booking_window_days*86400000);if(Number.isNaN(start.valueOf())||start.getTime()<Date.now()+p.minimum_notice_minutes*60000||start>latest)return NextResponse.json({error:'That time is no longer available.'},{status:409});const{data:rules}=await db.from('calendar_availability').select('*').eq('organization_id',p.organization_id).eq('user_id',p.user_id).eq('is_active',true);if(!withinAvailability(start,end,rules??[]))return NextResponse.json({error:'That time is outside the organizer’s availability.'},{status:409});const buffer=Number(p.buffer_minutes||0)*60000;const{data:conflict}=await db.from('calendar_events').select('id').eq('organization_id',p.organization_id).eq('owner_user_id',p.user_id).lt('starts_at',new Date(end.getTime()+buffer).toISOString()).gt('ends_at',new Date(start.getTime()-buffer).toISOString()).neq('status','cancelled').limit(1);if(conflict?.length)return NextResponse.json({error:'That time was just booked. Please choose another.'},{status:409});
 let meetingUrl:string|null=p.meeting_provider==='custom'?p.custom_meeting_url||null:null,meetingExternalId:string|null=null,meetingHostUrl:string|null=null,provider=p.meeting_provider;
 if(provider==='zoom'){const{data:connection}=await db.from('meeting_connections').select('*').eq('organization_id',p.organization_id).eq('user_id',p.user_id).eq('provider','zoom').eq('status','active').maybeSingle();if(connection){try{const token=await getValidZoomAccessToken(db,connection);const z=await zoomApi(token,`/users/${encodeURIComponent(connection.provider_user_id||'me')}/meetings`,{method:'POST',body:JSON.stringify({topic:body.title||`Meeting with ${name}`,type:2,start_time:start.toISOString(),duration:p.duration_minutes,timezone:body.timezone||'UTC',settings:{waiting_room:true,join_before_host:false}})});meetingUrl=z?.join_url||null;meetingHostUrl=z?.start_url||null;meetingExternalId=String(z?.id||'')||null}catch{provider='custom';meetingUrl=p.custom_meeting_url||null}}else{provider='custom';meetingUrl=p.custom_meeting_url||null}}
 const{data:e,error}=await db.from('calendar_events').insert({organization_id:p.organization_id,owner_user_id:p.user_id,created_by:p.user_id,title:String(body.title||`Meeting with ${name}`).slice(0,180),description:String(body.notes||'').slice(0,4000)||null,starts_at:start.toISOString(),ends_at:end.toISOString(),timezone:body.timezone||'UTC',meeting_provider:provider,meeting_url:meetingUrl,meeting_external_id:meetingExternalId,meeting_host_url:meetingHostUrl}).select('*').single();if(error||!e)return NextResponse.json({error:'Unable to book this time.'},{status:500});await db.from('calendar_attendees').insert({organization_id:p.organization_id,event_id:e.id,email,name:name.slice(0,160)});await db.from('calendar_reminders').insert({organization_id:p.organization_id,event_id:e.id,channel:'in_app',minutes_before:15});return NextResponse.json({ok:true,eventId:e.id,meetingUrl},{status:201})}
