'use client';

import { useMemo, useState, useTransition } from 'react';
import { sendStarkLeadWhatsApp, logStarkExternalEmailSent } from '@/features/integrations/interakt/sales-message-actions';

type TimelineItem={id:string;channel:'whatsapp'|'email'|'note'|'call'|'system';direction:'inbound'|'outbound'|'internal';body:string;subject?:string|null;occurredAt:string;actorName?:string|null;status?:string|null;attachmentName?:string|null};
type Props={leadId:string;companyName:string;contactName:string;email?:string|null;whatsappNumber?:string|null;items:TimelineItem[];linkedInterakt:boolean;whatsappReplyWindowOpen:boolean};
const fmt=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});};
const day=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?'Conversation':d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',year:'numeric'});};
function displayBody(item:TimelineItem){const raw=String(item.body||'').trim();if(!raw)return'Activity recorded.';if(raw.startsWith('{')){try{const p=JSON.parse(raw);const title=p?.title||p?.button_reply?.title||p?.list_reply?.title||p?.interactive?.button_reply?.title||p?.interactive?.list_reply?.title;if(title)return String(title);}catch{}}return raw;}
function Icon({channel}:{channel:TimelineItem['channel']}){return <span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm ${channel==='whatsapp'?'bg-emerald-100 text-emerald-700':channel==='email'?'bg-blue-100 text-blue-700':channel==='note'?'bg-violet-100 text-violet-700':'bg-slate-100 text-slate-600'}`}>{channel==='whatsapp'?'●':channel==='email'?'✉':channel==='note'?'▣':'•'}</span>}

export function StarkCommunicationsLauncher(props:Props){
 const[open,setOpen]=useState(false),[filter,setFilter]=useState<'all'|'whatsapp'|'email'|'note'>('all'),[mode,setMode]=useState<'whatsapp'|'email'>('whatsapp'),[message,setMessage]=useState(''),[subject,setSubject]=useState(''),[feedback,setFeedback]=useState('');const[pending,startTransition]=useTransition();
 const visible=useMemo(()=>props.items.filter(i=>filter==='all'||i.channel===filter),[props.items,filter]);
 const groups=useMemo(()=>{const out:Array<{label:string;items:TimelineItem[]}>=[];for(const item of visible){const label=day(item.occurredAt),last=out[out.length-1];if(last?.label===label)last.items.push(item);else out.push({label,items:[item]});}return out;},[visible]);
 const inbound=props.items.filter(i=>i.direction==='inbound').length;
 function sendWhatsApp(){if(!message.trim())return;const f=new FormData();f.set('leadId',props.leadId);f.set('message',message.trim());startTransition(async()=>{const r=await sendStarkLeadWhatsApp(f);setFeedback(r.message);if(r.ok)setMessage('');});}
 function openEmail(){if(props.email)window.location.href=`mailto:${encodeURIComponent(props.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`;}
 function logEmail(){if(!props.email||!message.trim())return;const f=new FormData();f.set('leadId',props.leadId);f.set('toEmail',props.email);f.set('subject',subject);f.set('body',message.trim());startTransition(async()=>{const r=await logStarkExternalEmailSent(f);setFeedback(r.message);if(r.ok){setMessage('');setSubject('');}});}
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-800 shadow-sm transition hover:border-blue-200 hover:text-blue-700"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-blue-50 text-blue-600">▣</span>Communications{inbound?<span className="rounded-full bg-blue-600 px-2 py-0.5 text-[10px] text-white">{Math.min(inbound,99)}</span>:null}</button>
  {open?<div className="fixed inset-0 z-[80] flex justify-end bg-slate-950/25" role="dialog" aria-modal="true"><button className="absolute inset-0" aria-label="Close communications" onClick={()=>setOpen(false)}/><aside className="relative flex h-full w-full max-w-[470px] flex-col border-l border-slate-200 bg-white shadow-2xl">
   <header className="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 font-black text-blue-600">▣</span><div><p className="text-base font-black text-slate-950">Communications</p><p className="mt-0.5 text-xs text-slate-500">WhatsApp, Email and all interactions in one place</p><p className="mt-1 text-[11px] font-semibold text-slate-400">{props.companyName} · {props.contactName}</p></div></div><button onClick={()=>setOpen(false)} className="rounded-lg px-2 py-1 text-xl text-slate-500 hover:bg-slate-100">×</button></header>
   <div className="border-b border-slate-100 px-4 py-3"><div className="grid grid-cols-4 gap-2">{(['all','whatsapp','email','note'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} className={`rounded-xl border px-2 py-2 text-xs font-bold capitalize transition ${filter===v?'border-blue-200 bg-blue-50 text-blue-700':'border-slate-100 bg-white text-slate-600 hover:bg-slate-50'}`}>{v==='all'?'All':v==='whatsapp'?'● WhatsApp':v==='email'?'✉ Email':'▣ Notes'}</button>)}</div></div>
   <div className="flex-1 overflow-y-auto bg-white px-4 py-3">{!visible.length?<div className="mt-10 rounded-2xl border border-dashed border-slate-200 p-8 text-center"><p className="font-bold text-slate-800">No conversation recorded yet</p><p className="mt-1 text-xs text-slate-500">Customer interactions will appear here automatically.</p></div>:groups.map(g=><section key={g.label} className="mb-5"><div className="mb-3 flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{g.label}</span><span className="h-px flex-1 bg-slate-100"/></div><div className="space-y-3">{g.items.map(item=><div key={item.id} className={`flex gap-2 ${item.direction==='outbound'?'flex-row-reverse':''}`}><Icon channel={item.channel}/><div className={`max-w-[82%] rounded-2xl px-3.5 py-3 ${item.direction==='outbound'?'bg-blue-50':'bg-emerald-50'}`}><div className="mb-1 flex flex-wrap items-center gap-1.5"><span className="text-xs font-black text-slate-900">{item.direction==='outbound'?'You':item.actorName||props.companyName}</span><span className="text-[10px] font-semibold text-slate-400">{fmt(item.occurredAt)}</span></div>{item.subject?<p className="mb-1 text-xs font-black text-slate-800">{item.subject}</p>:null}<p className="whitespace-pre-wrap break-words text-sm leading-5 text-slate-700">{displayBody(item)}</p>{item.attachmentName?<div className="mt-2 rounded-xl border border-slate-200 bg-white p-2 text-xs font-semibold text-slate-600">📎 {item.attachmentName}</div>:null}</div></div>)}</div></section>)}</div>
   <footer className="border-t border-slate-200 bg-white p-4"><div className="mb-2 flex gap-3 text-xs font-bold"><button onClick={()=>{setMode('whatsapp');setFeedback('')}} className={mode==='whatsapp'?'text-emerald-700':'text-slate-500'}>● WhatsApp</button><button onClick={()=>{setMode('email');setFeedback('')}} className={mode==='email'?'text-blue-700':'text-slate-500'}>✉ Email</button></div>{mode==='email'?<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Email subject" className="mb-2 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-400"/>:null}<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} placeholder={mode==='whatsapp'?'Type a WhatsApp message…':'Write your email…'} className="w-full resize-none rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-blue-400"/>{mode==='whatsapp'&&!props.linkedInterakt?<p className="mt-2 text-[11px] text-amber-700">No linked Interakt conversation is available for this lead yet.</p>:null}{mode==='whatsapp'&&props.linkedInterakt&&!props.whatsappReplyWindowOpen?<p className="mt-2 text-[11px] text-amber-700">The WhatsApp free-text window is closed. Use an approved template to restart the conversation.</p>:null}{feedback?<p className="mt-2 text-xs font-semibold text-slate-600">{feedback}</p>:null}<div className="mt-3 flex items-center justify-between"><div className="flex gap-2 text-slate-400"><button type="button" className="rounded-lg border border-slate-200 px-2 py-1" title="Attachments coming with provider integration">⌕</button><button type="button" className="rounded-lg border border-slate-200 px-2 py-1" title="Templates">▣</button></div>{mode==='email'?<div className="flex gap-2"><button onClick={openEmail} disabled={!props.email} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:opacity-40">Open email</button><button onClick={logEmail} disabled={pending||!props.email||!message.trim()} className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Log sent</button></div>:<button onClick={sendWhatsApp} disabled={pending||!message.trim()||!props.linkedInterakt||!props.whatsappReplyWindowOpen} className="rounded-xl bg-emerald-600 px-5 py-2 text-xs font-black text-white disabled:opacity-40">{pending?'Sending…':'Send'}</button>}</div></footer>
  </aside></div>:null}
 </>;
}
