'use client';

import { useMemo, useState } from 'react';
import { FaIcon } from '@/components/ui/fa-icon';
import { createStarkLeadFollowUp } from './stark-lead-actions';

type FollowUp = { id: string; status?: string | null; notes?: string | null; scheduled_at?: string | null };
type Props = { leadId: string; contactName?: string | null; companyName: string; requirement?: string | null; hasArtwork: boolean; hasQuote: boolean; followUps: FollowUp[]; };
type Channel = 'whatsapp' | 'email' | 'call';

export default function StarkFollowUpComposer({leadId,contactName,companyName,requirement,hasArtwork,hasQuote,followUps}:Props){
 const [channel,setChannel]=useState<Channel>('whatsapp');
 const name=contactName||'there';
 const suggestions=useMemo(()=>{
   if(hasQuote)return [`Hi ${name}, just following up on the pricing we shared. Please let me know your expected quantity and if there is anything we should adjust to move this forward.`,`Hi ${name}, checking in on the quote shared for ${requirement||'your packaging requirement'}. Happy to clarify pricing, MOQ or delivery timing.`,`Hi ${name}, wanted to see if you had a chance to review our quote. What would help you take the next step?`];
   if(hasArtwork)return [`Hi ${name}, thanks for sharing the artwork. We are reviewing it for ${requirement||'your packaging'} and can now confirm the right structure, MOQ and pricing.`,`Hi ${name}, we have the artwork/reference. Please confirm the final quantity so we can prepare accurate pricing.`,`Hi ${name}, your artwork is with our team. I wanted to confirm quantity and any final print requirements before we price it.`];
   return [`Hi ${name}, following up on your ${requirement||'packaging requirement'}. If you share the artwork/design and expected quantity, we can recommend the right structure and pricing.`,`Hi ${name}, I wanted to follow up on your packaging inquiry. Do you already have artwork ready, or would you like our team to help?`,`Hi ${name}, thanks for connecting with ${companyName}. Please share the quantity and artwork status and I can help with MOQ and pricing.`];
 },[name,companyName,requirement,hasArtwork,hasQuote]);
 const suggestionLabels=useMemo(()=>hasQuote?['Pricing follow-up','Quote clarification','Decision nudge']:hasArtwork?['Artwork received','Confirm quantity','Final print check']:['Requirement follow-up','Artwork check','Quantity & pricing'],[hasArtwork,hasQuote]);
 const [selectedSuggestion,setSelectedSuggestion]=useState(0);
 const [message,setMessage]=useState(suggestions[0]);
 const active=followUps.filter(f=>f.status!=='completed');
 const icon:Record<Channel,string>={whatsapp:'whatsapp',email:'envelope',call:'phone'};
 const channelLabel:Record<Channel,string>={whatsapp:'WhatsApp',email:'Email',call:'Call'};
 function chooseSuggestion(index:number){setSelectedSuggestion(index);setMessage(suggestions[index]||suggestions[0]);}
 return <section id="tasks" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_10px_28px_rgba(15,23,42,.05)]">
   <div className="flex items-start justify-between gap-4 px-4 pb-3 pt-4 sm:px-5"><div><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-violet-50 text-violet-700">✦</span><h3 className="text-[15px] font-bold tracking-[-0.01em] text-slate-950">Smart Follow-up</h3></div><p className="mt-1 text-[11px] leading-4 text-slate-500">Setu Guru suggests the message. You choose the channel and timing.</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">{active.length} scheduled</span></div>
   <form action={createStarkLeadFollowUp} className="space-y-3 border-t border-slate-100 p-4 sm:px-5"><input type="hidden" name="lead_id" value={leadId}/><input type="hidden" name="channel" value={channel}/>
    <div><label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Follow-up channel</label><div className="relative"><span className={`pointer-events-none absolute left-3 top-1/2 flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-lg ${channel==='whatsapp'?'bg-emerald-50 text-emerald-700':channel==='email'?'bg-blue-50 text-blue-700':'bg-violet-50 text-violet-700'}`}><FaIcon icon={icon[channel]} fixedWidth/></span><select value={channel} onChange={e=>setChannel(e.target.value as Channel)} className="h-11 w-full appearance-none rounded-xl border border-slate-200 bg-white pl-12 pr-10 text-xs font-semibold text-slate-800 outline-none transition focus:border-violet-300 focus:ring-2 focus:ring-violet-100"><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="call">Call</option></select><span className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-xs text-slate-400">⌄</span></div></div>
    <div><div className="mb-1.5 flex items-center justify-between gap-3"><label className="text-[10px] font-semibold uppercase tracking-[.12em] text-violet-600">✦ Setu Guru suggested message</label><span className="text-[10px] text-slate-400">Choose a starting point</span></div><div className="relative"><select value={selectedSuggestion} onChange={e=>chooseSuggestion(Number(e.target.value))} className="h-11 w-full appearance-none rounded-xl border border-violet-200 bg-violet-50/40 px-3 pr-10 text-xs font-semibold text-violet-900 outline-none transition focus:border-violet-300 focus:ring-2 focus:ring-violet-100">{suggestions.map((_,i)=><option key={i} value={i}>Option {i+1} — {suggestionLabels[i]}</option>)}</select><span className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-xs text-violet-500">⌄</span></div></div>
    <div><div className="mb-1.5 flex items-center justify-between"><label className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Message</label><span className="text-[10px] text-slate-400">Editable before scheduling</span></div><textarea name="message" value={message} onChange={e=>setMessage(e.target.value)} rows={3} className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50/40 p-3 text-xs leading-5 text-slate-800 outline-none transition focus:border-violet-300 focus:bg-white focus:ring-2 focus:ring-violet-100" required/></div>
    <div><label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Schedule for</label><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><input name="scheduled_at" type="datetime-local" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 outline-none focus:border-violet-300 focus:ring-2 focus:ring-violet-100" required/><button className="rounded-xl bg-[#0B2440] px-5 py-3 text-xs font-semibold text-white shadow-[0_8px_20px_rgba(11,36,64,.18)] transition hover:bg-[#12395f]">Schedule {channelLabel[channel]} Follow-up</button></div></div>
    <div className="flex items-start gap-2 rounded-xl bg-slate-50 px-3 py-2 text-[10px] leading-4 text-slate-500"><span className="mt-0.5 text-slate-400">ⓘ</span><span>This creates a sales task only. The customer is contacted when the salesperson sends the message or makes the call.</span></div>
   </form>
 </section>;
}
