'use client';

import { useState } from 'react';
import Link from 'next/link';
import type { LeadProfileData } from '@/lib/queries/leads';
import { createLeadQuoteDraftFromLead } from '@/features/quotes/server/lead-draft-actions';
import { FaIcon } from '@/components/ui/fa-icon';
import { moveCanonicalLeadStage } from './actions';
import { uploadStarkLeadArtwork } from './stark-lead-actions';
import { StarkCommunicationsLauncher } from './StarkCommunicationsDrawer';
import StarkFollowUpComposer from './StarkFollowUpComposer';

type TeamMember = { id: string; name: string };
type CommProps = React.ComponentProps<typeof StarkCommunicationsLauncher>;
type Props = { data: LeadProfileData; canReassignOwner: boolean; teamMembers: TeamMember[]; backHref: string; communications: CommProps; intake?: any; leadScore?: number };
type TabKey = 'overview' | 'company' | 'contacts' | 'requirements' | 'quotes' | 'tasks' | 'notes' | 'communications' | 'files';

const initials = (v?: string | null) => String(v || 'Lead').split(/\s+/).slice(0, 2).map((x) => x[0]?.toUpperCase()).join('');
const title = (v?: string | null) => String(v || '').replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
function score(d: LeadProfileData) { let s = 25; if (d.lead?.email || d.lead?.phone) s += 15; if (d.linkedProducts.length) s += 20; if (d.linkedMarkets.length) s += 15; if (d.quotes.length) s += 15; if (d.followUps.length) s += 10; return Math.min(100, s); }
function Card({ title: cardTitle, children, action, className = '' }: { title: string; children: React.ReactNode; action?: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,.05)] ${className}`}><div className="mb-4 flex items-center justify-between gap-3"><h3 className="text-sm font-black text-slate-950">{cardTitle}</h3>{action}</div>{children}</section>; }
function Row({ l, v }: { l: string; v: any }) { return <div className="grid grid-cols-[120px_minmax(0,1fr)] gap-3 border-b border-slate-100 py-2.5 text-xs last:border-0"><span className="text-slate-400">{l}</span><b className="break-words text-slate-800">{v || '—'}</b></div>; }
function ActionTile({href,icon,label,value,tone,newTab=false}:{href:string;icon:string;label:string;value:string;tone:'green'|'blue'|'violet';newTab?:boolean}){const styles={green:'border-emerald-200 bg-emerald-50/70 text-emerald-700',blue:'border-blue-200 bg-blue-50/70 text-blue-700',violet:'border-violet-200 bg-violet-50/70 text-violet-700'};return <a href={href} target={newTab?'_blank':undefined} rel={newTab?'noreferrer':undefined} className={`group flex items-center gap-3 rounded-2xl border p-3.5 transition hover:-translate-y-0.5 hover:shadow-md ${styles[tone]}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white shadow-sm"><FaIcon icon={icon} fixedWidth/></span><span className="min-w-0"><b className="block text-xs">{label}</b><span className="mt-0.5 block truncate text-[10px] opacity-70">{value}</span></span></a>}

export default function StarkLeadDetailApproved({ data, teamMembers, backHref, communications, intake, leadScore }: Props) {
  const [tab, setTab] = useState<TabKey>('overview');
  const lead = data.lead!;
  const quotes = [...(data.quotes || [])];
  const whatsapp = lead.whatsapp_number || lead.phone;
  const phone=lead.phone||lead.whatsapp_number;
  const owner = teamMembers.find((x) => x.id === lead.owner_user_id)?.name || 'Unassigned';
  const media = communications.items.filter((x: any) => x.attachmentUrl);
  const customerMedia = media.filter((x: any) => x.direction === 'inbound');
  const recent = communications.items.slice(-5).reverse();
  const requirement = (lead as any).products_or_needs || (lead as any).main_product_category || intake?.pouch_type || intake?.packaging_type || 'Requirement developing from conversation';
  const stageList = data.stages.filter((s: any) => !lead.pipeline_id || s.pipeline_id === lead.pipeline_id).sort((a: any, b: any) => (a.sort_order ?? 0) - (b.sort_order ?? 0));
  const current = stageList.findIndex((s: any) => s.id === lead.stage_id);
  const activeFollowUps = data.followUps.filter((f: any) => f.status !== 'completed');
  const displayScore=typeof leadScore==='number'?leadScore:score(data);
  const followUp=<StarkFollowUpComposer leadId={lead.id} contactName={lead.contact_name} companyName={lead.company_name} requirement={requirement} hasArtwork={customerMedia.length>0} hasQuote={quotes.length>0} followUps={data.followUps as any}/>;
  const tabs: Array<{ key: TabKey; label: string; count?: number }> = [
    { key: 'overview', label: 'Overview' }, { key: 'company', label: 'Company' }, { key: 'contacts', label: 'Contacts' }, { key: 'requirements', label: 'Requirements' },
    { key: 'quotes', label: 'Quotes', count: quotes.length }, { key: 'tasks', label: 'Tasks', count: activeFollowUps.length }, { key: 'notes', label: 'Notes' },
    { key: 'communications', label: 'Communications', count: communications.items.length }, { key: 'files', label: 'Files', count: media.length },
  ];

  const requirementCard = <Card title="Requirement & Artwork"><p className="text-sm font-black">{requirement}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 text-xs"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Quantity</span><b className="mt-1 block">{intake?.quantity_text || 'Confirm'}</b></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Size / Print</span><b className="mt-1 block">{intake?.dimensions_print || 'Confirm'}</b></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Delivery</span><b className="mt-1 block">{intake?.delivery_location || 'Confirm'}</b></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Artwork</span><b className="mt-1 block text-emerald-700">{customerMedia.length ? 'Received' : 'Not received'}</b></div></div>{customerMedia.slice(-4).map((m: any) => <a key={m.id} href={m.attachmentUrl} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-3 rounded-xl border p-2 text-xs font-bold text-blue-700">{m.messageType?.toLowerCase().includes('image') ? <img src={m.attachmentUrl} alt="Artwork" className="h-14 w-14 rounded object-cover" /> : <span>📎</span>}<span>Customer file from WhatsApp · View</span></a>)}<form action={uploadStarkLeadArtwork} className="mt-4 rounded-xl border border-dashed p-3"><input type="hidden" name="lead_id" value={lead.id} /><input type="hidden" name="label" value="Customer artwork" /><input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.ai,.eps" className="block w-full text-xs" required /><button className="mt-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">+ Attach artwork</button></form></Card>;
  const quotesCard = <Card title="Quotes" action={<form action={createLeadQuoteDraftFromLead}><input type="hidden" name="lead_id" value={lead.id} /><input type="hidden" name="force_new" value="true" /><button className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white shadow-sm">+ New Quote</button></form>}>{quotes.length ? quotes.map((q: any) => <Link key={q.id} href={`/leads/${lead.id}/quote?quoteId=${q.id}&step=1`} className="mb-2 flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><b>{q.quote_number || 'Quote'} · {title(q.status)}</b><span className="text-emerald-700">Open →</span></Link>) : <p className="text-xs text-slate-500">No quotes created yet.</p>}</Card>;
  const filesCard = <Card title="Files">{media.length ? <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{media.slice().reverse().map((m: any) => <a key={m.id} href={m.attachmentUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border p-3 hover:bg-slate-50">{m.messageType?.toLowerCase().includes('image') ? <img src={m.attachmentUrl} alt="Attachment" className="h-12 w-12 rounded object-cover" /> : <span className="text-xl">📎</span>}<div className="min-w-0"><p className="truncate text-xs font-bold">{m.attachmentName || 'Customer attachment'}</p><p className="text-[10px] text-slate-400">{m.direction === 'inbound' ? 'Received from customer' : 'Sent / uploaded'} · {title(m.channel)}</p></div></a>)}</div> : <p className="text-xs text-slate-500">No files yet. WhatsApp attachments and uploaded artwork will appear here.</p>}</Card>;

  function tabContent() {
    if (tab === 'company') return <div className="grid gap-4 xl:grid-cols-2"><Card title="Company"><Row l="Company" v={lead.company_name} /><Row l="Country" v={lead.country} /><Row l="Market" v={data.linkedMarkets.map((m) => m.name).join(', ')} /><Row l="Source" v={lead.source_label || lead.source_type} /><Row l="Owner" v={owner} /><Row l="Lead Score" v={`${displayScore}/100`} /></Card><Card title="Commercial Context"><Row l="Pipeline" v={stageList.find((s: any) => s.id === lead.stage_id)?.name} /><Row l="Products" v={data.linkedProducts.map((p) => p.name).join(', ')} /><Row l="Quotes" v={quotes.length} /><Row l="Open Tasks" v={activeFollowUps.length} /><Row l="Files" v={media.length} /></Card></div>;
    if (tab === 'contacts') return <div className="grid gap-4 xl:grid-cols-[1.05fr_1fr]"><Card title="Primary Contact"><div className="mb-4 flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-slate-900 text-xs font-black text-white">{initials(lead.contact_name)}</div><div><p className="text-sm font-black text-slate-900">{lead.contact_name||'Primary contact'}</p><p className="text-[11px] text-slate-500">{(lead as any).job_title||'Buyer contact'}</p></div></div><Row l="Mobile" v={lead.phone} /><Row l="WhatsApp" v={lead.whatsapp_number || lead.phone} /><Row l="Email" v={lead.email} /><Row l="Social" v={(lead as any).social_handle} /></Card><Card title="Contact Actions"><p className="mb-4 text-xs leading-5 text-slate-500">Reach the buyer directly or open the complete communication history.</p><div className="grid gap-2 sm:grid-cols-3">{whatsapp?<ActionTile href={`https://wa.me/${String(whatsapp).replace(/\D/g,'')}`} icon="whatsapp" label="WhatsApp" value={String(whatsapp)} tone="green" newTab/>:null}{lead.email?<ActionTile href={`mailto:${encodeURIComponent(lead.email)}`} icon="envelope" label="Email" value={lead.email} tone="blue"/>:null}{phone?<ActionTile href={`tel:${String(phone).replace(/[^+0-9]/g,'')}`} icon="phone" label="Call" value={String(phone)} tone="violet"/>:null}</div><div className="mt-4 border-t border-slate-100 pt-4"><StarkCommunicationsLauncher {...communications}/></div></Card></div>;
    if (tab === 'requirements') return requirementCard;
    if (tab === 'quotes') return quotesCard;
    if (tab === 'tasks') return followUp;
    if (tab === 'notes') return <Card title="Notes"><div className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{lead.notes || 'No notes captured yet.'}</div></Card>;
    if (tab === 'communications') return <Card title="Customer Communications" action={<StarkCommunicationsLauncher {...communications} />}><p className="mb-4 text-xs text-slate-500">{communications.items.length} interactions retained with this lead, including pre-conversion Interakt history.</p><div className="grid gap-2 lg:grid-cols-2 xl:grid-cols-3">{recent.map((a: any) => <div key={a.id} className="flex gap-3 rounded-xl border border-slate-100 bg-slate-50/70 p-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${a.channel === 'whatsapp' ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'}`}>{a.channel === 'whatsapp' ? <FaIcon icon="whatsapp"/> : <FaIcon icon="envelope"/>}</span><div className="min-w-0"><p className="text-xs font-black">{a.direction === 'outbound' ? 'You' : a.actorName || lead.contact_name || lead.company_name} · {title(a.channel)}</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">{a.body || a.subject || 'Attachment'}</p></div></div>)}</div></Card>;
    if (tab === 'files') return filesCard;
    return <><div className="grid gap-4 xl:grid-cols-[1.05fr_1.5fr_1.15fr]"><Card title="Lead Information"><Row l="Company" v={lead.company_name} /><Row l="Contact" v={lead.contact_name} /><Row l="Designation" v={(lead as any).job_title} /><Row l="Mobile" v={lead.phone} /><Row l="Email" v={lead.email} /><Row l="Country" v={lead.country} /><Row l="Source" v={lead.source_label || lead.source_type} /><Row l="Owner" v={owner} /><Row l="Lead Score" v={`${displayScore}/100`} /></Card><Card title="Recent Customer Activity" action={<button type="button" onClick={() => setTab('communications')} className="text-[10px] font-bold text-blue-600">View all</button>}>{recent.map((a: any) => <div key={a.id} className="mb-3 flex gap-3 rounded-xl bg-slate-50 p-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${a.channel === 'whatsapp' ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'}`}>{a.channel === 'whatsapp' ? <FaIcon icon="whatsapp"/> : <FaIcon icon="envelope"/>}</span><div className="min-w-0"><p className="text-xs font-black">{a.direction === 'outbound' ? 'You' : a.actorName || lead.contact_name || lead.company_name} · {title(a.channel)}</p><p className="mt-1 truncate text-xs text-slate-500">{a.body || a.subject || 'Attachment'}</p></div></div>)}</Card>{followUp}</div><div className="grid gap-4 xl:grid-cols-[1.2fr_1fr_1fr]">{requirementCard}{quotesCard}<Card title="Files" action={<button type="button" onClick={() => setTab('files')} className="text-[10px] font-bold text-blue-600">View all</button>}>{media.length ? <div className="space-y-2">{media.slice().reverse().slice(0, 5).map((m: any) => <a key={m.id} href={m.attachmentUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border p-2"><span className="text-xl">📎</span><div><p className="text-xs font-bold">{m.attachmentName || 'Customer attachment'}</p><p className="text-[10px] text-slate-400">{m.direction === 'inbound' ? 'Received from customer' : 'Sent / uploaded'} · {title(m.channel)}</p></div></a>)}</div> : <p className="text-xs text-slate-500">No files yet.</p>}</Card></div></>;
  }

  return <div className="w-full max-w-none space-y-4 px-2 pb-24 sm:px-4 lg:px-6 xl:px-8 2xl:px-10"><div className="text-xs"><Link href={backHref} className="font-bold text-blue-600">Leads</Link> › Lead Detail</div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_16px_45px_rgba(15,23,42,.06)]"><div className="flex flex-wrap items-start justify-between gap-4 p-5"><div className="flex min-w-0 gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-slate-900 to-slate-700 font-black text-white shadow-lg">{initials(lead.company_name)}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-2xl font-black text-slate-950">{lead.company_name}</h1><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">Buyer</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">🇮🇳 {lead.country || 'India'}</span><span className="rounded-full border border-violet-100 bg-violet-50 px-2.5 py-1 text-[10px] font-black text-violet-700">Lead Score {displayScore}</span></div><p className="mt-2 text-xs text-slate-500">{lead.contact_name || 'Contact'} · {whatsapp || 'No mobile'} {lead.email ? ` · ${lead.email}` : ''}</p></div></div><div className="flex flex-wrap gap-2"><StarkCommunicationsLauncher {...communications}/></div></div><div className="grid overflow-x-auto border-t border-slate-100 px-5 py-4" style={{ gridTemplateColumns: `repeat(${Math.max(stageList.length, 1)},minmax(120px,1fr))` }}>{stageList.map((s: any, i: number) => <form key={s.id} action={moveCanonicalLeadStage} className="relative text-center"><input type="hidden" name="lead_id" value={lead.id} /><input type="hidden" name="stage_id" value={s.id} />{i < stageList.length - 1 ? <span className={`absolute left-1/2 top-4 h-0.5 w-full ${i < current ? 'bg-emerald-500' : 'bg-slate-200'}`} /> : null}<button className="relative z-10"><span className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full text-xs font-black ${i <= current ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-500'}`}>{i < current ? '✓' : i + 1}</span><span className="mt-2 block text-[10px] font-bold">{s.name}</span></button></form>)}</div><nav className="flex gap-1 overflow-x-auto border-t border-slate-100 px-3 text-xs font-bold text-slate-500 sm:px-5">{tabs.map((item) => <button key={item.key} type="button" onClick={() => setTab(item.key)} className={`whitespace-nowrap border-b-2 px-3 py-3 transition ${tab === item.key ? 'border-blue-600 text-blue-700' : 'border-transparent hover:border-slate-200 hover:text-slate-800'}`}>{item.label}{typeof item.count === 'number' ? <span className="ml-1 rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px]">{item.count}</span> : null}</button>)}</nav></section>{tabContent()}</div>;
}
