'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Requirement={id?:string;label:string;quantity:string;notes:string;familyId?:string|null;dimensionOptionId?:string|null;dimensions?:string;customWidthMm?:string;customHeightMm?:string;customGussetMm?:string;quantityMode?:'preset'|'custom'|'';source?:string;sourceContext?:Record<string,unknown>};
type Family={id:string;slug:string;name:string};
type DimensionOption={id:string;family_id:string;name:string;width_mm:string|number;height_mm:string|number;bottom_gusset_each_mm?:string|number|null;source:string};
type Note={id:string;message:string;occurred_at:string};
const QTY=['1,000','2,000','3,000','5,000','10,000','20,000','30,000','50,000'];
function RequirementRow({item,index,onChange,onRemove,families,dimensionOptions}:{item:Requirement;index:number;onChange:(r:Requirement)=>void;onRemove:()=>void;families:Family[];dimensionOptions:DimensionOption[]}){
  const inferredMode=item.quantityMode|| (QTY.includes(item.quantity)?'preset':item.quantity?'custom':'');
  const familyDimensions=dimensionOptions.filter(s=>s.family_id===item.familyId);
  const selectedDimension=familyDimensions.find(s=>s.id===item.dimensionOptionId);
  const customDimensions=item.dimensionOptionId==='custom';
  return <div className="rounded-xl border border-slate-200 bg-white p-4">
    <div className="flex items-center justify-between gap-3"><p className="text-xs font-bold text-slate-800">Requirement {index+1}</p><button type="button" onClick={onRemove} className="text-[10px] font-semibold text-rose-600">Remove</button></div>
    <div className="mt-3 grid gap-3 md:grid-cols-2">
      <label className="text-xs font-semibold text-slate-600">Packaging type / service family<select value={item.familyId||''} onChange={e=>{const family=families.find(f=>f.id===e.target.value);onChange({...item,familyId:e.target.value||null,label:family?.name||'',dimensionOptionId:null,dimensions:''})}} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="">Select packaging type</option>{families.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
      <label className="text-xs font-semibold text-slate-600">Dimensions<select value={item.dimensionOptionId||''} disabled={!item.familyId} onChange={e=>{const value=e.target.value;const s=familyDimensions.find(x=>x.id===value);if(value==='custom')onChange({...item,dimensionOptionId:'custom',dimensions:'',customWidthMm:item.customWidthMm||'',customHeightMm:item.customHeightMm||'',customGussetMm:item.customGussetMm||''});else onChange({...item,dimensionOptionId:value||null,dimensions:s?.name||'',customWidthMm:'',customHeightMm:'',customGussetMm:''})}} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm disabled:bg-slate-50 disabled:text-slate-400"><option value="">{!item.familyId?'Select packaging type first':'Select dimensions'}</option>{familyDimensions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}<option value="custom">Custom dimensions</option></select></label>
      <label className="text-xs font-semibold text-slate-600">Quantity<select value={inferredMode==='custom'?'custom':QTY.includes(item.quantity)?item.quantity:''} onChange={e=>{if(e.target.value==='custom')onChange({...item,quantityMode:'custom',quantity:QTY.includes(item.quantity)?'':item.quantity});else onChange({...item,quantityMode:e.target.value?'preset':'',quantity:e.target.value})}} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="">Select quantity</option>{QTY.map(q=><option key={q} value={q}>{q}</option>)}<option value="custom">Custom quantity</option></select></label>
      {selectedDimension?<p className="text-[10px] text-slate-500 md:col-span-2">Selected dimensions: {selectedDimension.name}</p>:null}
      {customDimensions?<div className="grid gap-3 md:col-span-2 md:grid-cols-3"><label className="text-xs font-semibold text-slate-600">Width (mm)<input type="number" min="1" step="0.1" value={item.customWidthMm||''} onChange={e=>onChange({...item,customWidthMm:e.target.value})} placeholder="e.g. 120" className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Height (mm)<input type="number" min="1" step="0.1" value={item.customHeightMm||''} onChange={e=>onChange({...item,customHeightMm:e.target.value})} placeholder="e.g. 180" className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Gusset (mm, optional)<input type="number" min="0" step="0.1" value={item.customGussetMm||''} onChange={e=>onChange({...item,customGussetMm:e.target.value})} placeholder="e.g. 40" className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label></div>:null}
      {inferredMode==='custom'?<label className="text-xs font-semibold text-slate-600 md:col-span-2">Custom quantity<input autoFocus value={item.quantity} onChange={e=>onChange({...item,quantityMode:'custom',quantity:e.target.value})} placeholder="e.g. 7,500 or 1,000 - 5,000" className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/></label>:null}
      <label className="text-xs font-semibold text-slate-600 md:col-span-2">Requirement notes<textarea value={item.notes} onChange={e=>onChange({...item,notes:e.target.value})} rows={3} placeholder="Add details, dimensions, print, delivery, special instructions…" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/></label>
    </div>
  </div>
}

export function StarkLeadRequirementsPanel({leadId,mode='edit',fallbackLabel='',fallbackQuantity='',fallbackDimensions='',fallbackDelivery=''}:{leadId:string;mode?:'edit'|'summary';fallbackLabel?:string;fallbackQuantity?:string;fallbackDimensions?:string;fallbackDelivery?:string}){
  const router=useRouter();const[items,setItems]=useState<Requirement[]>([]);const[families,setFamilies]=useState<Family[]>([]);const[dimensionOptions,setDimensionOptions]=useState<DimensionOption[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState('');
  async function load(){setLoading(true);try{const r=await fetch(`/api/leads/${leadId}/requirements`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load requirements.');setFamilies(p.families||[]);setDimensionOptions(p.dimensionOptions||[]);let next=(p.requirements||[]).map((x:Requirement)=>({...x,quantityMode:QTY.includes(x.quantity)?'preset':x.quantity?'custom':''}));if(!next.length&&fallbackLabel)next=[{label:fallbackLabel,quantity:fallbackQuantity||'',quantityMode:QTY.includes(fallbackQuantity)?'preset':fallbackQuantity?'custom':'',notes:'',dimensions:fallbackDimensions||'',sourceContext:{dimensions_print:fallbackDimensions||null,delivery_location:fallbackDelivery||null}}];setItems(next);}catch(e){setNotice(e instanceof Error?e.message:'Unable to load requirements.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[leadId]);
  async function save(){if(items.some(x=>!x.familyId||!x.dimensionOptionId||!x.quantity.trim()||(x.dimensionOptionId==='custom'&&(!(Number(x.customWidthMm)>0)||!(Number(x.customHeightMm)>0))))){setNotice('Each requirement needs a packaging type, dimensions, and quantity. Custom dimensions require width and height in mm.');return;}setSaving(true);setNotice('');try{const r=await fetch(`/api/leads/${leadId}/requirements`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({requirements:items})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Unable to save requirements.');setNotice('Requirements saved.');await load();router.refresh();}catch(e){setNotice(e instanceof Error?e.message:'Unable to save requirements.')}finally{setSaving(false)}}
  if(loading)return <div className="rounded-2xl border border-slate-200 bg-white p-4 text-xs text-slate-400">Loading requirements…</div>;
  if(mode==='summary')return <section className="rounded-2xl border border-[#dfe7f0] bg-white p-4 shadow-[0_8px_24px_rgba(15,35,60,.045)]"><div className="mb-3 flex items-center justify-between"><h3 className="text-[15px] font-bold text-[#10233d]">Requirements</h3></div>{items.length?<div className="space-y-3">{items.map((x,i)=><div key={x.id||i} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold text-slate-900">{x.label}</p><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{x.quantity||'Quantity to confirm'}</span></div>{x.dimensions?<p className="mt-1 text-[10px] font-semibold text-slate-500">Dimensions: {x.dimensions}</p>:null}{x.notes?<p className="mt-2 text-[11px] leading-5 text-slate-600">{x.notes}</p>:null}</div>)}</div>:<p className="text-xs text-slate-500">No requirements saved yet.</p>}</section>;
  return <section className="rounded-2xl border border-[#dfe7f0] bg-white p-4 shadow-[0_8px_24px_rgba(15,35,60,.045)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-[15px] font-bold text-[#10233d]">Requirements</h3><p className="mt-1 text-[11px] text-slate-500">Select a standard quantity or enter a custom quantity for each product/variant.</p></div><button type="button" onClick={()=>setItems([...items,{label:'',quantity:'',quantityMode:'',notes:'',familyId:null,dimensionOptionId:null,customWidthMm:'',customHeightMm:'',customGussetMm:'',sourceContext:{source:'canonical_lead_detail'}}])} className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">+ Add Requirement</button></div>{notice?<p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600">{notice}</p>:null}<div className="mt-4 space-y-3">{items.map((x,i)=><RequirementRow key={x.id||i} item={x} index={i} families={families} dimensionOptions={dimensionOptions} onChange={v=>setItems(items.map((r,j)=>j===i?v:r))} onRemove={()=>setItems(items.filter((_,j)=>j!==i))}/>)}</div>{!items.length?<button type="button" onClick={()=>setItems([{label:'',quantity:'',quantityMode:'',notes:'',familyId:null,dimensionOptionId:null,customWidthMm:'',customHeightMm:'',customGussetMm:'',sourceContext:{source:'canonical_lead_detail'}}])} className="mt-4 w-full rounded-xl border border-dashed border-slate-300 py-5 text-xs font-bold text-blue-600">+ Add first requirement</button>:null}<div className="mt-4 flex justify-end"><button type="button" disabled={saving} onClick={()=>void save()} className="rounded-lg bg-[#0B2440] px-4 py-2 text-xs font-bold text-white">{saving?'Saving…':'Save Requirements'}</button></div></section>
}

export function StarkLeadNotesPanel({leadId,systemNotes='',compact=false}:{leadId:string;systemNotes?:string|null;compact?:boolean}){
  const[notes,setNotes]=useState<Note[]>([]);const[text,setText]=useState('');const[saving,setSaving]=useState(false);const[notice,setNotice]=useState('');
  async function load(){const r=await fetch(`/api/leads/${leadId}/requirements`,{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.ok)setNotes(p.notes||[])}
  useEffect(()=>{void load()},[leadId]);
  async function add(){if(!text.trim())return;setSaving(true);setNotice('');const r=await fetch(`/api/leads/${leadId}/requirements`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note:text})});const p=await r.json().catch(()=>({}));if(!r.ok)setNotice(p.error||'Unable to add note.');else{setText('');await load()}setSaving(false)}
  if(compact)return <section className="rounded-2xl border border-[#dfe7f0] bg-white p-4 shadow-[0_8px_24px_rgba(15,35,60,.045)]"><div className="mb-3 flex items-center justify-between"><h3 className="text-[15px] font-bold text-[#10233d]">Sales Notes</h3><span className="text-[10px] text-slate-400">{notes.length}</span></div>{notes.length?<div className="space-y-2">{notes.slice(0,3).map(n=><div key={n.id} className="rounded-lg bg-amber-50/70 px-3 py-2"><p className="text-[11px] leading-5 text-slate-700">{n.message}</p><p className="mt-1 text-[9px] text-slate-400">{new Date(n.occurred_at).toLocaleString()}</p></div>)}</div>:<p className="text-xs text-slate-500">No additional sales notes.</p>}</section>;
  return <div className="space-y-4"><section className="rounded-2xl border border-[#dfe7f0] bg-white p-4"><h3 className="text-[15px] font-bold text-[#10233d]">Add Note</h3><textarea value={text} onChange={e=>setText(e.target.value)} rows={4} placeholder="Add a sales, customer, follow-up, or internal note…" className="mt-3 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm"/>{notice?<p className="mt-2 text-xs text-rose-600">{notice}</p>:null}<div className="mt-3 flex justify-end"><button type="button" disabled={saving||!text.trim()} onClick={()=>void add()} className="rounded-lg bg-[#0B2440] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{saving?'Adding…':'Add Note'}</button></div></section>{notes.length?<section className="rounded-2xl border border-[#dfe7f0] bg-white p-4"><h3 className="text-[15px] font-bold text-[#10233d]">Additional Notes</h3><div className="mt-3 space-y-2">{notes.map(n=><div key={n.id} className="rounded-xl bg-slate-50 p-3"><p className="whitespace-pre-wrap text-sm text-slate-700">{n.message}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(n.occurred_at).toLocaleString()}</p></div>)}</div></section>:null}<section className="rounded-2xl border border-[#dfe7f0] bg-white p-4"><h3 className="text-[15px] font-bold text-[#10233d]">Imported / System Notes</h3><div className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{systemNotes||'No imported notes.'}</div></section></div>;
}
