'use client';

import { useMemo, useState } from 'react';
import { FaIcon } from '@/components/ui/fa-icon';
import { createStarkLeadFollowUp, completeStarkLeadFollowUp } from './stark-lead-actions';

type FollowUp = { id: string; status?: string | null; notes?: string | null; scheduled_at?: string | null };
type Props = { leadId: string; contactName?: string | null; companyName: string; requirement?: string | null; hasArtwork: boolean; hasQuote: boolean; followUps: FollowUp[]; };
type Channel = 'whatsapp' | 'email' | 'call';

const when = (v?: string | null) => { if (!v) return 'No date'; const d = new Date(v); return Number.isNaN(d.getTime()) ? 'No date' : d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); };
function parseNote(v?: string | null){const raw=String(v||'Follow up with buyer');const m=raw.match(/^\[(WhatsApp|Email|Call)\]\s*(.*)$/i);return{channel:(m?.[1]||'Follow-up'),message:m?.[2]||raw};}

export default function StarkFollowUpComposer({leadId,contactName,companyName,requirement,hasArtwork,hasQuote,followUps}:Props){
 const [channel,setChannel]=useState<Channel>('whatsapp');
 const name=contactName||'there';
 const suggestions=useMemo(()=>{
   if(hasQuote)return [`Hi ${name}, just following up on the pricing we shared. Please let me know your expected quantity and if there is anything we should adjust to move this forward.`,`Hi ${name}, checking in on the quote shared for ${requirement||'your packaging requirement'}. Happy to clarify pricing, MOQ or delivery timing.`,`Hi ${name}, wanted to see if you had a chance to review our quote. What would help you take the next step?`];
   if(hasArtwork)return [`Hi ${name}, thanks for sharing the artwork. We are reviewing it for ${requirement||'your packaging'} and can now confirm the right structure, MOQ and pricing.`,`Hi ${name}, we have the artwork/reference. Please confirm the final quantity so we can prepare accurate pricing.`,`Hi ${name}, your artwork is with our team. I wanted to confirm quantity and any final print requirements before we price it.`];
   return [`Hi ${name}, following up on your ${requirement||'packaging requirement'}. If you share the artwork/design and expected quantity, we can recommend the right structure and pricing.`,`Hi ${name}, I wanted to follow up on your packaging inquiry. Do you already have artwork ready, or would you like our team to help?`,`Hi ${name}, thanks for connecting with ${companyName}. Please share the quantity and artwork status and I can help with MOQ and pricing.`];
 },[name,companyName,requirement,hasArtwork,hasQuote]);
 const [message,setMessage]=useState(suggestions[0]);
 const active=followUps.filter(f=>f.status!=='completed');
 const channelStyle:Record<Channel,string>={whatsapp:'border-emerald-200 bg-emerald-50 text-emerald-700',email:'border-blue-200 bg-blue-50 text-blue-700',call:'border-violet-200 bg-violet-50 text-violet-700'};
 const icon:Record<Channel,string>={whatsapp:'whatsapp',email:'envelope',call:'phone'};
 return <section id="tasks" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_35px_rgba(15,23,42,.06)]">
   <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-violet-50 text-violet-700">✦</span><h3 className="text-sm font-black text-slate-950">Smart Follow-up</h3></div><p className="mt-1 text-[11px] text-slate-500">Setu Guru suggests the message. You choose the channel and timing.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{active.length} scheduled</span></div>
   {active.length?<div className="space-y-2 border-b border-slate-100 bg-slate-50/60 p-4">{active.slice(0,4).map(f=>{const p=parseNote(f.notes);return <form key={f.id} action={completeStarkLeadFollowUp} className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><input type="hidden" name="lead_id" value={leadId}/><input type="hidden" name="follow_up_id" value={f.id}/><button title="Mark complete" className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-emerald-200 bg-emerald-50 text-xs font-black text-emerald-700 hover:bg-emerald-100">✓</button><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-black uppercase tracking-wide text-slate-600">{p.channel}</span><span className="text-[10px] font-bold text-slate-400">{when(f.scheduled_at)}</span></div><p className="mt-1.5 text-xs font-semibold leading-5 text-slate-700">{p.message}</p></div></form>})}</div>:null}
   <form action={createStarkLeadFollowUp} className="p-5"><input type="hidden" name="lead_id" value={leadId}/><input type="hidden" name="channel" value={channel}/><div className="mb-3 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">How will we follow up?</div><div className="grid grid-cols-3 gap-2">{(['whatsapp','email','call'] as Channel[]).map(c=><button key={c} type="button" onClick={()=>setChannel(c)} className={`flex items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-black transition ${channel===c?channelStyle[c]:'border-slate-200 bg-white text-slate-500 hover:bg-slate-50'}`}><FaIcon icon={icon[c]} fixedWidth/>{c==='whatsapp'?'WhatsApp':c==='email'?'Email':'Call'}</button>)}</div>
   <div className="mt-4 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.14em] text-violet-600">✦ Setu Guru suggested message</span><span className="text-[10px] text-slate-400">Editable before scheduling</span></div><div className="mt-2 flex gap-2 overflow-x-auto pb-1">{suggestions.map((s,i)=><button key={s} type="button" onClick={()=>setMessage(s)} className={`min-w-[190px] rounded-xl border p-2.5 text-left text-[10px] leading-4 transition ${message===s?'border-violet-300 bg-violet-50 text-violet-900':'border-slate-200 bg-white text-slate-600 hover:border-violet-200'}`}><b className="mb-1 block">Option {i+1}</b>{s}</button>)}</div><textarea name="message" value={message} onChange={e=>setMessage(e.target.value)} rows={4} className="mt-3 w-full resize-none rounded-xl border border-slate-200 bg-slate-50/50 p-3 text-xs leading-5 text-slate-800 outline-none focus:border-violet-300 focus:ring-2 focus:ring-violet-100" required/><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto]"><div><label className="mb-1 block text-[10px] font-black uppercase tracking-wide text-slate-400">When</label><input name="scheduled_at" type="datetime-local" className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700" required/></div><button className="self-end rounded-xl bg-slate-950 px-5 py-3 text-xs font-black text-white shadow-lg shadow-slate-200 transition hover:bg-slate-800">Schedule {channel==='whatsapp'?'WhatsApp':channel==='email'?'Email':'Call'} follow-up</button></div><p className="mt-2 text-[10px] text-slate-400">Scheduling creates the sales task. It does not automatically contact the customer.</p></form>
 </section>;
}
