'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createAdminSupabaseClient } from '@/lib/supabase/admin';
import { createClient } from '@/lib/supabase/server';
import { requireWorkspace } from '@/lib/workspace/auth';

const STARK='b97913cb-3b95-4247-8ced-ffdc0d392d2a';
const clean=(v:FormDataEntryValue|null)=>String(v??'').trim();
async function ctx(){const w=await requireWorkspace();if(!w.organization||!w.user||w.organization.id!==STARK)throw new Error('Stark Packmate workspace required.');return w;}
function go(id:string,saved:string,hash:string){redirect(`/leads/${id}?saved=${saved}#${hash}`);}

export async function createStarkLeadFollowUp(formData:FormData){const w=await ctx(),leadId=clean(formData.get('lead_id')),scheduled=clean(formData.get('scheduled_at')),channelRaw=clean(formData.get('channel')).toLowerCase(),message=clean(formData.get('message'))||clean(formData.get('notes'));if(!leadId||!scheduled)return;const channel=channelRaw==='email'?'Email':channelRaw==='call'?'Call':'WhatsApp';const date=new Date(scheduled);if(Number.isNaN(date.getTime()))return;const notes=`[${channel}] ${message||`Follow up with buyer via ${channel}`}`;const db=(await createClient()) as any;const now=new Date().toISOString();await db.from('lead_follow_ups').insert({organization_id:STARK,lead_id:leadId,assigned_user_id:w.user!.id,scheduled_at:date.toISOString(),status:'scheduled',notes,created_by:w.user!.id});await db.from('leads').update({next_follow_up_at:date.toISOString(),updated_by:w.user!.id}).eq('organization_id',STARK).eq('id',leadId);await db.from('lead_activities').insert({organization_id:STARK,lead_id:leadId,actor_user_id:w.user!.id,kind:'follow_up_scheduled',message:`${channel} follow-up scheduled: ${message||'Follow up with buyer'}`,occurred_at:now});revalidatePath(`/leads/${leadId}`);go(leadId,'follow-up','tasks');}

export async function completeStarkLeadFollowUp(formData:FormData){const w=await ctx(),leadId=clean(formData.get('lead_id')),id=clean(formData.get('follow_up_id'));if(!leadId||!id)return;const db=(await createClient()) as any,now=new Date().toISOString();await db.from('lead_follow_ups').update({status:'completed',completed_at:now}).eq('organization_id',STARK).eq('lead_id',leadId).eq('id',id);const{data:next}=await db.from('lead_follow_ups').select('scheduled_at').eq('organization_id',STARK).eq('lead_id',leadId).eq('status','scheduled').neq('id',id).order('scheduled_at',{ascending:true}).limit(1).maybeSingle();await db.from('leads').update({next_follow_up_at:next?.scheduled_at??null,updated_by:w.user!.id}).eq('organization_id',STARK).eq('id',leadId);await db.from('lead_activities').insert({organization_id:STARK,lead_id:leadId,actor_user_id:w.user!.id,kind:'follow_up_completed',message:'Follow-up marked completed.',occurred_at:now});revalidatePath(`/leads/${leadId}`);go(leadId,'follow-up','tasks');}

export async function uploadStarkLeadArtwork(formData:FormData){const w=await ctx(),leadId=clean(formData.get('lead_id')),label=clean(formData.get('label'))||'Customer artwork',file=formData.get('file');if(!leadId||!(file instanceof File)||!file.size)return;const allowed=new Set(['application/pdf','image/png','image/jpeg','image/webp','application/postscript','application/illustrator']);if(file.size>20*1024*1024)throw new Error('Artwork must be 20MB or smaller.');if(file.type&&!allowed.has(file.type))throw new Error('Upload PDF, PNG, JPG, WEBP, AI or EPS artwork.');const admin=createAdminSupabaseClient() as any;if(!admin)throw new Error('File storage is unavailable.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)||'artwork';const path=`lead-artwork/${STARK}/${leadId}/${Date.now()}-${safe}`;const bytes=new Uint8Array(await file.arrayBuffer());const{error}=await admin.storage.from('lead-attachments').upload(path,bytes,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error;const{data:signed}=await admin.storage.from('lead-attachments').createSignedUrl(path,60*60*24*7);const now=new Date().toISOString();await admin.from('communications').insert({organization_id:STARK,lead_id:leadId,related_entity:'lead',related_id:leadId,communication_type:'attachment',direction:'internal',channel:'note',subject:label,body:`Artwork uploaded: ${file.name}`,status:'sent',sent_at:now,created_by:w.user!.id,metadata:{kind:'artwork',file_path:path,file_name:file.name,mime_type:file.type,size:file.size,preview_url:signed?.signedUrl??null,source:'lead_detail_upload'}});await admin.from('lead_activities').insert({organization_id:STARK,lead_id:leadId,actor_user_id:w.user!.id,kind:'artwork_uploaded',message:`Artwork uploaded: ${file.name}`,occurred_at:now});revalidatePath(`/leads/${leadId}`);go(leadId,'artwork','files');}
