import Link from 'next/link';
import type { LeadProfileData } from '@/lib/queries/leads';
import { createLeadQuoteDraftFromLead } from '@/features/quotes/server/lead-draft-actions';
import { moveCanonicalLeadStage, reassignCanonicalLeadOwner } from './actions';
import { StarkCommunicationsLauncher } from './StarkCommunicationsDrawer';

type TeamMember={id:string;name:string};
type CommProps=React.ComponentProps<typeof StarkCommunicationsLauncher>;
type Props={data:LeadProfileData;canReassignOwner:boolean;teamMembers:TeamMember[];backHref:string;communications:CommProps};
const norm=(v?:string|null)=>String(v||'').trim().toLowerCase();
const initials=(v?:string|null)=>String(v||'Lead').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'LD';
const title=(v?:string|null)=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const phone=(v?:string|null)=>String(v||'').replace(/[^+\d]/g,'');
const when=(v?:string|null)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});};
function owner(data:LeadProfileData,members:TeamMember[]){return members.find(m=>m.id===data.lead?.owner_user_id)?.name||data.profiles.find((p:any)=>p.id===data.lead?.owner_user_id)?.full_name||'Unassigned';}
function score(data:LeadProfileData){let s=25;if(data.lead?.email||data.lead?.phone)s+=15;if(data.linkedProducts.length)s+=20;if(data.linkedMarkets.length)s+=15;if(data.quotes.length)s+=15;if(data.followUps.length)s+=10;return Math.min(100,s);}
function stages(data:LeadProfileData){const current=data.stages.find((s:any)=>s.id===data.lead?.stage_id);const pid=current?.pipeline_id||data.lead?.pipeline_id;return data.stages.filter((s:any)=>!pid||s.pipeline_id===pid).sort((a:any,b:any)=>(a.sort_order??0)-(b.sort_order??0));}
function Card({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-black text-slate-900">{title}</h3>{action}</div>{children}</section>}
function Row({label,value}:{label:string;value:React.ReactNode}){return <div className="grid grid-cols-[115px_1fr] gap-3 border-b border-slate-100 py-2 text-xs last:border-0"><span className="text-slate-500">{label}</span><span className="font-semibold text-slate-800">{value||'—'}</span></div>}
function StageStrip({data}:{data:LeadProfileData}){const list=stages(data),current=list.findIndex((s:any)=>s.id===data.lead?.stage_id);return <div className="grid min-w-[560px] gap-1" style={{gridTemplateColumns:`repeat(${Math.max(list.length,1)},minmax(0,1fr))`}}>{list.map((s:any,i:number)=><form key={s.id} action={moveCanonicalLeadStage} className="relative text-center"><input type="hidden" name="lead_id" value={data.lead!.id}/><input type="hidden" name="stage_id" value={s.id}/>{i<list.length-1?<span className={`absolute left-1/2 top-4 h-0.5 w-full ${i<current?'bg-emerald-500':'bg-slate-200'}`}/>:null}<button className="relative z-10 w-full"><span className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full text-xs font-black ${i<=current?'bg-emerald-600 text-white':'bg-slate-100 text-slate-500'}`}>{i<current?'✓':i+1}</span><span className={`mt-2 block text-[10px] font-bold ${i===current?'text-emerald-700':'text-slate-500'}`}>{s.name}</span></button></form>)}</div>}

export default function StarkLeadDetailApproved({data,canReassignOwner,teamMembers,backHref,communications}:Props){const lead=data.lead!,quotes=[...(data.quotes||[])].sort((a:any,b:any)=>String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||''))),active=quotes[0],members=teamMembers.length?teamMembers:data.profiles.map((p:any)=>({id:p.id,name:p.full_name||p.username||'Team member'}));const whatsapp=lead.whatsapp_number||lead.phone;const requirement=(lead as any).products_or_needs||(lead as any).main_product_category||data.linkedProducts.map(p=>p.name).join(', ')||'Requirement not captured yet';const recent=(data.communications||[]).slice(0,4);return <div className="mx-auto max-w-[1560px] space-y-4 pb-28">
 <div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Link href={backHref} className="text-blue-600">Leads</Link><span>›</span><span>Lead Detail</span></div>
 <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4 p-5"><div className="flex min-w-0 gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-lg font-black text-slate-800">{initials(lead.company_name)}</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black text-slate-950">{lead.company_name}</h1><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">Buyer</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">🇮🇳 {lead.country||'Market'}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">High ICP Fit ({score(data)})</span></div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500"><span>{lead.contact_name||'Contact not captured'}</span>{(lead as any).job_title?<><span>·</span><span>{(lead as any).job_title}</span></>:null}{whatsapp?<><span>·</span><span>{whatsapp}</span></>:null}{lead.email?<><span>·</span><span>{lead.email}</span></>:null}</div></div></div><div className="flex flex-wrap gap-2"><StarkCommunicationsLauncher {...communications}/>{whatsapp?<a href={`https://wa.me/${phone(whatsapp).replace('+','')}`} className="inline-flex h-10 items-center rounded-xl border border-emerald-200 bg-white px-4 text-xs font-bold text-emerald-700">● WhatsApp</a>:null}{lead.email?<a href={`mailto:${lead.email}`} className="inline-flex h-10 items-center rounded-xl border border-blue-200 bg-white px-4 text-xs font-bold text-blue-700">✉ Email</a>:null}<a href="#edit-lead" className="inline-flex h-10 items-center rounded-xl bg-emerald-600 px-5 text-xs font-black text-white">Open</a></div></div><div className="overflow-x-auto border-t border-slate-100 px-5 py-4"><StageStrip data={data}/></div>
 <nav className="flex gap-5 overflow-x-auto border-t border-slate-100 px-5 text-xs font-bold text-slate-500"><a href="#overview" className="border-b-2 border-blue-600 py-3 text-blue-700">Overview</a><a href="#company" className="py-3">Company</a><a href="#contacts" className="py-3">Contacts</a><a href="#requirements" className="py-3">Requirements</a><a href="#quotes" className="py-3">Quotes <span className="rounded-full bg-slate-100 px-1.5">{quotes.length}</span></a><a href="#tasks" className="py-3">Tasks</a><a href="#notes" className="py-3">Notes</a><button onClick={undefined} className="py-3">Communications <span className="rounded-full bg-blue-100 px-1.5 text-blue-700">{communications.items.length}</span></button><a href="#files" className="py-3">Files</a></nav></section>
 <div id="overview" className="grid gap-4 xl:grid-cols-3"><Card title="Lead Information" action={<a href="#edit-lead" className="rounded-lg border px-2 py-1 text-[10px] font-bold">✎ Edit</a>}><Row label="Company" value={lead.company_name}/><Row label="Contact" value={lead.contact_name}/><Row label="Designation" value={(lead as any).job_title}/><Row label="Mobile" value={lead.phone}/><Row label="Email" value={lead.email}/><Row label="Country / Market" value={`${lead.country||'—'} / ${data.linkedMarkets.map(m=>m.name).join(', ')||'—'}`}/><Row label="Source" value={lead.source_label||lead.source_type}/><Row label="Owner" value={owner(data,members)}/><Row label="ICP Fit" value={<span className="text-emerald-700">{score(data)}/100 · Ideal Fit</span>}/><Row label="Created" value={when((lead as any).created_at)}/></Card>
 <Card title="Recent Activity" action={<button className="rounded-lg border px-2 py-1 text-[10px] font-bold">View all</button>}><div className="space-y-3">{recent.length?recent.map((a:any)=><div key={a.id} className="flex gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-blue-600">{norm(a.channel)==='whatsapp'?'●':'✉'}</span><div className="min-w-0"><p className="text-xs font-black text-slate-800">{title(a.channel)} {a.direction?`(${title(a.direction)})`:''}</p><p className="truncate text-xs text-slate-500">{a.subject||a.body||a.summary||'Activity recorded'}</p></div></div>):<p className="text-xs text-slate-500">No recent activity recorded.</p>}</div></Card>
 <Card title="Next Steps" action={<Link href="/tasks" className="rounded-lg border px-2 py-1 text-[10px] font-bold">Add Task</Link>}><div className="space-y-3">{data.followUps.slice(0,4).map((f:any)=><div key={f.id} className="flex gap-2 text-xs"><span className="mt-0.5 h-4 w-4 rounded border border-slate-300"/><div><p className="font-bold text-slate-700">{f.title||f.follow_up_for||f.notes||'Follow up with buyer'}</p><p className="mt-1 text-slate-400">{when(f.due_at||f.scheduled_at)}</p></div></div>)}{!data.followUps.length?<p className="text-xs text-slate-500">No next step scheduled yet.</p>:null}<Link href="/tasks" className="inline-flex pt-2 text-xs font-bold text-blue-600">+ Add new task</Link></div></Card></div>
 <div className="grid gap-4 xl:grid-cols-3"><Card title="Requirement"><p className="text-sm font-bold text-slate-800">{requirement}</p><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">{lead.notes||'Add quantity, artwork, MOQ and commercial requirements as they are learned.'}</div></Card><Card title="Quotes" action={<Link href="#quotes" className="text-[10px] font-bold text-blue-600">View all</Link>}>{active?<Link href={`/leads/${lead.id}/quote?quoteId=${active.id}&step=1`} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-xs font-black text-slate-900">{active.quote_number||'Quote'}</p><p className="mt-1 text-[11px] text-slate-500">{title(active.status)}</p></div><span className="text-xs font-bold text-emerald-700">Open →</span></Link>:<form action={createLeadQuoteDraftFromLead}><input type="hidden" name="lead_id" value={lead.id}/><input type="hidden" name="force_new" value="true"/><button className="text-xs font-bold text-blue-600">+ Create first quote</button></form>}</Card><Card title="Files" action={<span className="text-[10px] text-slate-400">Persistent with lead</span>}><p className="text-xs leading-5 text-slate-500">WhatsApp and email attachments remain linked to the communication history. CRM document uploads will appear here as the unified Files workspace is enabled.</p></Card></div>
 <div id="quotes" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h3 className="text-sm font-black">Quotes on this Lead</h3><form action={createLeadQuoteDraftFromLead}><input type="hidden" name="lead_id" value={lead.id}/><input type="hidden" name="force_new" value="true"/><button className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white">+ New Quote</button></form></div><div className="mt-3 grid gap-2 md:grid-cols-2">{quotes.map((q:any)=><Link key={q.id} href={`/leads/${lead.id}/quote?quoteId=${q.id}&step=1`} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-xs font-black">{q.quote_number||'Quote'} · {title(q.status)}</p></Link>)}</div></div>
 {canReassignOwner?<form action={reassignCanonicalLeadOwner} className="hidden"><input name="lead_id" value={lead.id} readOnly/></form>:null}
 </div>;
}
