import { money } from '@/lib/trade-events/analytics';
import { buildTradeEventHistoryRows } from '@/lib/trade-events/history';
import type { TradeEventsCommandCenterData } from '@/lib/trade-events/query';

export function TradeEventsHistoryComparison({ data }: { data: TradeEventsCommandCenterData }) {
  const rows = buildTradeEventHistoryRows(data);
  if (!rows.length) return <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Event history</p><h2 className="mt-1 text-xl font-black">No completed events to compare yet</h2><p className="mt-2 text-sm text-slate-500">Verified outcomes will become evidence for future Setu Guru recommendations.</p></section>;
  return <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Event history</p><h2 className="mt-1 text-xl font-black">Compare completed shows</h2></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-black uppercase text-slate-500"><tr><th className="px-5 py-3">Event</th><th>Captured</th><th>Qualified</th><th>Quotes</th><th>Orders</th><th>Revenue</th><th className="px-5">ROI</th></tr></thead><tbody>{rows.map((row) => <tr key={row.event.id} className="border-t border-slate-100"><td className="px-5 py-4 font-black">{row.event.name}</td><td>{row.captured}</td><td>{row.qualified}</td><td>{row.outcome.quoteCount}</td><td>{row.outcome.orderCount}</td><td>{row.outcome.revenueCurrency ? money(row.outcome.wonRevenue, row.outcome.revenueCurrency) : row.outcome.wonRevenue ? 'Mixed currency' : '—'}</td><td className="px-5 font-black text-emerald-700">{row.outcome.roiMultiple == null ? '—' : `${row.outcome.roiMultiple.toFixed(2)}×`}</td></tr>)}</tbody></table></div></section>;
}
