import Link from 'next/link';
import { hasSupabaseEnv } from '@/lib/env';
import { createClient } from '@/lib/supabase/server';
import { requireAdminWorkspace } from '@/lib/workspace/auth';
import { getSettingsListsData } from '@/lib/queries/settings-lists';
import { getAuditEvents, type AuditEventType } from '@/lib/auditLog';
import { getAuditEventCategory, getAuditEventLabel, getAuditEventSummary } from '@/lib/adminAuditEvents';
import { StateMessage } from '@/components/ui/state-message';
import { formatDateTime } from '@/lib/utils';
import { saveAdminSettingsListItem, moveAdminSettingsListItem } from '@/features/settings/server/actions';
import { inviteMember, sendInvitation, resendInvitation, revokeInvitation, updateMemberRole, removeMember, reactivateMember, updateApprovalThreshold } from '@/features/admin/server/actions';

type SearchParams = Record<string, string | string[] | undefined>;
type SectionKey = 'organization' | 'team' | 'invitations' | 'markets' | 'categories' | 'stages' | 'pipelines' | 'trade-events' | 'audit' | 'ai' | 'security';
type RefItem = { id: string; name: string; sort_order: number | null; is_active: boolean; [key: string]: unknown };

const NAV: Array<[SectionKey, string]> = [['organization','Organization'],['team','Team members'],['invitations','Invitations'],['markets','Markets'],['categories','Categories'],['stages','Stages & next steps'],['pipelines','Pipelines'],['trade-events','Trade events'],['audit','Audit log'],['ai','AI analytics'],['security','Security & roles']];
const ALIASES: Record<string, SectionKey> = { org:'organization', organization:'organization', users:'team', team:'team', members:'team', invites:'invitations', invitations:'invitations', markets:'markets', countries:'markets', categories:'categories', 'product-categories':'categories', stages:'stages', 'next-steps':'stages', pipelines:'pipelines', events:'trade-events', 'trade-events':'trade-events', audit:'audit', ai:'ai', analytics:'ai', security:'security', roles:'security' };
const ACCESS_EVENTS: AuditEventType[] = ['invitation_created','invitation_sent','invitation_resent','invitation_updated','invitation_revoked','invitation_accepted','invitation_failed','role_changed','membership_reactivated','membership_deactivated','membership_removed','password_reset_requested'];
const CATALOG_EVENTS: AuditEventType[] = ['settings_list_item_saved','settings_list_item_deleted','pricing_shared','pricing_sent','pricing_exported','product_created','product_updated','product_deleted'];

function first(v: string | string[] | undefined) { return Array.isArray(v) ? v[0] : v; }
function sectionFrom(params?: SearchParams): SectionKey { return ALIASES[String(first(params?.section) ?? '').trim()] ?? 'organization'; }
function categoryFrom(params?: SearchParams) { const value = String(first(params?.category) ?? 'all'); return value === 'access' || value === 'catalog' || value === 'workflow' ? value : 'all'; }
function roleLabel(value?: string | null) { return String(value ?? 'member').replace(/[_-]/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase()); }
function activeCount(rows: any[]) { return rows.filter((row) => row.is_active !== false).length; }
function snapshotHref(data: unknown) { return `data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(data, null, 2))}`; }
function cardClasses() { return 'rounded-[16px] border border-[var(--border)] bg-white p-5 shadow-sm'; }
function primaryCta(section: SectionKey) { return ({ organization:'Save policy', team:'Edit role', invitations:'Send invite', markets:'Add market', categories:'Add category', stages:'Add next step', pipelines:'Review pipelines', 'trade-events':'Add event', audit:'Export log', ai:'Review guardrails', security:'Save security' } as Record<SectionKey,string>)[section]; }

function LeftNav({ active }: { active: SectionKey }) {
  return <aside className="admin-left-nav"><div className="mb-3 px-3"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-slate-400">Workspace Control</p><p className="mt-1 text-xs text-slate-500">Admin + Settings</p></div>{NAV.map(([key,label]) => <Link key={key} href={`/admin?section=${key}`} className={`admin-ln-item ${active === key ? 'active' : ''}`}><span>{label}</span>{key === 'security' ? <span className="admin-ln-badge">Fix</span> : null}</Link>)}</aside>;
}
function Card({ title, eyebrow, description, children, actions }: { title: string; eyebrow?: string; description?: string; children?: React.ReactNode; actions?: React.ReactNode }) { return <section className={cardClasses()}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-slate-400">{eyebrow ?? 'Workspace'}</p><h2 className="mt-1 text-lg font-extrabold tracking-[-0.02em] text-slate-950">{title}</h2>{description ? <p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{description}</p> : null}</div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</div>{children ? <div className="mt-5">{children}</div> : null}</section>; }
function Stat({ label, value, helper }: { label: string; value: React.ReactNode; helper?: string }) { return <div className="rounded-[16px] border border-[var(--border)] bg-white p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}</p>{helper ? <p className="mt-1 text-xs text-slate-500">{helper}</p> : null}</div>; }
function GovernanceBanner({ gaps }: { gaps: Array<{ label: string; href: string }> }) { return <div className="rounded-[16px] border border-amber-200 bg-amber-50 px-5 py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-amber-600">Governance banner</p><h3 className="mt-1 text-sm font-extrabold text-slate-950">Visible across every Admin section.</h3></div><div className="flex flex-wrap gap-2">{gaps.length ? gaps.map((gap) => <Link key={gap.label} href={gap.href} className="rounded-full border border-amber-200 bg-white px-3 py-1 text-xs font-bold text-amber-700 hover:bg-amber-100">{gap.label}</Link>) : <span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">No critical governance gaps</span>}</div></div></div>; }

function RefList({ title, table, items, extra }: { title: string; table: string; items: RefItem[]; extra?: { name: string; placeholder: string } }) {
  return <Card title={title} eyebrow="Reference lists" description="Inline add/edit with sort_order controls. ↑/↓ persists reorder without a drawer."><div className="space-y-2"><form action={saveAdminSettingsListItem} id={`${table}-primary-action`} className="grid gap-2 rounded-[16px] border border-dashed border-slate-200 bg-slate-50 p-3 md:grid-cols-[1.4fr_0.8fr_0.5fr_auto]"><input type="hidden" name="table" value={table}/><input className="admin-input" name="name" placeholder={`New ${title.toLowerCase()} name`} required />{extra ? <input className="admin-input" name={extra.name} placeholder={extra.placeholder}/> : <span/>}<input className="admin-input" type="number" name="sort_order" defaultValue={items.length + 1}/><button className="rounded-[6px] bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">＋ Add</button></form>{items.map((item, index) => <form key={item.id} action={saveAdminSettingsListItem} className="grid gap-2 rounded-[12px] border border-slate-100 bg-white p-3 md:grid-cols-[42px_1.4fr_0.8fr_0.5fr_80px_auto]"><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={item.id}/><div className="flex gap-1"><button formAction={moveAdminSettingsListItem} name="direction" value="up" className="rounded border px-2 text-xs" disabled={index===0}>↑</button><button formAction={moveAdminSettingsListItem} name="direction" value="down" className="rounded border px-2 text-xs" disabled={index===items.length-1}>↓</button></div><input className="admin-input" name="name" defaultValue={item.name} required />{extra ? <input className="admin-input" name={extra.name} defaultValue={String(item[extra.name] ?? '')}/> : <span/>}<input className="admin-input" type="number" name="sort_order" defaultValue={item.sort_order ?? index + 1}/><label className="flex items-center gap-2 text-xs font-semibold text-slate-500"><input type="checkbox" name="is_active" defaultChecked={item.is_active !== false}/> Active</label><button className="rounded-[6px] border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700">Save</button></form>)}</div></Card>;
}

function Team({ members, roles }: { members: any[]; roles: any[] }) { return <Card title="Team members" eyebrow="Access" description="Role edit panel is inline in the unified workspace." actions={<Link href="/admin?section=audit&category=access" className="admin-ghost">Access audit →</Link>}><div id="team-primary-action" className="space-y-3">{members.map((member) => { const profile = member.profiles ?? {}; return <form key={member.id} action={updateMemberRole} className="grid gap-3 rounded-[12px] border border-slate-100 bg-slate-50 p-3 lg:grid-cols-[1fr_180px_auto_auto]"><input type="hidden" name="membership_id" value={member.id}/><input type="hidden" name="return_path" value="/admin?section=team"/><div><p className="text-sm font-bold text-slate-900">{profile.full_name ?? profile.username ?? profile.email ?? 'Workspace member'}</p><p className="text-xs text-slate-500">{profile.email ?? member.user_id} · {member.is_active ? 'Active' : 'Disabled'}</p></div><select name="role_id" defaultValue={member.user_roles?.[0]?.role_id ?? ''} className="admin-input">{roles.map((role) => <option key={role.id} value={role.id}>{roleLabel(role.name)}</option>)}</select><button className="rounded-[6px] bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Save role</button>{member.is_active ? <button formAction={removeMember} className="rounded-[6px] border border-rose-200 bg-white px-3 py-2 text-xs font-bold text-rose-600">Deactivate</button> : <button formAction={reactivateMember} className="rounded-[6px] border border-emerald-200 bg-white px-3 py-2 text-xs font-bold text-emerald-700">Reactivate</button>}</form>; })}</div></Card>; }
function Invites({ invitations, roles }: { invitations: any[]; roles: any[] }) { return <Card title="Invitations" eyebrow="Access" description="Invite member inline, then send, resend, or revoke." actions={<Link href="/admin?section=audit&category=access" className="admin-ghost">Access audit →</Link>}><form action={inviteMember} id="invitations-primary-action" className="mb-4 grid gap-2 rounded-[16px] border border-dashed border-slate-200 bg-slate-50 p-3 md:grid-cols-[1.4fr_180px_110px_auto]"><input type="hidden" name="return_path" value="/admin?section=invitations"/><input className="admin-input" type="email" name="email" placeholder="member@company.com" required/><select name="role_id" className="admin-input">{roles.map((role) => <option key={role.id} value={role.id}>{roleLabel(role.name)}</option>)}</select><input className="admin-input" type="number" name="expires_in_days" defaultValue={7}/><button className="rounded-[6px] bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Send invite</button></form><div className="space-y-2">{invitations.map((invite) => <form key={invite.id} action={sendInvitation} className="grid gap-3 rounded-[12px] border border-slate-100 bg-white p-3 lg:grid-cols-[1fr_110px_auto_auto]"><input type="hidden" name="invitation_id" value={invite.id}/><input type="hidden" name="return_path" value="/admin?section=invitations"/><div><p className="text-sm font-bold text-slate-900">{invite.email}</p><p className="text-xs text-slate-500">{roleLabel(invite.roles?.name)} · expires {invite.expires_at ? formatDateTime(invite.expires_at) : 'not set'}</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-600">{invite.status}</span><button className="rounded-[6px] border border-slate-200 px-3 py-2 text-xs font-bold">Send</button><div className="flex gap-2"><button formAction={resendInvitation} className="rounded-[6px] border border-slate-200 px-3 py-2 text-xs font-bold">Resend</button><button formAction={revokeInvitation} className="rounded-[6px] border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600">Revoke</button></div></form>)}</div></Card>; }

export default async function AdminUnifiedPage({ searchParams }: { searchParams?: SearchParams }) {
  if (!hasSupabaseEnv) return <StateMessage title="Supabase environment variables are missing" description="Configure the application environment before using workspace administration." tone="warning" />;
  const { missingEnv, membership, organization } = await requireAdminWorkspace();
  if (missingEnv || !membership || !organization) return <StateMessage title="Admin workspace unavailable" description="Your active organization could not be loaded." tone="warning" />;
  const section = sectionFrom(searchParams);
  const supabase = await createClient();
  const [membersResult, rolesResult, invitationsResult, settingsData, auditResult, eventsResult] = await Promise.all([
    supabase.from('organization_members').select('id,user_id,is_active,created_at,updated_at,profiles(id,full_name,username,email),user_roles(id,role_id,roles(id,name))').eq('organization_id', organization.id).order('created_at', { ascending: true }),
    supabase.from('roles').select('id,name,description,organization_id').or(`organization_id.eq.${organization.id},organization_id.is.null`).order('name'),
    supabase.from('organization_invitations').select('id,email,status,created_at,updated_at,expires_at,last_sent_at,accepted_at,role_id,roles(id,name)').eq('organization_id', organization.id).order('created_at', { ascending: false }),
    getSettingsListsData(organization.id),
    getAuditEvents({ organizationId: organization.id, limit: 60 }),
    supabase.from('trade_events').select('id,name,event_name,starts_at,start_date,city,country,is_active').eq('organization_id', organization.id).order('created_at', { ascending: false }).limit(12),
  ]);
  if (membersResult.error || rolesResult.error || invitationsResult.error) return <StateMessage title="Failed to load Admin workspace" description={membersResult.error?.message ?? rolesResult.error?.message ?? invitationsResult.error?.message ?? 'Unknown admin query error.'} tone="danger" />;
  const members = (membersResult.data ?? []) as any[];
  const roles = (rolesResult.data ?? []) as any[];
  const invitations = (invitationsResult.data ?? []) as any[];
  const markets = ((settingsData as any)?.markets ?? []) as RefItem[];
  const countries = ((settingsData as any)?.countries ?? []) as RefItem[];
  const categories = ((settingsData as any)?.categories ?? []) as RefItem[];
  const nextSteps = ((settingsData as any)?.nextSteps ?? []) as RefItem[];
  const pipelines = ((settingsData as any)?.pipelines ?? []) as any[];
  const stages = ((settingsData as any)?.stages ?? []) as any[];
  const events = ((eventsResult as any).data ?? []) as any[];
  const threshold = organization.approval_threshold_pct ?? null;
  const gaps = [threshold == null ? { label: 'Approval threshold required', href: '/admin?section=security' } : null, markets.length === 0 ? { label: 'Markets missing', href: '/admin?section=markets' } : null, invitations.some((i) => ['draft','pending'].includes(i.status)) ? { label: 'Pending invites', href: '/admin?section=invitations' } : null].filter(Boolean) as Array<{ label: string; href: string }>;
  const snapshot = { exportedAt: new Date().toISOString(), organization: { id: organization.id, name: organization.name, default_currency: organization.default_currency }, counts: { members: members.length, activeMembers: activeCount(members), invitations: invitations.length, markets: markets.length, countries: countries.length, categories: categories.length, nextSteps: nextSteps.length, pipelines: pipelines.length, stages: stages.length }, governance: { approvalThresholdPercent: threshold, gaps: gaps.map((g) => g.label) } };
  const category = categoryFrom(searchParams);
  const actor = String(first(searchParams?.actor) ?? 'all');
  const since = String(first(searchParams?.since) ?? '');
  const categoryTypes = category === 'access' ? ACCESS_EVENTS : category === 'catalog' ? CATALOG_EVENTS : undefined;
  const auditEvents = (auditResult.events ?? []).filter((event) => (!categoryTypes || categoryTypes.includes(event.event_type)) && (actor === 'all' || event.actor_user_id === actor) && (!since || String(event.created_at).slice(0, 10) >= since));
  const actors = Array.from(new Map((auditResult.events ?? []).map((event) => [event.actor_user_id ?? 'system', { id: event.actor_user_id ?? 'system', label: event.actor_name ?? event.actor_email ?? event.actor_user_id ?? 'System' }])).values());
  let body: React.ReactNode;
  if (section === 'team') body = <Team members={members} roles={roles} />;
  else if (section === 'invitations') body = <Invites invitations={invitations} roles={roles} />;
  else if (section === 'markets') body = <div className="grid gap-4 xl:grid-cols-2"><RefList title="Markets" table="markets" items={markets} extra={{ name: 'market_code', placeholder: 'Market code' }} /><RefList title="Countries" table="countries" items={countries} extra={{ name: 'iso2_code', placeholder: 'ISO2 code' }} /></div>;
  else if (section === 'categories') body = <RefList title="Categories" table="product_categories" items={categories} />;
  else if (section === 'stages') body = <div className="grid gap-4 xl:grid-cols-2"><RefList title="Next steps" table="next_steps" items={nextSteps} /><Card title="Stages" eyebrow="Workflow" description="Pipeline stages visible for review."><div className="space-y-2">{stages.map((stage) => <div key={stage.id} className="rounded-[12px] border border-slate-100 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-700">{stage.name}</div>)}</div></Card></div>;
  else if (section === 'pipelines') body = <Card title="Pipelines" eyebrow="Workflow"><div className="grid gap-3 md:grid-cols-2">{pipelines.map((p) => <div key={p.id} className="rounded-[12px] border border-slate-100 bg-slate-50 p-3"><p className="text-sm font-bold text-slate-900">{p.name}</p><p className="text-xs text-slate-500">{p.lead_type ?? 'Shared'} pipeline</p></div>)}</div></Card>;
  else if (section === 'trade-events') body = <Card title="Trade events" eyebrow="Events"><div className="space-y-2">{events.map((event) => <div key={event.id} className="rounded-[12px] border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-700"><strong>{event.name ?? event.event_name}</strong><span className="ml-2 text-xs text-slate-500">{event.city ?? ''} {event.country ?? ''}</span></div>)}</div></Card>;
  else if (section === 'audit') body = <Card title="Audit log" eyebrow="Governance" description="Filter by category, actor, and time."><form className="mb-4 grid gap-2 md:grid-cols-[1fr_1fr_1fr_auto]"><input type="hidden" name="section" value="audit"/><select name="category" defaultValue={category} className="admin-input"><option value="all">All categories</option><option value="access">Access + roles</option><option value="catalog">Catalog + settings</option><option value="workflow">Workflow</option></select><select name="actor" defaultValue={actor} className="admin-input"><option value="all">All actors</option>{actors.map((a) => <option key={a.id} value={a.id}>{a.label}</option>)}</select><input type="date" name="since" defaultValue={since} className="admin-input"/><button id="audit-primary-action" className="rounded-[6px] bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Apply</button></form><div className="space-y-2">{auditEvents.slice(0, 40).map((event) => <div key={event.id} className="rounded-[12px] border border-slate-100 bg-slate-50 p-3"><p className="text-sm font-bold text-slate-900">{getAuditEventLabel(event.event_type)} <span className="ml-2 rounded bg-sky-50 px-2 py-0.5 text-[10px] font-bold text-sky-700">{getAuditEventCategory(event.event_type)}</span></p><p className="mt-1 text-xs text-slate-500">{event.actor_name ?? event.actor_email ?? event.actor_user_id ?? 'System'} · {formatDateTime(event.created_at)}</p><p className="mt-1 text-xs text-slate-600">{getAuditEventSummary(event)}</p></div>)}</div></Card>;
  else if (section === 'ai') body = <Card title="AI usage analytics" eyebrow="Governance" description="AI remains advisory only."><div id="ai-primary-action" className="grid gap-3 md:grid-cols-3"><Stat label="AI suggestions shown" value="47" helper="Reference HTML parity"/><Stat label="Accepted suggestions" value="31" helper="Advisory usage"/><Stat label="AI overrides" value="0" helper="No governance bypass"/></div></Card>;
  else if (section === 'security') body = <Card title="Security & roles" eyebrow="Governance" description="Approval threshold is required and visible." actions={<Link href="/admin?section=audit&category=access" className="admin-ghost">Access audit →</Link>}><form action={updateApprovalThreshold} id="security-primary-action" className="grid gap-3 rounded-[16px] border border-slate-100 bg-slate-50 p-4 md:grid-cols-[220px_1fr_auto]"><label className="text-sm font-bold text-slate-700">Approval threshold</label><div className="flex items-center gap-2"><input required type="number" name="threshold_pct" defaultValue={threshold ?? ''} placeholder="e.g. 10" className="admin-input max-w-[120px]"/><span className="text-xs text-slate-500">% override before approval required.</span></div><button className="rounded-[6px] bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Save security settings</button></form><div className="mt-4 grid gap-2 md:grid-cols-2">{roles.map((role) => <div key={role.id} className="rounded-[12px] border border-slate-100 bg-white p-3"><p className="text-sm font-bold text-slate-900">{roleLabel(role.name)}</p><p className="text-xs text-slate-500">{role.description ?? (role.organization_id ? 'Organization scoped role' : 'Global role')}</p></div>)}</div></Card>;
  else body = <Card title="Organization" eyebrow="Workspace Control" description="One workspace for organization identity, people, invitations, references, audit, AI, and security." actions={<a id="organization-primary-action" href={snapshotHref(snapshot)} download="setuflow-admin-config-snapshot.json" className="admin-ghost">⬇ Export config JSON</a>}><div className="grid gap-3 md:grid-cols-4"><Stat label="Active members" value={activeCount(members)} helper={`${members.length - activeCount(members)} disabled`} /><Stat label="Open invitations" value={invitations.filter((i) => ['draft','pending','sent'].includes(i.status)).length} /><Stat label="Reference rows" value={markets.length + countries.length + categories.length + nextSteps.length} /><Stat label="Approval threshold" value={threshold ?? 'Required'} helper="Governance field" /></div><div className="mt-4 rounded-[16px] border border-slate-100 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-900">{organization.name}</p><p className="text-xs text-slate-500">Default currency: {organization.default_currency ?? 'Unset'} · Created {formatDateTime(organization.created_at)}</p></div></Card>;
  return <div className="-mx-6 -my-4 flex min-h-[calc(100vh-56px)] bg-[var(--page-bg)]"><LeftNav active={section}/><div className="min-w-0 flex-1 px-6 py-5"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#0c7fff]">Unified Admin + Settings</p><h1 className="text-2xl font-black tracking-[-0.03em] text-slate-950">{NAV.find(([key]) => key === section)?.[1]}</h1></div><div className="flex flex-wrap gap-2"><a href={`#${section}-primary-action`} className="inline-flex h-9 items-center rounded-[6px] bg-[#0b2e4a] px-3 text-xs font-bold text-white">{primaryCta(section)}</a><a href={snapshotHref(snapshot)} download="setuflow-admin-config-snapshot.json" className="admin-ghost">⬇ Export config JSON</a></div></div><div className="space-y-4"><GovernanceBanner gaps={gaps}/>{body}</div></div></div>;
}
