import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { requireWorkspace } from '@/lib/workspace/auth';
import { resolveUserMailbox } from '@/lib/mail/resolve-user-mailbox';
import { matchCommunicationIdentity } from '@/lib/contacts/identity';
import { MailIntelligenceDetail } from '@/features/mail/components/mail-intelligence-detail';

export const dynamic='force-dynamic';
const title=(value:string)=>value?value[0].toUpperCase()+value.slice(1):value;
export default async function MailCrmContextPage({params}:{params:{id:string}}){
  const workspace=await requireWorkspace();const db=(await createClient())as any;const org=workspace.organization!.id;const mailbox=await resolveUserMailbox(db,org,workspace.user!.id,'id,address,status');
  if(!mailbox)return <div className="p-8">Mailbox unavailable.</div>;
  const{data:message}=await db.from('mail_messages').select('id,direction,from_address,to_addresses,subject,thread_id').eq('id',params.id).eq('mailbox_id',mailbox.id).maybeSingle();
  if(!message)return <div className="p-8">Message not found.</div>;
  const peer=String(message.direction==='inbound'?message.from_address:message.to_addresses?.[0]??'').trim().toLowerCase();const identity=await matchCommunicationIdentity(db,org,peer);
  const{data:explicitLinks}=message.thread_id?await db.from('mail_crm_links').select('id,entity_type,entity_id').eq('organization_id',org).eq('mailbox_id',mailbox.id).eq('thread_id',message.thread_id):{data:[]};const linked=new Set((explicitLinks??[]).map((row:any)=>`${row.entity_type}:${row.entity_id}`));
  const returnTo=`/mail`;
  return <div className="mx-auto max-w-4xl p-6 md:p-8"><div className="flex items-start gap-4"><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">Setu Mail · CRM identity</div><h1 className="mt-1 text-2xl font-black text-slate-950">{peer||'Conversation context'}</h1><p className="mt-2 text-sm text-slate-500">{message.subject||'No subject'} · Matching is permission-scoped and never creates CRM records automatically.</p></div><Link href="/mail" className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">Back to Mail</Link></div>
  <MailIntelligenceDetail messageId={message.id}/>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Contact</h2>{identity.contact?<div className="mt-3 rounded-xl bg-slate-50 p-4"><div className="font-bold">{`${identity.contact.first_name} ${identity.contact.last_name}`.trim()||identity.contact.email}</div><div className="mt-1 text-sm text-slate-500">{[identity.contact.job_title,identity.contact.company,title(identity.contact.relationship_type)].filter(Boolean).join(' · ')}</div><div className="mt-3 flex flex-wrap gap-2"><Link href={identity.contact.href} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Open Contact</Link>{message.thread_id&&!linked.has(`contact:${identity.contact.id}`)?<Link href={`/mail/link?thread=${message.thread_id}&entityType=contact&entityId=${identity.contact.id}&label=${encodeURIComponent('Contact · '+(identity.contact.company||identity.contact.email))}&returnTo=${encodeURIComponent(returnTo)}`} className="rounded-lg bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Link conversation</Link>:<span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Linked</span>}</div></div>:<div className="mt-3"><p className="text-sm text-slate-500">No Contact exists for this email.</p><Link href={`/contacts?create=1&email=${encodeURIComponent(peer)}`} className="mt-2 inline-block rounded-lg bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Create Contact</Link></div>}</section>
  <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">CRM records</h2>{identity.records.length?<div className="mt-3 space-y-2">{identity.records.map(record=><div key={record.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-4"><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase text-blue-600">{title(record.type)}</div><div className="truncate text-sm font-bold">{record.company_name||record.contact_name||record.email}</div></div><Link href={record.href} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Open</Link>{message.thread_id&&!linked.has(`${record.type}:${record.id}`)?<Link href={`/mail/link?thread=${message.thread_id}&entityType=${record.type}&entityId=${record.id}&label=${encodeURIComponent(title(record.type)+' · '+(record.company_name||record.contact_name||record.email||''))}&returnTo=${encodeURIComponent(returnTo)}`} className="rounded-lg bg-[#0b2e4a] px-3 py-2 text-xs font-bold text-white">Link conversation</Link>:<span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Linked</span>}</div>)}</div>:<div className="mt-3"><p className="text-sm text-slate-500">No accessible Lead, Buyer or Supplier matches this identity.</p><Link href={`/leads?quickLead=1&leadType=buyer&sourceType=setu_mail&sourceLabel=${encodeURIComponent(`Setu Mail · ${peer}`)}`} className="mt-2 inline-block rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Create Lead</Link></div>}</section>
  </div>;
}