import type { CSSProperties, ReactNode } from 'react';
const shellFont='-apple-system,BlinkMacSystemFont,system-ui,sans-serif'; const navy='#0b2e4a'; const slateBorder='#e2e8f0';
export type SetuTopbarAction={label:ReactNode;href?:string;active?:boolean;variant?:'primary'|'secondary'|'ghost'}; export type SetuStat={label:ReactNode;value:ReactNode;meta?:ReactNode;accent?:string};
export function SetuWorkspaceShell({children}:{children:ReactNode}){return <div style={{fontFamily:shellFont,fontSize:'13px',lineHeight:1.5,color:'#1e293b',background:'#f0f4f8',minHeight:'100vh'}}>{children}</div>}
function actionStyle(action:SetuTopbarAction):CSSProperties{const isPrimary=action.variant==='primary'||action.active;return{display:'inline-flex',alignItems:'center',justifyContent:'center',minHeight:'32px',padding:'6px 14px',borderRadius:'7px',border:isPrimary?`1px solid ${navy}`:`1px solid ${slateBorder}`,background:isPrimary?navy:action.variant==='ghost'?'transparent':'white',color:isPrimary?'white':'#334155',fontSize:'12px',fontWeight:700,textDecoration:'none',whiteSpace:'nowrap'}}
export function SetuTopbarActions({eyebrow,title,subtitle='SETU Groups LLC',section,actions}:{eyebrow?:ReactNode;title:ReactNode;subtitle?:ReactNode;section?:ReactNode;actions?:SetuTopbarAction[]}){return <header style={{background:'white',borderBottom:`1px solid ${slateBorder}`,padding:'0 24px',minHeight:'56px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'16px',position:'sticky',top:0,zIndex:50}}><div style={{display:'flex',alignItems:'center',gap:'14px',minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:'8px',padding:'5px 12px',borderRadius:'6px',background:'rgba(11,46,74,.06)',border:'1px solid rgba(11,46,74,.12)',flexShrink:0}}><div><div style={{fontSize:'11px',fontWeight:800,color:'#1F487C',letterSpacing:'-.1px'}}>SETU <span style={{color:'#279491'}}>Flow</span> CRM</div><div style={{fontSize:'8px',color:'#94a3b8',letterSpacing:'.1em',textTransform:'uppercase'}}>{subtitle}</div></div></div><div style={{width:'1px',height:'24px',background:slateBorder,flexShrink:0}}/><div style={{minWidth:0}}>{eyebrow?<div style={{fontSize:'10px',fontWeight:700,letterSpacing:'.16em',textTransform:'uppercase',color:'#0c7fff'}}>{eyebrow}</div>:null}<div style={{fontSize:'16px',fontWeight:800,color:'#1e293b',letterSpacing:'-.3px',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{title}</div>{section?<div style={{fontSize:'10px',color:'#64748b'}}>{section}</div>:null}</div></div>{actions?.length?<nav style={{display:'flex',alignItems:'center',gap:'8px',flexWrap:'wrap',justifyContent:'flex-end'}}>{actions.map((action,index)=>action.href?<a key={index} href={action.href} style={actionStyle(action)}>{action.label}</a>:<span key={index} style={actionStyle(action)}>{action.label}</span>)}</nav>:null}</header>}
export function SetuFilterBar({children,meta}:{children:ReactNode;meta?:ReactNode}){return <div style={{background:'white',borderBottom:`1px solid ${slateBorder}`,padding:'10px 24px',display:'flex',alignItems:'center',gap:'10px',flexWrap:'wrap'}}>{children}<div style={{marginLeft:'auto',fontSize:'10px',fontWeight:700,color:'#94a3b8'}}>{meta}</div></div>}
export function SetuStatsStrip({stats}:{stats:SetuStat[]}){return <div style={{display:'grid',gridTemplateColumns:`repeat(${Math.min(Math.max(stats.length,1),6)}, minmax(0, 1fr))`,gap:'10px',padding:'16px 24px 0'}}>{stats.map((stat,index)=><div key={index} style={{position:'relative',overflow:'hidden',borderRadius:'16px',border:`1px solid ${slateBorder}`,background:'white',padding:'13px 15px',boxShadow:'0 1px 3px rgba(15,23,42,.06)'}}><div style={{position:'absolute',top:0,left:0,right:0,height:'3px',background:stat.accent??'#0c7fff',borderRadius:'16px 16px 0 0'}}/><div style={{fontSize:'9px',fontWeight:700,letterSpacing:'.14em',textTransform:'uppercase',color:'#94a3b8',marginBottom:'7px'}}>{stat.label}</div><div style={{fontSize:'22px',fontWeight:800,letterSpacing:'-.03em',color:'#0f172a',lineHeight:1}}>{stat.value}</div>{stat.meta?<div style={{fontSize:'10px',color:'#94a3b8',marginTop:'4px',fontWeight:600}}>{stat.meta}</div>:null}</div>)}</div>}
export function SetuSlideInDrawer({title,children,open=true}:{title:ReactNode;children:ReactNode;open?:boolean}){if(!open)return null;return <aside style={{background:'white',border:`1px solid ${slateBorder}`,borderRadius:'22px',boxShadow:'0 18px 45px rgba(15,23,42,.12)',overflow:'hidden'}}><div style={{padding:'14px 18px',borderBottom:`1px solid ${slateBorder}`,fontSize:'14px',fontWeight:800,color:'#0f172a'}}>{title}</div><div style={{padding:'16px 18px'}}>{children}</div></aside>}
