import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { hasSupabaseEnv } from '@/lib/env';
import { requireWorkspace } from '@/lib/workspace/auth';

function num(v: unknown, fallback = 0) { const n = Number(v ?? fallback); return Number.isFinite(n) ? n : fallback; }
function txt(v: unknown, fallback = '-') { const s = String(v ?? '').trim(); return s || fallback; }
function cut(v: unknown, max = 48, fallback = '-') { const s = txt(v, fallback); return s.length > max ? s.slice(0, max - 3) + '...' : s; }
function money(v: unknown, c = 'USD') { return `${c} ${num(v).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function dateOut(v: unknown) { const s = txt(v, ''); if (!s) return '-'; const d = new Date(s.includes('T') ? s : `${s}T00:00:00`); return Number.isNaN(d.getTime()) ? '-' : d.toLocaleDateString('en-GB'); }
function esc(v: string) { return String(v ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/[\r\n]+/g, ' '); }
function rgb(hex: string) { const x = Number.parseInt(hex.replace('#',''), 16); return `${(((x>>16)&255)/255).toFixed(3)} ${(((x>>8)&255)/255).toFixed(3)} ${((x&255)/255).toFixed(3)}`; }
function wrap(s: string, w: number) { const out: string[] = []; let cur = ''; for (const word of txt(s, '').split(/\s+/).filter(Boolean)) { const next = cur ? `${cur} ${word}` : word; if (next.length > w && cur) { out.push(cur); cur = word; } else cur = next; } if (cur) out.push(cur); return out.length ? out : ['']; }
function mode(v: unknown) { const s = txt(v, 'unit').toLowerCase(); return s.includes('kg') || s.includes('bulk') ? 'KG' : s.includes('case') ? 'CASE' : 'UNIT'; }
function basis(v: unknown) { return txt(v, 'FOB').toUpperCase().replace(/_/g, ' '); }
function months(v: unknown) { const x = num(v); return x > 0 ? `${x} months` : 'Available per SKU'; }
function days(v: unknown) { const x = num(v); return x > 0 ? `${Math.max(1, x - 3)}-${x} days` : 'Confirm per category/order'; }

type Row = { sku: string; product: string; hs: string; pack: string; uom: string; units: string; moq: string; origin: string; unit: number; net: number; discount: string; note: string; total: number; shelf: string; lead: string };
function buildPdf(data: { quoteNo: string; org: any; buyer: any; market: string; destination: string; incoterm: string; place: string; currency: string; quoteDate: string; validUntil: string; terms: string; rows: Row[]; leadSummary: string }) {
  const objects: string[] = [];
  const add = (body: string) => { objects.push(body); return objects.length; };
  const font = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const bold = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const boxes: string[] = [];
  const texts: string[] = [];
  const navy = '#0b2e4a';
  const box = (x:number,y:number,w:number,h:number,fill?:string,stroke?:string) => { if (fill) boxes.push(`${rgb(fill)} rg ${x} ${y} ${w} ${h} re f`); if (stroke) boxes.push(`${rgb(stroke)} RG ${x} ${y} ${w} ${h} re S`); };
  const text = (x:number,y:number,s:string,size=7,isBold=false,color='#0f172a') => { texts.push(`/${isBold?'F2':'F1'} ${size} Tf\n${rgb(color)} rg\n1 0 0 1 ${x} ${y} Tm (${esc(s)}) Tj`); };
  const right = (x:number,y:number,s:string,size=7,isBold=false,color='#0f172a') => text(Math.max(18, x - s.length * size * 0.48), y, s, size, isBold, color);
  box(18,742,48,34,navy); text(30,757,'LOGO',8,true,'#ffffff');
  text(74,762,cut(data.org.legal_name ?? data.org.name,30,'SETU Flow'),10,true,navy);
  text(74,748,cut(data.org.website,36,'Streamlining Global Trade'),6.5,false,'#475569');
  text(190,764,'SETU Flow - Client Price List',17,true,navy); text(190,746,'Pro Forma Quotation',9,false,'#334155');
  box(465,742,128,38,navy); text(475,762,data.quoteNo,10,true,'#ffffff'); text(475,748,`Quote Date: ${data.quoteDate}`,6.3,false,'#ffffff'); text(475,738,`Valid Until: ${data.validUntil}`,6.3,false,'#ffffff');
  box(18,604,170,124,'#ffffff','#cbd5e1'); text(28,710,'SELLER / EXPORTER',7,true,navy); text(28,692,cut(data.org.legal_name ?? data.org.name,32),8,true); wrap(txt(data.org.registered_address,''),32).slice(0,3).forEach((l,i)=>text(28,677-i*9,l,6.3)); text(28,644,cut(data.org.contact_email,34),6.3); text(28,633,cut(data.org.website,34),6.3); text(28,618,`Tax/VAT: ${cut(data.org.tax_id,22)}`,6.3,true);
  box(202,604,150,124,'#ffffff','#cbd5e1'); text(212,710,'BUYER / IMPORTER',7,true,navy); text(212,692,cut(data.buyer.company_name,30,'Unknown customer'),8,true); text(212,678,cut(data.buyer.contact_name,30,''),6.3); text(212,667,cut(data.buyer.country,30,data.destination),6.3); text(212,650,cut(data.buyer.email,32),6.3); text(212,639,cut(data.buyer.phone,32),6.3);
  box(362,604,231,124,'#ffffff','#cbd5e1'); [['Destination',data.destination],['Market',data.market],['Basis',`${data.incoterm} (Incoterms 2020)`],['Named place',data.place],['Currency',data.currency],['Payment terms','As agreed / per quote terms'],['Lead time',data.leadSummary],['Taxes','Buyer import duties / VAT unless included']].forEach(([k,v],i)=>{ const y=716-i*14; box(362,y-4,231,14,i%2?'#ffffff':'#f4f7fb','#e2e8f0'); text(372,y,k.toUpperCase(),5.5,true,'#334155'); text(458,y,cut(v,35),6.1); });
  box(18,582,575,14,'#eef6ff','#bfdbfe'); text(26,586,'Export sales may be zero-rated/exempt where applicable; destination duty, VAT/GST and local taxes are buyer account unless included.',5.6,false,'#1e3a8a');
  let y=560; box(18,y-15,575,18,navy); [['#',22],['SKU',42],['Product',82],['HS',148],['Pack',184],['UOM',222],['Units',256],['MOQ',290],['Origin',322],['Unit',370],['Disc',412],['Net',448],['Notes',492]].forEach(([h,x])=>text(Number(x),y-9,String(h),5.6,true,'#ffffff')); y-=22;
  data.rows.slice(0,8).forEach((r,i)=>{ box(18,y-16,575,22,i%2?'#ffffff':'#f8fafc','#dbe3ed'); text(22,y,String(i+1),5.7,true); text(42,y,cut(r.sku,13),5.5); text(82,y,cut(r.product,18),5.5); text(148,y,cut(r.hs,9),5.5); text(184,y,cut(r.pack,10),5.5); text(222,y,r.uom,5.5); right(280,y,r.units,5.5); right(312,y,r.moq,5.5); text(322,y,cut(r.origin,10),5.5); right(404,y,money(r.unit,data.currency),5.5); right(440,y,r.discount,5.5); right(486,y,money(r.net,data.currency),5.5); text(492,y,cut(r.note,18),5.2); y-=22; });
  const total=data.rows.reduce((s,r)=>s+r.total,0); const shelf=Array.from(new Set(data.rows.map(r=>r.shelf))).slice(0,2).join(', ') || 'Available per SKU'; const origin=Array.from(new Set(data.rows.map(r=>r.origin).filter(Boolean))).slice(0,3).join(', ') || 'Confirm per SKU'; y-=8;
  box(18,y-86,282,86,'#ffffff','#cbd5e1'); text(28,y-13,'COMMERCIAL & COMPLIANCE',7,true,navy); [`Country of origin: ${origin}`,`Shelf life: ${shelf}`,'Product specs, ingredients and nutrition available on request.','Export docs: invoice, packing list, certificate of origin, and applicable certificates.','HS codes are indicative and subject to buyer validation.'].forEach((l,i)=>text(28,y-27-i*10,`• ${cut(l,82)}`,5.7));
  box(316,y-86,277,86,'#ffffff','#cbd5e1'); text(326,y-13,`FINANCIAL SUMMARY (${data.currency})`,7,true,navy); [['Subtotal after discount',money(total,data.currency)],['Documentation / packaging charge',money(0,data.currency)],['Freight / insurance','Not included unless stated'],['Taxes / duties','Buyer account unless included']].forEach(([k,v],i)=>{text(326,y-28-i*11,k,5.8); right(582,y-28-i*11,v,5.8);}); box(316,y-86,277,18,navy); text(326,y-80,'GRAND TOTAL',9,true,'#ffffff'); right(582,y-80,money(total,data.currency),9,true,'#ffffff');
  y-=104; box(18,y-70,575,70,'#ffffff','#cbd5e1'); text(28,y-13,'TERMS & CONDITIONS',7,true,navy); [`Quote valid until ${data.validUntil}.`,`Prices quoted on ${data.incoterm} basis from ${data.place}.`,'Destination import duties, VAT/GST, customs charges and destination handling are buyer account unless included.','Order confirmation is subject to agreed quantities, pack sizes, MOQs and specifications.','Export documentation will be provided as per applicable regulations.','Prices may change before confirmation if cost, freight, policy or currency inputs change.'].forEach((l,i)=>text(i<3?28:316,y-27-(i%3)*12,`${i+1}. ${cut(l,74)}`,5.6));
  y-=82; box(18,y-52,282,52,'#ffffff','#cbd5e1'); text(28,y-13,'LEAD TIME & SHIPMENT',7,true,navy); [`Lead time: ${data.leadSummary}.`,`Port/place: ${data.place}.`,'Shipment schedule and routing are confirmed after PO and document review.'].forEach((l,i)=>text(28,y-27-i*9,`• ${cut(l,72)}`,5.6)); box(316,y-52,277,52,'#ffffff','#cbd5e1'); text(326,y-13,'NOTES',7,true,navy); ['Quote is confidential and intended solely for the addressee.','Pricing basis and charges must be reviewed before sending.',cut(data.terms,78)].forEach((l,i)=>text(326,y-27-i*9,`• ${l}`,5.6));
  box(18,36,575,52,'#ffffff','#cbd5e1'); text(28,73,'AUTHORIZED SIGNATURE (SELLER)',6.5,true,navy); text(28,58,'Name: ___________________________',5.7); text(28,47,'Date: ____________________________',5.7); text(236,73,'GET IN TOUCH',6.5,true,navy); text(236,60,cut(data.org.contact_email,34),5.7); text(236,49,cut(data.org.website,34),5.7); text(420,73,'ACCEPTANCE (IMPORTER)',6.5,true,navy); text(420,60,'Accepted by: _____________________',5.7); text(420,49,'Signature: _______________________',5.7); box(0,14,612,14,navy); text(245,18,'THANK YOU FOR YOUR BUSINESS!',7.5,true,'#ffffff');
  const ops=[...boxes,'BT',...texts,'ET'].join('\n'); const contentId=add(`<< /Length ${Buffer.byteLength(ops)} >>\nstream\n${ops}\nendstream`); const pageId=add(`<< /Type /Page /Parent 0 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentId} 0 R >>`); const pagesId=add(`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`); objects[pageId-1]=objects[pageId-1].replace('/Parent 0 0 R',`/Parent ${pagesId} 0 R`); const catalogId=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
  let pdf='%PDF-1.4\n'; const offsets=[0]; objects.forEach((body,i)=>{offsets.push(Buffer.byteLength(pdf)); pdf+=`${i+1} 0 obj\n${body}\nendobj\n`;}); const xref=Buffer.byteLength(pdf); pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`; for(let i=1;i<=objects.length;i++) pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`; pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(pdf,'utf8');
}

export async function GET(_request: Request, { params }: { params: { quoteId: string } }) {
  if (!hasSupabaseEnv) return NextResponse.json({ error: 'Supabase is not configured.' }, { status: 500 });
  const workspace = await requireWorkspace(); const organizationId = workspace.organization?.id; if (!organizationId) return NextResponse.json({ error: 'Workspace not found.' }, { status: 403 });
  const db = await createClient() as any; const quoteId = params.quoteId;
  const { data: quote, error } = await db.from('quotes').select('id, quote_number, lead_id, currency, display_currency, updated_at, created_at, valid_until, pricing_basis, destination_port, market_id, country_id, freight_profile_id, approval_required, approved_at, notes_customer').eq('organization_id', organizationId).eq('id', quoteId).maybeSingle();
  if (error) return NextResponse.json({ error: error.message }, { status: 500 }); if (!quote?.id) return NextResponse.json({ error: 'Quote not found.' }, { status: 404 });
  const [{data: lead},{data: items},{data: org},{data: market},{data: country},{data: freight}] = await Promise.all([
    db.from('leads').select('id, company_name, contact_name, email, phone, country').eq('organization_id', organizationId).eq('id', quote.lead_id).maybeSingle(),
    db.from('quote_line_items').select('id, product_id, product_variant_id, quantity, unit_price, catalog_price_amount, is_price_overridden, override_reason, notes').eq('quote_id', quote.id).order('created_at', { ascending: true }),
    db.from('organizations').select('id, name, legal_name, logo_url, registered_address, website, contact_email, tax_id, quote_terms_conditions, default_currency').eq('id', organizationId).maybeSingle(),
    quote.market_id ? db.from('markets').select('id, name').eq('organization_id', organizationId).eq('id', quote.market_id).maybeSingle() : Promise.resolve({data:null}),
    quote.country_id ? db.from('countries').select('id, name, default_port_of_loading').eq('organization_id', organizationId).eq('id', quote.country_id).maybeSingle() : Promise.resolve({data:null}),
    quote.freight_profile_id ? db.from('freight_profiles').select('id, destination_port, notes').eq('organization_id', organizationId).eq('id', quote.freight_profile_id).maybeSingle() : Promise.resolve({data:null})
  ]);
  const lines = (items ?? []) as any[]; const productIds = Array.from(new Set(lines.map(l=>l.product_id).filter(Boolean))); const variantIds = Array.from(new Set(lines.map(l=>l.product_variant_id).filter(Boolean)));
  const [{data: products},{data: variants}] = await Promise.all([
    productIds.length ? db.from('products').select('id, name, sku, sku_code, hsn_code, category_id').eq('organization_id', organizationId).in('id', productIds) : Promise.resolve({data:[]}),
    variantIds.length ? db.from('product_variants').select('id, product_id, name, sku_code, hsn_code, country_of_origin, pack_size_value, pack_size_unit, pack_label, units_per_case, moq_cases, moq_kg, pricing_mode_default, shipment_notes, lead_time_days, shelf_life_months').in('id', variantIds) : Promise.resolve({data:[]})
  ]);
  const productMap = new Map((products ?? []).map((p:any)=>[p.id,p])); const variantMap = new Map((variants ?? []).map((v:any)=>[v.id,v])); const categoryIds = Array.from(new Set((products ?? []).map((p:any)=>p.category_id).filter(Boolean))); const {data: categories} = categoryIds.length ? await db.from('product_categories').select('id, name, default_lead_time_days, default_shelf_life_months, default_country_of_origin, default_shipment_notes').eq('organization_id', organizationId).in('id', categoryIds) : {data:[]}; const categoryMap = new Map((categories ?? []).map((c:any)=>[c.id,c]));
  const currency = String(quote.display_currency ?? quote.currency ?? org?.default_currency ?? 'USD');
  const rows: Row[] = lines.map((l:any)=>{ const p:any = l.product_id ? productMap.get(l.product_id) : {}; const v:any = l.product_variant_id ? variantMap.get(l.product_variant_id) : {}; const c:any = p?.category_id ? categoryMap.get(p.category_id) : {}; const m=mode(v?.pricing_mode_default ?? quote.pricing_basis); const net=num(l.unit_price); const catalog=l.catalog_price_amount == null ? net : num(l.catalog_price_amount); return { sku:txt(v?.sku_code ?? p?.sku_code ?? p?.sku), product:txt(p?.name ?? v?.name,'Catalog line'), hs:txt(v?.hsn_code ?? p?.hsn_code,'TBC'), pack:txt(v?.pack_label) !== '-' ? txt(v?.pack_label) : (txt(v?.pack_size_value,'') && txt(v?.pack_size_unit,'') ? `${txt(v?.pack_size_value,'')}${txt(v?.pack_size_unit,'')}` : '-'), uom:m==='KG'?'Kg':m==='CASE'?'Case':'Unit', units:txt(v?.units_per_case), moq:m==='KG'?txt(v?.moq_kg,'0'):txt(v?.moq_cases ?? v?.moq_kg,'0'), origin:txt(v?.country_of_origin ?? c?.default_country_of_origin,'Confirm per SKU'), unit:catalog, net, discount:l.is_price_overridden && catalog ? `${(((catalog-net)/catalog)*100).toFixed(1)}%` : '-', note:txt(l.override_reason ?? l.notes ?? v?.shipment_notes ?? c?.default_shipment_notes), total:num(l.quantity)*net, shelf:months(v?.shelf_life_months ?? c?.default_shelf_life_months), lead:days(v?.lead_time_days ?? c?.default_lead_time_days) }; });
  const place = txt(quote.destination_port ?? freight?.destination_port ?? country?.default_port_of_loading, 'Confirm port/place before sending'); const leadSummary = Array.from(new Set(rows.map(r=>r.lead))).slice(0,2).join(', ') || 'Confirm per category/order';
  const pdf = buildPdf({ quoteNo:`Quote ${quote.quote_number ?? quote.id.slice(0,8)}`, org:org ?? {name:workspace.organization?.name}, buyer:lead ?? {}, market:txt(market?.name), destination:txt(country?.name ?? lead?.country), incoterm:basis(quote.pricing_basis), place, currency, quoteDate:dateOut(quote.updated_at ?? quote.created_at), validUntil:dateOut(quote.valid_until), terms:txt(org?.quote_terms_conditions ?? quote.notes_customer, 'Prices are subject to validity, Incoterms basis, final order confirmation, agreed payment terms, and buyer destination taxes/duties unless included.'), rows, leadSummary });
  await db.from('documents').upsert({ organization_id: organizationId, related_entity: 'quote', related_id: quote.id, file_name: `quote-${quote.quote_number ?? quote.id.slice(0,8)}.pdf`, file_url: `/api/quotes/${quote.id}/pdf`, doc_type: 'quote_pdf', uploaded_by: workspace.user?.id ?? null, version: 1, status: quote.approval_required && !quote.approved_at ? 'pending_approval' : 'ready' }, { onConflict: 'organization_id,related_entity,related_id,file_name' }).then(() => null);
  return new Response(new Uint8Array(pdf), { status: 200, headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `inline; filename="quote-${quote.quote_number ?? quote.id.slice(0,8)}.pdf"`, 'Cache-Control': 'no-store' } });
}
