-- Sprint 25 / S25-TS-002
-- Superseded by 20260615165500_s25_ts_002_trial_lead_trigger.sql.
-- This placeholder is intentionally a no-op so future fresh database replays use the
-- smaller trigger-based implementation that keeps internal lead creation scoped to
-- trade_show_trial_workspaces inserts and updates.
