import type { SVGProps } from 'react';
import { siWhatsapp } from 'simple-icons/icons';
import {
  AlertTriangle,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Camera,
  Calendar,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Circle,
  CreditCard,
  Database,
  File,
  FileCheck,
  FileDown,
  FileText,
  Flag,
  Folder,
  Globe2,
  Home,
  KeyRound,
  LayoutDashboard,
  LineChart,
  Lock,
  Mail,
  MessageCircle,
  Package,
  Paperclip,
  Phone,
  Plane,
  Plug,
  Puzzle,
  QrCode,
  Rocket,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Tags,
  Truck,
  UserCircle,
  Users,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

function BrandSvgIcon({ path, className, ...props }: SVGProps<SVGSVGElement> & { path: string }) {
  return (
    <svg aria-hidden="true" role="img" viewBox="0 0 24 24" className={className} fill="currentColor" {...props}>
      <path d={path} />
    </svg>
  );
}

const BRAND_ICONS = {
  whatsapp: siWhatsapp.path,
};

const ICONS: Record<string, LucideIcon> = {
  address: UserCircle,
  'address-card-o': UserCircle,
  admin: Building2,
  analytics: LineChart,
  archive: Package,
  'arrow-down': ChevronRight,
  'arrow-up': ChevronRight,
  'bar-chart': BarChart3,
  bars: LayoutDashboard,
  bell: Bell,
  'bell-o': Bell,
  billing: CreditCard,
  briefcase: Briefcase,
  building: Building2,
  'building-o': Building2,
  calendar: Calendar,
  camera: Camera,
  capture: Camera,
  catalog: Package,
  check: CheckSquare,
  'check-circle': CheckSquare,
  'check-circle-o': CheckSquare,
  'check-square-o': CheckSquare,
  circle: Sparkles,
  'circle-o': Sparkles,
  clipboard: FileCheck,
  'clipboard-check': FileCheck,
  clock: Calendar,
  'clock-o': Calendar,
  cogs: Settings,
  'comments-o': MessageCircle,
  compliance: ShieldCheck,
  country: Globe2,
  database: Database,
  dashboard: LayoutDashboard,
  docs: FileText,
  document: FileText,
  documents: FileText,
  download: FileDown,
  edit: Settings,
  envelope: Mail,
  'envelope-open-o': Mail,
  event: Calendar,
  events: Calendar,
  exchange: Send,
  'external-link': Send,
  'external-link-alt': Send,
  file: File,
  'file-o': File,
  'file-check': FileCheck,
  'file-down': FileDown,
  'file-pdf-o': FileText,
  pdf: FileText,
  'file-text': FileText,
  'file-text-o': FileText,
  filter: SlidersHorizontal,
  flag: Flag,
  folder: Folder,
  'folder-open-o': Folder,
  globe: Globe2,
  'globe-2': Globe2,
  history: ShieldCheck,
  home: Home,
  integrations: Puzzle,
  key: KeyRound,
  lead: Users,
  leads: Users,
  link: Send,
  lock: Lock,
  'line-chart': LineChart,
  magic: Sparkles,
  mail: Mail,
  market: Globe2,
  markets: Globe2,
  'paper-plane-o': Send,
  paperclip: Paperclip,
  phone: Phone,
  pipeline: BarChart3,
  plane: Plane,
  plug: Plug,
  plus: Rocket,
  product: Package,
  products: Package,
  puzzle: Puzzle,
  qrcode: QrCode,
  quote: FileText,
  quotes: FileText,
  report: BarChart3,
  reports: BarChart3,
  rocket: Rocket,
  search: SlidersHorizontal,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  ship: Ship,
  'shopping-bag': ShoppingBag,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  supplier: Truck,
  suppliers: Truck,
  tags: Tags,
  tasks: CheckSquare,
  'th-large': LayoutDashboard,
  th: LayoutDashboard,
  times: X,
  trash: X,
  truck: Truck,
  user: UserCircle,
  users: Users,
  'user-circle-o': UserCircle,
  warning: AlertTriangle,
  'exclamation-circle': AlertTriangle,
  'exclamation-triangle': AlertTriangle,
  wrench: Wrench,
  'angle-left': ChevronLeft,
  'angle-right': ChevronRight,
};

export function FaIcon({
  icon,
  className,
  fixedWidth = false,
}: {
  icon: string;
  className?: string;
  fixedWidth?: boolean;
}) {
  const brandPath = BRAND_ICONS[icon as keyof typeof BRAND_ICONS];
  if (brandPath) return <BrandSvgIcon path={brandPath} className={cn('inline-block h-[1em] w-[1em]', fixedWidth && 'shrink-0', className)} />;
  const Icon = ICONS[icon] ?? Sparkles;
  return <Icon aria-hidden="true" className={cn('inline-block h-[1em] w-[1em] stroke-[2.1]', fixedWidth && 'shrink-0', className)} />;
}
